---
config:
    debug: 2
    agent: Firefox
do:
- walk:
    to: http://www.johnstonmurphy.com/
    do:
    - find:
        path: li.level-3LI>a
        do:
        - parse:
            attr: href
        - space_dedupe
        - trim
        - if:
            match: \w+
            do:
            - normalize:
                routine: url
            - variable_set: url
            - walk:
                to: value
                do:
                - variable_set:
                    field: total
                    value: 0
                - find:
                    path: div.results-hits
                    do:
                    - parse:
                        filter: (\d+)
                    - variable_set: total
                    - eval:
                        routine: js
                        body: (function () {var pages = []; for (var i=0; i <= <%total%>; i+=12) {pages.push(i)}; return pages.join(",");})();
                    - to_block
                    - split:
                        context: text
                        delimiter: ","
                    - find: 
                        path: .splitted 
                        do: 
                        - parse
                        - variable_set: start
                        - register_set: <%url%>?sz=12&start=<%start%>&format=page-element
                        - walk:
                            to: value
                            do:
                            - find:
                                path: a.name-link
                                do:
                                - parse:
                                    attr: href
                                    filter: ^([^\?]+)
                                - space_dedupe
                                - trim
                                - if:
                                    match: \w+
                                    do:
                                    - normalize:
                                        routine: url
                                    - link_add:
                                        pool: pages
- walk:
    to: links
    pool: pages
    do:
    - sleep: 2
    - find:
        path: 'div#pdpMain'
        do:
        - variable_clear: pid
        - object_new: product
        - eval:
            routine: js
            body: '(function (){var d = new Date(); return d.toISOString()})();'
        - object_field_set:
            object: product
            field: date
        - static_get: url
        - object_field_set:
            object: product
            field: url
        - find:
            path: h1.product-name
            do:
            - parse
            - space_dedupe
            - trim
            - object_field_set:
                object: product
                field: name
        - register_set: Johnston & Murphy
        - object_field_set:
            object: product
            field: brand
        - find:
            in: doc
            path: a.breadcrumb-element
            do:
            - parse
            - space_dedupe
            - trim
            - if:
                match: \w+
                do:
                - object_field_set:
                    object: product
                    joinby: "|"
                    field: categories
        - find:
            path: input.selectedStyleId
            do:
            - parse:
                attr: value
            - space_dedupe
            - trim
            - if:
                match: \w+
                do:
                - variable_set: pid
                - object_field_set:
                    object: product
                    field: sku
        - find:
            path: a.MagicZoomPlus
            do:
            - parse:
                attr: href
            - space_dedupe
            - trim
            - if:
                match: \w+
                do:
                - normalize:
                    routine: url
                - object_field_set:
                    object: product
                    joinby: "|"
                    field: images
        - find:
            path: div.product-thumbnails>ul>li>a
            do:
            - parse:
                attr: href
            - space_dedupe
            - trim
            - if:
                match: \w+
                do:
                - normalize:
                    routine: url
                - object_field_set:
                    object: product
                    joinby: "|"
                    field: images
        - find:
            path: ul.Color>li>a
            do:
            - parse:
                attr: title
            - space_dedupe
            - trim
            - if:
                match: \w+
                do:
                - object_field_set:
                    object: product
                    joinby: "|"
                    field: variations
            - parse:
                attr: href
            - space_dedupe
            - trim
            - if:
                match: \w+
                do:
                - normalize:
                    routine: url
                - walk:
                    to: value
                    do:
                    - find:
                        path: a.MagicZoomPlus
                        do:
                        - parse:
                            attr: href
                        - space_dedupe
                        - trim
                        - if:
                            match: \w+
                            do:
                            - normalize:
                                routine: url
                            - object_field_set:
                                object: product
                                joinby: "|"
                                field: images
                    - find:
                        path: div.product-thumbnails>ul>li>a
                        do:
                        - parse:
                            attr: href
                        - space_dedupe
                        - trim
                        - if:
                            match: \w+
                            do:
                            - normalize:
                                routine: url
                            - object_field_set:
                                object: product
                                joinby: "|"
                                field: images
        - find:
            in: doc
            path: meta[name="description"]
            do:
            - parse:
                attr: content
            - space_dedupe
            - trim
            - object_field_set:
                object: product
                field: description
        - find:
            path: div.product-price
            do:
            - find:
                path: span.price-list
                do:
                - parse:
                    filter:
                    - \$([0-9\.\,]+)\s*-
                    - \$([0-9\.\,]+)
                - normalize:
                    routine: replace_substring
                    args:
                        \,: ''
                - space_dedupe
                - trim
                - object_field_set:
                    object: product
                    type: float
                    field: price
                - parse
                - normalize:
                    routine: replace_matched
                    args:
                        \$: USD
                - object_field_set:
                    object: product
                    field: currency
            - find:
                path: span.price-sales
                do:
                - parse:
                    filter:
                    - \$([0-9\.\,]+)\s*-
                    - \$([0-9\.\,]+)
                - normalize:
                    routine: replace_substring
                    args:
                        \,: ''
                - space_dedupe
                - trim
                - if:
                    match: \d+
                    do:
                    - object_field_set:
                        object: product
                        type: float
                        field: price
                - parse
                - if:
                    match: \d+
                    do:
                    - normalize:
                        routine: replace_matched
                        args:
                            \$: USD
                    - object_field_set:
                        object: product
                        field: currency
        - walk:
            to: http://photorankapi-a.akamaihd.net/customers/217092/streams/search?auth_token=520af2a204fdc2fffc0c3f3442844cdcd20646a1bd3af131247f5aaa3fe8c827&wrap_responses=1&version=v2.2&tag_key=<%pid%>
            do:
            - find:
                path: data>safe__analytics>oid
                do:
                - parse:
                    filter: (\d+)
                - variable_set: olapic_id
                - walk:
                    to: http://photorankapi-a.akamaihd.net/streams/<%olapic_id%>/media/recent?auth_token=520af2a204fdc2fffc0c3f3442844cdcd20646a1bd3af131247f5aaa3fe8c827&version=v2.2&wrap_responses=1&count=300
                    do:
                    - find:
                        path: data>safe__embedded>media>images
                        do:
                        - find:
                            path: original
                            do:
                            - parse
                            - object_field_set:
                                object: product
                                joinby: "|"
                                field: images
        - object_save:
            name: product
