---
config:
    debug: 2
    agent: Firefox
do:
- pool_clear: pages
- pool_clear: catalog
- link_add:
    pool: catalog
    url: http://api.hm.com/v2/us/en/products/display?page=1&categories=ladies&concealCategories=true&pageSize=500&deviceType=DESKTOP
- walk:
    to: links
    pool: catalog
    do:
    - sleep: 3
    - find:
        path: pagination
        do:
        - find:
            path: count
            do:
            - parse
            - variable_set: count
        - find:
            path: page
            do:
            - parse
            - variable_set: page
        - find:
            path: pagesize
            do:
            - parse
            - variable_set: pagesize
        - eval:
            routine: js
            body: '(function (){var last = (parseInt("<%page%>") - 1) * parseInt("<%pagesize%>") + parseInt("<%pagesize%>"); if (last < parseInt("<%count%>")) { return parseInt("<%page%>") + 1; } else { return ""; }})();'
        - if:
            match: \d+
            do:
            - variable_set: next
            - link_add:
                pool: catalog
                url: http://api.hm.com/v2/us/en/products/display?page=<%next%>&categories=ladies&concealCategories=true&pageSize=500&deviceType=DESKTOP
    - find:
        path: displayArticles>webUrl
        do:
        - parse:
            filter: ^([^\?]+)\?
        - link_add:
            pool: pages
- pool_clear: catalog
- link_add:
    pool: catalog
    url: http://api.hm.com/v2/us/en/products/display?page=1&categories=men&concealCategories=true&pageSize=500&deviceType=DESKTOP
- walk:
    to: links
    pool: catalog
    do:
    - sleep: 3
    - find:
        path: pagination
        do:
        - find:
            path: count
            do:
            - parse
            - variable_set: count
        - find:
            path: page
            do:
            - parse
            - variable_set: page
        - find:
            path: pagesize
            do:
            - parse
            - variable_set: pagesize
        - eval:
            routine: js
            body: '(function (){var last = (parseInt("<%page%>") - 1) * parseInt("<%pagesize%>") + parseInt("<%pagesize%>"); if (last < parseInt("<%count%>")) { return parseInt("<%page%>") + 1; } else { return ""; }})();'
        - if:
            match: \d+
            do:
            - variable_set: next
            - link_add:
                pool: catalog
                url: http://api.hm.com/v2/us/en/products/display?page=<%next%>&categories=men&concealCategories=true&pageSize=500&deviceType=DESKTOP
    - find:
        path: displayArticles>webUrl
        do:
        - parse:
            filter: ^([^\?]+)\?
        - link_add:
            pool: pages
- pool_clear: catalog
- link_add:
    pool: catalog
    url: http://api.hm.com/v2/us/en/products/display?page=1&categories=kids&concealCategories=true&pageSize=500&deviceType=DESKTOP
- walk:
    to: links
    pool: catalog
    do:
    - sleep: 3
    - find:
        path: pagination
        do:
        - find:
            path: count
            do:
            - parse
            - variable_set: count
        - find:
            path: page
            do:
            - parse
            - variable_set: page
        - find:
            path: pagesize
            do:
            - parse
            - variable_set: pagesize
        - eval:
            routine: js
            body: '(function (){var last = (parseInt("<%page%>") - 1) * parseInt("<%pagesize%>") + parseInt("<%pagesize%>"); if (last < parseInt("<%count%>")) { return parseInt("<%page%>") + 1; } else { return ""; }})();'
        - if:
            match: \d+
            do:
            - variable_set: next
            - link_add:
                pool: catalog
                url: http://api.hm.com/v2/us/en/products/display?page=<%next%>&categories=kids&concealCategories=true&pageSize=500&deviceType=DESKTOP
    - find:
        path: displayArticles>webUrl
        do:
        - parse:
            filter: ^([^\?]+)\?
        - link_add:
            pool: pages
- pool_clear: catalog
- link_add:
    pool: catalog
    url: http://api.hm.com/v2/us/en/products/display?page=1&categories=home&concealCategories=true&pageSize=500&deviceType=DESKTOP
- walk:
    to: links
    pool: catalog
    do:
    - sleep: 3
    - find:
        path: pagination
        do:
        - find:
            path: count
            do:
            - parse
            - variable_set: count
        - find:
            path: page
            do:
            - parse
            - variable_set: page
        - find:
            path: pagesize
            do:
            - parse
            - variable_set: pagesize
        - eval:
            routine: js
            body: '(function (){var last = (parseInt("<%page%>") - 1) * parseInt("<%pagesize%>") + parseInt("<%pagesize%>"); if (last < parseInt("<%count%>")) { return parseInt("<%page%>") + 1; } else { return ""; }})();'
        - if:
            match: \d+
            do:
            - variable_set: next
            - link_add:
                pool: catalog
                url: http://api.hm.com/v2/us/en/products/display?page=<%next%>&categories=home&concealCategories=true&pageSize=500&deviceType=DESKTOP
    - find:
        path: displayArticles>webUrl
        do:
        - parse:
            filter: ^([^\?]+)\?
        - link_add:
            pool: pages
- pool_clear: catalog
- link_add:
    pool: catalog
    url: http://api.hm.com/v2/us/en/products/display?page=1&categories=sale%2Fmen&concealCategories=true&pageSize=500&deviceType=DESKTOP
- walk:
    to: links
    pool: catalog
    do:
    - sleep: 3
    - find:
        path: pagination
        do:
        - find:
            path: count
            do:
            - parse
            - variable_set: count
        - find:
            path: page
            do:
            - parse
            - variable_set: page
        - find:
            path: pagesize
            do:
            - parse
            - variable_set: pagesize
        - eval:
            routine: js
            body: '(function (){var last = (parseInt("<%page%>") - 1) * parseInt("<%pagesize%>") + parseInt("<%pagesize%>"); if (last < parseInt("<%count%>")) { return parseInt("<%page%>") + 1; } else { return ""; }})();'
        - if:
            match: \d+
            do:
            - variable_set: next
            - link_add:
                pool: catalog
                url: http://api.hm.com/v2/us/en/products/display?page=<%next%>&categories=sale%2Fmen&concealCategories=true&pageSize=500&deviceType=DESKTOP
    - find:
        path: displayArticles>webUrl
        do:
        - parse:
            filter: ^([^\?]+)\?
        - link_add:
            pool: pages
- pool_clear: catalog
- link_add:
    pool: catalog
    url: http://api.hm.com/v2/us/en/products/display?page=1&categories=sale%2Fladies&concealCategories=true&pageSize=500&deviceType=DESKTOP
- walk:
    to: links
    pool: catalog
    do:
    - sleep: 3
    - find:
        path: pagination
        do:
        - find:
            path: count
            do:
            - parse
            - variable_set: count
        - find:
            path: page
            do:
            - parse
            - variable_set: page
        - find:
            path: pagesize
            do:
            - parse
            - variable_set: pagesize
        - eval:
            routine: js
            body: '(function (){var last = (parseInt("<%page%>") - 1) * parseInt("<%pagesize%>") + parseInt("<%pagesize%>"); if (last < parseInt("<%count%>")) { return parseInt("<%page%>") + 1; } else { return ""; }})();'
        - if:
            match: \d+
            do:
            - variable_set: next
            - link_add:
                pool: catalog
                url: http://api.hm.com/v2/us/en/products/display?page=<%next%>&categories=sale%2Fladies&concealCategories=true&pageSize=500&deviceType=DESKTOP
    - find:
        path: displayArticles>webUrl
        do:
        - parse:
            filter: ^([^\?]+)\?
        - link_add:
            pool: pages
- pool_clear: catalog
- link_add:
    pool: catalog
    url: http://api.hm.com/v2/us/en/products/display?page=1&categories=sale%2Fkids&concealCategories=true&pageSize=500&deviceType=DESKTOP
- walk:
    to: links
    pool: catalog
    do:
    - sleep: 3
    - find:
        path: pagination
        do:
        - find:
            path: count
            do:
            - parse
            - variable_set: count
        - find:
            path: page
            do:
            - parse
            - variable_set: page
        - find:
            path: pagesize
            do:
            - parse
            - variable_set: pagesize
        - eval:
            routine: js
            body: '(function (){var last = (parseInt("<%page%>") - 1) * parseInt("<%pagesize%>") + parseInt("<%pagesize%>"); if (last < parseInt("<%count%>")) { return parseInt("<%page%>") + 1; } else { return ""; }})();'
        - if:
            match: \d+
            do:
            - variable_set: next
            - link_add:
                pool: catalog
                url: http://api.hm.com/v2/us/en/products/display?page=<%next%>&categories=sale%2Fkids&concealCategories=true&pageSize=500&deviceType=DESKTOP
    - find:
        path: displayArticles>webUrl
        do:
        - parse:
            filter: ^([^\?]+)\?
        - link_add:
            pool: pages
- pool_clear: catalog
- link_add:
    pool: catalog
    url: http://api.hm.com/v2/us/en/products/display?page=1&categories=sale%2Fhome&concealCategories=true&pageSize=500&deviceType=DESKTOP
- walk:
    to: links
    pool: catalog
    do:
    - sleep: 3
    - find:
        path: pagination
        do:
        - find:
            path: count
            do:
            - parse
            - variable_set: count
        - find:
            path: page
            do:
            - parse
            - variable_set: page
        - find:
            path: pagesize
            do:
            - parse
            - variable_set: pagesize
        - eval:
            routine: js
            body: '(function (){var last = (parseInt("<%page%>") - 1) * parseInt("<%pagesize%>") + parseInt("<%pagesize%>"); if (last < parseInt("<%count%>")) { return parseInt("<%page%>") + 1; } else { return ""; }})();'
        - if:
            match: \d+
            do:
            - variable_set: next
            - link_add:
                pool: catalog
                url: http://api.hm.com/v2/us/en/products/display?page=<%next%>&categories=sale%2Fhome&concealCategories=true&pageSize=500&deviceType=DESKTOP
    - find:
        path: displayArticles>webUrl
        do:
        - parse:
            filter: ^([^\?]+)\?
        - link_add:
            pool: pages
- walk:
    to: links
    pool: pages
    do:
    - sleep: 3
    - find:
        path: 'div#content'
        do:
        - variable_clear: desc
        - object_new: product
        - eval:
            routine: js
            body: '(function (){var d = new Date(); return d.toISOString()})();'
        - object_field_set:
            object: product
            field: date
        - static_get: url
        - object_field_set:
            object: product
            field: url
        - find:
            path: 'span#text-price>span.actual-price'
            do:
            - parse:
                filter: ([0-9\.]+)
            - object_field_set:
                object: product
                type: float
                field: price
            - parse
            - normalize:
                routine: replace_matched
                args:
                    \$: USD
            - object_field_set:
                object: product
                field: currency
        - find:
            in: doc
            path: script:contains('hm.data.product =')
            do:
            - parse:
                filter: hm\.data\.breadcrumbs\s+\=\s+(.+)
            - normalize:
                routine: replace_substring
                args:
                - ^\s+|\s+$: ''
                - ;$: ''
            - normalize:
                routine: json2xml
            - to_block
            - find:
                path: element
                slice: 0:-2
                do:
                - find:
                    path: label
                    do:
                    - parse
                    - if:
                        match: \w+
                        do:
                        - object_field_set:
                            object: product
                            joinby: "|"
                            field: attributes
        - find:
            in: doc
            path: script:contains('hm.data.product =')
            do:
            - parse:
                filter: hm\.data\.product\s+\=\s+(.+)
            - normalize:
                routine: replace_substring
                args:
                - ^\s+|\s+$: ''
                - ;$: ''
            - normalize:
                routine: json2xml
            - to_block
            - find:
                path: body_safe>name
                do:
                - parse
                - object_field_set:
                    object: product
                    field: name
            - find:
                path: body_safe>description
                do:
                - parse
                - normalize:
                    routine: replace_substring
                    args:
                        - \s+: ' '
                        - ^\s+|\s+$: ''
                - if:
                    match: \w+
                    do:
                    - object_field_set:
                        object: product
                        field: description
            - find:
                path: body_safe>code
                do:
                - parse
                - variable_set: code
                - object_field_set:
                    object: product
                    field: sku
            - find:
                path: body_safe>codes
                do:
                - parse
                - normalize:
                    routine: lower
                - variable_set: sku
                - find:
                    in: doc
                    path: script:contains('hm.data.product =')
                    do:
                    - parse:
                        filter: hm\.data\.product\s+\=\s+(.+)
                    - normalize:
                        routine: replace_substring
                        args:
                        - ^\s+|\s+$: ''
                        - ;$: ''
                    - normalize:
                        routine: json2xml
                    - to_block
                    - find:
                        path: body_safe>articles>safe_<%sku%>
                        do:
                        - find:
                            path: description
                            slice: 0
                            do:
                            - parse
                            - if:
                                match: \w+
                                do:
                                - object_field_set:
                                    object: product
                                    joinby: "|"
                                    field: variations
                        - find:
                            path: images>zoomareaparams
                            do:
                            - parse
                            - normalize:
                                routine: replace_substring
                                args:
                                    \s: '%20'
                            - variable_set: source
                            - register_set: "http://lp.hm.com/hmprod?set=<%source%>&call=url[file:/product/full]"
                            - object_field_set:
                                object: product
                                joinby: "|"
                                field: images
        - register_set: "H&M"
        - object_field_set:
            object: product
            field: brand
        - object_save:
            name: product
