---
config:
    debug: 2
    agent: Firefox
do:
- walk:
    to: https://www.happysocks.com
    do:
    - find: 
        path: '#menu-desktop .level0' 
        do: 
        - find: 
            path: a 
            slice: 0
            do: 
            - parse
            - space_dedupe
            - trim
            - normalize:
                routine: lower
            - variable_set: cat1
        - find: 
            path: li.level1 > a 
            do: 
            - parse
            - space_dedupe
            - trim
            - normalize:
                routine: lower
            - variable_set: cat2
            - parse:
                attr: href
            - normalize:
                routine: url
            - pool_clear: main
            - link_add:
                pool: main
            - walk:
                to: links
                pool: main
                do:
                - find: 
                    path: .i-next 
                    do: 
                    - parse:
                        attr: href
                    - normalize:
                        routine: url
                    - link_add:
                        pool: main
                - find: 
                    path: .product-image 
                    do: 
                    - parse:
                        attr: href
                    - normalize:
                        routine: url
                    - walk:
                        to: value
                        do:
                        - object_new: product
                        - find: 
                            in: doc
                            path: head 
                            do: 
                            - variable_get: cat1
                            - object_field_set:
                                object: product
                                field: categories
                                joinby: "|"
                            - variable_get: cat2
                            - object_field_set:
                                object: product
                                field: categories
                                joinby: "|"
                            - eval:
                                routine: js
                                body: '(function (){var d = new Date(); return d.toISOString()})();'
                            - object_field_set:
                                object: product
                                field: date
                            - static_get: url
                            - object_field_set:
                                object: product
                                field: url
                        - find: 
                            path: .swiper-slide
                            do: 
                            - parse:
                                attr: style
                                filter: background\:url\(([^\)]+)
                            - if:
                                match: \w+
                                do:
                                - object_field_set:
                                    object: product
                                    field: images
                                    joinby: "|"
                            - find: 
                                path: .product-img
                                do: 
                                - parse:
                                    attr: data-src
                                - if:
                                    match: \w+
                                    do:
                                    - object_field_set:
                                        object: product
                                        field: images
                                        joinby: "|"
                        - find: 
                            path: script:matches(var\s*dataLayer) 
                            do: 
                            - parse:
                                filter: 
                                    - dataLayer\.push\((.+)\);
                                    - var\s*dataLayer\s*\=\s*(.+)
                            - normalize:
                                routine: json2xml
                            - to_block
                            - find: 
                                path: productPrice
                                do: 
                                - parse
                                - if:
                                    match: (\d)
                                    do:
                                    - object_field_set:
                                        object: product
                                        field: price
                                        type: float
                                    - register_set: USD
                                    - object_field_set:
                                        object: product
                                        field: currency
                        - find: 
                            path: .product-name 
                            do: 
                            - parse
                            - space_dedupe
                            - trim
                            - object_field_set:
                                object: product
                                field: name
                            - register_set: Happy Socks
                            - object_field_set:
                                object: product
                                field: brand
                        - find: 
                            path: .details > p 
                            do: 
                            - parse
                            - space_dedupe
                            - trim
                            - object_field_set:
                                object: product
                                field: description
                        - find: 
                            path: .attributes 
                            do: 
                            - find: 
                                path: .attr:has(h5:matches(SKU)) > p
                                slice: 0
                                do: 
                                - parse
                                - space_dedupe
                                - trim
                                - object_field_set:
                                    object: product
                                    field: sku
                        - object_save:
                            name: product
