---
config:
    debug: 2
    agent: Firefox
do:
- walk:
    to: https://www.covergirl.com/beauty-products
    do:
    - find:
        path: ul.global-header__list>li:not(.country-selector) ul.global-header__dropdown-list
        do:
        - find:
            path: li>a
            do:
            - parse:
                attr: href
            - space_dedupe
            - trim
            - walk:
                to: value
                do:
                - find:
                    path: a.card__product-link
                    do:
                    - parse:
                        attr: href
                    - space_dedupe
                    - trim
                    - if:
                        match: \w+
                        do:
                        - normalize:
                            routine: url
                        - link_add:
                            pool: pages

- walk:
    to: links
    pool: pages
    do:
    - find:
        path: main
        do:
        - object_new: product
        - eval:
            routine: js
            body: '(function (){var d = new Date(); return d.toISOString()})();'
        - object_field_set:
            object: product
            field: date
        - static_get: url
        - object_field_set:
            object: product
            field: url
        - find:
            path: h1.product__name
            slice: 0
            do:
            - parse
            - space_dedupe
            - trim
            - object_field_set:
                object: product
                field: name
        - register_set: CoverGirl
        - object_field_set:
            object: product
            field: brand
        - find:
            path: div.product__description
            slice: 0
            do:
            - parse
            - space_dedupe
            - trim
            - object_field_set:
                object: product
                field: description
        - find:
            path: li.breadcrumbs__item>a
            do:
            - parse
            - space_dedupe
            - trim
            - if:
                match: \w+
                do:
                - object_field_set:
                    object: product
                    joinby: "|"
                    field: categories
        - find:
            path: 'select#product-filter-dropdown>option.select-control__option'
            do:
            - parse
            - space_dedupe
            - trim
            - if:
                match: \w+
                do:
                - object_field_set:
                    object: product
                    joinby: "|"
                    field: variations
        - find:
            path: li.retailers__item>div.justify-content-end
            slice: 0
            do:
            - parse:
                filter: ([0-9\.]+)\s*\$
            - object_field_set:
                object: product
                field: price
                type: float
            - parse
            - normalize:
                routine: replace_matched
                args:
                    \$: USD
            - object_field_set:
                object: product
                field: currency
        - find:
            in: doc
            path: script:contains('window.product=')
            do:
            - parse
            - normalize:
                routine: replace_substring
                args:
                    ^window\.: ''
            - variable_set: js
            - eval:
                routine: js
                body: '(function (){<%js%>; return JSON.stringify(product);})();'
            - normalize:
                routine: json2xml
            - to_block
            - node_remove: retailers
            - find:
                path: selectedsku
                do:
                - parse
                - space_dedupe
                - trim
                - if:
                    match: \d+
                    do:
                    - object_field_set:
                        object: product
                        field: sku
            - find:
                path: mainimages>safe_source
                do:
                - parse
                - space_dedupe
                - trim
                - if:
                    match: \w+
                    do:
                    - object_field_set:
                        object: product
                        joinby: "|"
                        field: images
        - object_save:
            name: product
