---
config:
    debug: 2
    agent: Firefox
do:
- walk:
    to: https://dwell.co.uk/
    do:
    - find: 
        path: 'li:hasChild(a#amenu)' 
        do: 
        - find: 
            path: a
            slice: 0
            do: 
            - parse
            - space_dedupe
            - trim
            - normalize:
                routine: lower
            - variable_set: cat1
        - find: 
            path: div > a
            do: 
            - parse
            - space_dedupe
            - trim
            - normalize:
                routine: lower
            - variable_set: cat2
            - parse:
                attr: href
            - normalize:
                routine: url
            - walk:
                to: value
                do:
                
                - find: 
                    path: .product 
                    do: 
                    - parse:
                        attr: onclick
                        filter:
                            - (\d+)
                    - register_set: https://dwell.co.uk/<%register%>
                    - walk:
                        to: value
                        do:
                        - cookie_reset
                        - object_new: product
                        - find: 
                            in: doc
                            path: head 
                            do: 
                            - eval:
                                routine: js
                                body: '(function (){var d = new Date(); return d.toISOString()})();'
                            - object_field_set:
                                object: product
                                field: date
                            - static_get: url
                            - object_field_set:
                                object: product
                                field: url
                            - variable_get: cat1
                            - object_field_set:
                                object: product
                                field: categories
                                joinby: "|"
                            - variable_get: cat2
                            - object_field_set:
                                object: product
                                field: categories
                                joinby: "|"
                            - register_set: DWELL
                            - object_field_set:
                                object: product
                                field: brand
                        - find: 
                            path: .abc 
                            do: 
                            - parse:
                                attr: id
                                filter:
                                    - (http.+)
                            - if:
                                match: (\S)
                                do:
                                - object_field_set:
                                    object: product
                                    field: images
                                    joinby: "|"
                        - find: 
                            path: .jqzoom 
                            do: 
                            - parse:
                                attr: href
                            - if:
                                match: (\S)
                                do:
                                - object_field_set:
                                    object: product
                                    field: images
                                    joinby: "|"
                        - find: 
                            path: .zoomThumbActive a
                            do: 
                            - parse:
                                attr: rel
                            - if:
                                match: (^\s*\{)
                                do:
                                - eval:
                                    routine: js
                                    body: (function () {var e = <%register%>; return JSON.stringify(e);})();
                                - normalize:
                                    routine: json2xml
                                - to_block
                                - find: 
                                    path: largeimage 
                                    do: 
                                    - parse
                                    - if:
                                        match: (\S)
                                        do:
                                        - object_field_set:
                                            object: product
                                            field: images
                                            unique: yes
                        - find: 
                            path: '[name="product"]'
                            slice: 0
                            do: 
                            - parse:
                                attr: value
                            - space_dedupe
                            - trim
                            - object_field_set:
                                object: product
                                field: sku
                        - find: 
                            path: .prod_block2 
                            slice: 0
                            do: 
                            - parse
                            - space_dedupe
                            - trim
                            - object_field_set:
                                object: product
                                field: description
                        - find: 
                            path: '[itemprop="name"]' 
                            do: 
                            - parse
                            - space_dedupe
                            - trim
                            - object_field_set:
                                object: product
                                field: name
                        - find: 
                            path: '[itemprop="price"]' 
                            do: 
                            - parse:
                                filter:
                                    - (\d+\.?\d*)
                            - if:
                                match: (\d+)
                                do:
                                - object_field_set:
                                    object: product
                                    field: price
                                    type: float
                                - register_set: GBP
                                - object_field_set:
                                    object: product
                                    field: currency
                        - find: 
                            path: '#productPageotherColoursItemsStaticBar .productPageMarqueeBoxProductDescription' 
                            do: 
                            - node_remove: strong
                            - parse
                            - normalize:
                                routine: replace_substring
                                args:
                                    £: ''
                            - space_dedupe
                            - trim
                            - if:
                                match: (\S)
                                do:
                                - object_field_set:
                                    object: product
                                    field: variations
                                    joinby: "|"
                        - object_save:
                            name: product
