---
config:
    debug: 2
    agent: Firefox
do:
- walk:
    to: http://www.desigual.com/en_US
    do:
    - find:
        path: .menu-desktop a
        do:
        - parse:
            attr: href
        - if:
            match: (highlights|collections)
            else:
            - normalize:
                routine: url
            - link_add:
                pool: main
- walk:
    to: links
    pool: main
    do:
    - sleep: 5
    - find:
        path: noscript:matches(load-more-btn-holder) 
        do:
        - parse
        - to_block
        - find:
            path: a
            do:
            - parse: 
                attr: href
            - normalize:
                routine: url
            - link_add:
                pool: main
    
    - find:
        path: .grid-product-item > a 
        do:
        - parse: 
            attr: href
        - normalize:
            routine: url
        - link_add:
            pool: sub
- walk:
    to: links
    pool: sub
    do:
    - find:
        path: body[b2c-is-error-page="false"]
        do:
        - find:
            in: doc
            path: html
            do:
            - sleep: 5
            - variable_clear: colorid
            - variable_clear: productid
            - variable_clear: sdescr
            - object_new: product
            - find:
                path: head
                do:
                - eval:
                    routine: js
                    body: '(function (){var d = new Date(); return d.toISOString()})();'
                - object_field_set:
                    object: product
                    field: date
                - static_get: url
                - object_field_set:
                    object: product
                    field: url
                - register_set: 'Desigual'
                - object_field_set:
                    object: product
                    field: brand
                - find:
                    path: meta[name="description"]
                    do:
                    - parse
                    - space_dedupe
                    - trim
                    - if:
                        match: (\S)
                        do:
                        - object_field_set:
                            object: product
                            field: description
            - find: 
                path: .breadcrumb a
                slice: 2:-1
                do: 
                - parse
                - space_dedupe
                - trim
                - if:
                    match: (\S)
                    do:
                    - object_field_set:
                        object: product
                        field: categories
                        joinby: "|"
            - find:
                path: .product-name
                do:
                - parse
                - space_dedupe
                - trim
                - if:
                    match: (\S)
                    do:
                    - object_field_set:
                        object: product
                        field: name
            - find: 
                path: .product-price
                do: 
                - parse:
                    filter:
                        - (\d+\.?\d*)
                - if:
                    match: (\d)
                    do:
                    - object_field_set:
                        object: product
                        field: price
                        type: float
                    - register_set: USD
                    - object_field_set:
                        object: product
                        field: currency
            - find:
                path: script:matches(pdp.productDetail)
                do:
                - parse:
                    filter:
                        - pdp.productDetail\s*=\s*(\{.+\})
                - normalize:
                    routine: json2xml
                - to_block
                - find: 
                    path: body_safe > compositions > description 
                    do: 
                    - parse
                    - space_dedupe
                    - trim
                    - if:
                        match: (\S)
                        do:
                        - object_field_set:
                            object: product
                            field: description
                        
                        
                - find: 
                    path: body_safe > productid 
                    do: 
                    - parse
                    - variable_set: productid
                    - object_field_set:
                        object: product
                        field: sku
                - find:
                    path: items > colorid
                    do:
                    - parse
                    - variable_set: colorid
                    - register_set: http://www.desigual.com/api/v2/amplience/pdp/<%productid%><%colorid%>?colorId=<%colorid%>&productId=<%productid%>&locale=en_US&storeId=store_us_web
                    - walk:
                        to: value
                        do:
                        - variable_clear: h
                        - variable_clear: w
                        - variable_clear: iu
                        - find:
                            path: safe_image
                            do:
                            - find:
                                path: height
                                do: 
                                - parse
                                - variable_set: h
                            - find:
                                path: width
                                do:
                                - parse
                                - variable_set: w
                            - find:
                                path: url
                                do:
                                - parse
                                - variable_set: iu
                                - register_set: <%iu%>?w=<%w%>&h=<%h%>
                                - object_field_set:
                                    object: product
                                    field: images
                                    joinby: "|"
                - find: 
                    path: colorname 
                    do: 
                    - parse
                    - space_dedupe
                    - trim
                    - if:
                        match: (\S)
                        do:
                        - object_field_set:
                            object: product
                            field: variations
                            joinby: "|"
                - find: 
                    path: compositions > description
                    do: 
                    - parse
                    - space_dedupe
                    - trim
                    - if:
                        match: (\S)
                        do:
                        - variable_set: sdescr
                        - object_field_set:
                            object: product
                            field: description
            - object_save:
                name: product
