#vkusvillru digger
---
config:
    debug: 2
    agent: Firefox
do:
- variable_set: 
    field: crep
    value: "yes"
- counter_set: 
    name: catc
    value: 0
- walk:
    to: links
    repeat_in_pool: <%crep%>
    do:
    - cookie_reset
    - variable_clear: pageOk
    - variable_clear: crep
    - counter_increment:
        name: catc
    - find: 
        path: a:hasChild(.VV_Pager--btn-desk)
        do: 
        - parse:
            attr: href
        - if:
            match: \S
            do:
            - normalize:
                routine: url
            - link_add
    - find: 
        path: .ProductCard .ProductCard__link
        do: 
        - variable_set: 
            field: pageOk
            value: 1
        - parse:
            attr: href
        - if:
            match: \S
            do:
            - normalize:
                routine: url
            - link_add:
                pool: catalog
    - find: 
        path: body 
        do: 
        - variable_get: pageOk
        - if:
            match: \S
            else:
            - counter_get: catc
            - if:
                gt: 4
                type: int
                do:
                - variable_clear: crep
                - counter_reset: catc
                - proxy_switch
                - info: cannot fetch url after 5 retries, skipping
                else:
                - variable_set: 
                    field: crep
                    value: "yes"
- variable_set: 
    field: crep
    value: "yes"
- counter_set: 
    name: catc
    value: 0
- walk:
    to: links
    repeat_in_pool: <%crep%>
    pool: catalog
    do:
    - cookie_reset
    - variable_clear: pageOk
    - variable_clear: crep
    - counter_increment:
        name: catc
    - find: 
        path: body 
        do:
        - find: 
            path: h1.Product__title 
            do: 
            - variable_set:
                field: pageOk
                value: 1
            - find: 
                path: body
                in: doc
                do: 
                - object_new: item
                - static_get: url
                - object_field_set:
                    object: item
                    field: url
                - register_set: "yes"
                - object_field_set:
                    object: item
                    field: instock
                - find: 
                    path: h1.Product__title 
                    do: 
                    - parse
                    - space_dedupe
                    - trim
                    - if:
                        match: \S
                        do:
                        - object_field_set:
                            object: item
                            field: title
                - find: 
                    path: 'meta[itemprop="brand"]' 
                    do: 
                    - parse:
                        attr: content
                    - if:
                        match: \S
                        do:
                        - object_field_set:
                            object: item
                            field: brand
                - find: 
                    path: .Breadcrumbs__link > a
                    slice: 2:-1
                    do: 
                    - parse
                    - space_dedupe
                    - trim
                    - if:
                        match: \S
                        do:
                        - object_field_set:
                            object: item
                            field: categories
                            joinby: ","
                - find: 
                    path: 'div[itemprop="ratingValue"]' 
                    do: 
                    - parse
                    - space_dedupe
                    - trim
                    - if:
                        match: \d
                        do:
                        - object_field_set:
                            object: item
                            field: rating
                - find: 
                    path: 'div[itemprop="reviewCount"]'
                    do: 
                    - parse
                    - space_dedupe
                    - trim
                    - if:
                        match: \d
                        do:
                        - object_field_set:
                            object: item
                            field: total_reviews
                - find: 
                    path: .Price__value 
                    do: 
                    - parse
                    - space_dedupe
                    - trim
                    - if:
                        match: \d
                        do:
                        - object_field_set:
                            object: item
                            field: price
                - find: 
                    path: .Product__desc 
                    do: 
                    - node_remove: script, style
                    - parse
                    - space_dedupe
                    - trim
                    - if:
                        match: \S
                        do:
                        - object_field_set:
                            object: item
                            field: description
                - find: 
                    path: .ProductGallery__image > a > img
                    slice: 0
                    do: 
                    - parse:
                        attr: data-src
                        filter: 
                            - ^([^\?]+)
                    - if:
                        match: \S
                        do:
                        - normalize:
                            routine: url
                        - object_field_set:
                            object: item
                            field: image
                - find: 
                    path: .js-product-cart 
                    do: 
                    - parse:
                        attr: data-xmlid
                    - if:
                        match: \d
                        do:
                        - object_field_set:
                            object: item
                            field: sku
                        
                - object_save:
                    name: item
    - find: 
        path: body 
        do: 
        - variable_get: pageOk
        - if:
            match: \S
            else:
            - counter_get: catc
            - if:
                gt: 4
                type: int
                do:
                - variable_clear: crep
                - counter_reset: catc
                - proxy_switch
                - info: cannot fetch url after 5 retries, skipping
                else:
                - variable_set: 
                    field: crep
                    value: "yes"