---
config:
    debug: 2
    agent: Chrome
do:
- walk:
    to: https://www.hermanmiller.com/global/en_eur
    do:
    - find: 
        path: 'ul#navGlobal>li'
        slice: 0
        do: 
        - find: 
            path: div.dropdown>div.col
            slice: 0
            do: 
            - find: 
                path: a
                slice: 1:-2
                do: 
                - parse:
                    attr: href
                - space_dedupe
                - trim
                - if:
                    match: \w+
                    do:
                    - normalize:
                        routine: url
                    - link_add:
                        pool: catalog
- walk:
    to: links
    pool: catalog
    do:
    - find:
        path: ul.productGrid>li>a
        do:
        - parse:
            attr: href
        - space_dedupe
        - trim
        - if:
            match: \w+
            do:
            - normalize:
                routine: url
            - link_add:
                pool: pages
- walk:
    to: links
    pool: pages
    do:
    - sleep: 2
    - find:
        path: body.basepage
        do:
        - variable_clear: desc
        - variable_clear: pid
        - variable_clear: cid
        - object_new: product
        - eval:
            routine: js
            body: '(function (){var d = new Date(); return d.toISOString()})();'
        - object_field_set:
            object: product
            field: date
        - static_get: url
        - object_field_set:
            object: product
            field: url
        - find:
            path: 'div#insetBlock>h1'
            do:
            - parse
            - space_dedupe
            - trim
            - object_field_set:
                object: product
                field: name
        - register_set: Herman Miller
        - object_field_set:
            object: product
            field: brand
        - find:
            in: doc
            path: meta[name="description"]
            do:
            - parse:
                attr: content
            - space_dedupe
            - trim
            - object_field_set:
                object: product
                field: description
        - find:
            path: div.productHero>div.slide>img
            do:
            - parse:
                attr: src
            - space_dedupe
            - trim
            - if:
                match: \w+
                do:
                - normalize:
                    routine: url
                - object_field_set:
                    object: product
                    joinby: "|"
                    field: images
        - find:
            path: div.module:contains('Photo Gallery') a>img
            do:
            - parse:
                attr: src
            - space_dedupe
            - trim
            - if:
                match: \w+
                do:
                - normalize:
                    routine: url
                - normalize:
                    routine: replace_substring
                    args:
                        \/_jcr_content.+$: ''
                - object_field_set:
                    object: product
                    joinby: "|"
                    field: images
        - find:
            in: doc
            path: 'div#breadcrumb>a'
            slice: 1:-1
            do:
            - parse
            - space_dedupe
            - trim
            - if:
                match: \w+
                do:
                - object_field_set:
                    object: product
                    joinby: "|"
                    field: categories
        - object_save:
            name: product
