---
config:
    debug: 2
    agent: Firefox
do:
- link_add:
    pool: beauty
    url:
    - https://www.chanel.com/en_US/fragrance-beauty/fragrance-beauty-skincare-140910
- walk:
    to: links
    pool: beauty
    do:
    - find:
        path: a.product-link
        do:
        - parse:
            attr: href
        - if:
            match: \w+
            do:
            - normalize:
                routine: url
            - link_add:
                pool: beauty
    - find:
        path: a:haschild(div.top_header[role="button"])
        do:
        - parse:
            attr: href
        - if:
            match: \w+
            do:
            - normalize:
                routine: url
            - link_add:
                pool: beauty
    - find:
        path: form.product_container ul.unstyled>li.img>a
        do:
        - parse:
            attr: href
        - if:
            match: \w+
            do:
            - normalize:
                routine: url
            - link_add:
                pool: beautypages
- walk:
    to: links
    pool: beautypages
    do:
    - sleep: 2
    - find:
        path: 'div#contentContainer'
        do:
        - object_new: product
        - eval:
            routine: js
            body: '(function (){var d = new Date(); return d.toISOString()})();'
        - object_field_set:
            object: product
            field: date
        - static_get: url
        - object_field_set:
            object: product
            field: url
        - find:
            path: h1[itemprop="name"]
            do:
            - parse
            - space_dedupe
            - trim
            - if:
                match: \w+
                do:
                - object_field_set:
                    object: product
                    field: name
        - find:
            path: div.cc-sku-selector-dropdown select>option
            slice: 0
            do:
            - parse:
                attr: value
            - space_dedupe
            - trim
            - if:
                match: \w+
                do:
                - object_field_set:
                    object: product
                    field: sku
        - register_set: Chanel
        - object_field_set:
            object: product
            field: brand
        - find:
            path: div.cc-product-options-price
            do:
            - find:
                path: span[itemprop="priceCurrency"]
                do:
                - parse:
                    attr: content
                - space_dedupe
                - trim
                - object_field_set:
                    object: product
                    field: currency
            - find:
                path: span[itemprop="price"]
                do:
                - parse:
                    filter: (\d+\.\d+)
                - space_dedupe
                - trim
                - object_field_set:
                    object: product
                    type: float
                    field: price
        - find:
            path: div.cc-sku-selector-dropdown select>option
            do:
            - parse
            - space_dedupe
            - trim
            - if:
                match: \w{2,}
                do:
                - object_field_set:
                    object: product
                    joinby: "|"
                    field: variations
        - find:
            in: doc
            path: script:contains('window.__CC_STATE__')
            do:
            - parse:
                filter: window\.__CC_STATE__\s*\=\s*(.+)\;
            - normalize:
                routine: json2xml
            - to_block
            - find:
                path: images src
                do:
                - parse
                - if:
                    match: \w+
                    do:
                    - normalize:
                        routine: url
                    - object_field_set:
                        object: product
                        joinby: "|"
                        field: images
            - find:
                path: product>description
                slice: 0
                do:
                - parse
                - to_block
                - find:
                    path: p
                    slice: 1
                    do:
                    - parse
                    - space_dedupe
                    - trim
                    - if:
                        match: \w+
                        do:
                        - object_field_set:
                            object: product
                            field: description
        - find:
            path: span.breadcrumb>a
            do:
            - parse
            - space_dedupe
            - trim
            - if:
                match: \w{2,}
                do:
                - object_field_set:
                    object: product
                    joinby: "|"
                    field: categories
        - object_save:
            name: product
- link_add:
    pool: sun
    url:
    - https://www.chanel.com/en_US/fashion/sunglasses/products/
- walk:
    to: links
    pool: sun
    do:
    - find:
        path: a.ui-pagination-next
        do:
        - parse:
            attr: href
        - if:
            match: \w+
            do:
            - normalize:
                routine: url
            - link_add:
                pool: sun
    - find:
        path: ul.product-list>li
        do:
        - find:
            path: li.item
            slice: 0
            do:
            - find:
                path: a
                do:
                - parse:
                    attr: href
                - if:
                    match: \w+
                    do:
                    - normalize:
                        routine: url
                    - link_add:
                        pool: sunpages
- walk:
    to: links
    pool: sunpages
    do:
    - sleep: 2
    - find:
        path: main[role="main"]
        do:
        - variable_clear: pid
        - object_new: product
        - eval:
            routine: js
            body: '(function (){var d = new Date(); return d.toISOString()})();'
        - object_field_set:
            object: product
            field: date
        - static_get: url
        - object_field_set:
            object: product
            field: url
        - find:
            path: h1.tt-1
            do:
            - parse
            - space_dedupe
            - trim
            - if:
                match: \w+
                do:
                - object_field_set:
                    object: product
                    field: name
        - find:
            path: input[name="pdt-sku"]
            do:
            - parse:
                attr: value
            - space_dedupe
            - trim
            - if:
                match: \w+
                do:
                - variable_set: pid
                - object_field_set:
                    object: product
                    field: sku
        - register_set: Chanel
        - object_field_set:
            object: product
            field: brand
        - find:
            path: span[property="price"]
            do:
            - parse:
                filter: (\d+)
            - object_field_set:
                object: product
                type: float
                field: price
            - parse
            - normalize:
                routine: replace_matched
                args:
                    \$: USD
            - object_field_set:
                object: product
                field: currency
        - find:
            path: select[data-select="pdt-color"]>option
            do:
            - parse
            - space_dedupe
            - trim
            - if:
                match: \w{2,}
                do:
                - object_field_set:
                    object: product
                    joinby: "|"
                    field: variations
        - find:
            in: doc
            path: meta[name="description"]
            do:
            - parse:
                attr: content
            - space_dedupe
            - trim
            - if:
                match: \w+
                do:
                - object_field_set:
                    object: product
                    field: description
        - find:
            path: div.breadcrumb>a
            slice: 1:-2
            do:
            - parse
            - space_dedupe
            - trim
            - if:
                match: \w{2,}
                do:
                - object_field_set:
                    object: product
                    joinby: "|"
                    field: categories
        - walk:
            to: https://www.chanel.com/en_US/fashion/sunglasses/pdpjson/<%pid%>/product
            do:
            - find:
                path: script
                do:
                - parse
                - normalize:
                    routine: replace_substring
                    args:
                        ^window\.: ''
                - to_block
                - parse
                - eval:
                    routine: js
                    body: (function () {var <%register%>; return JSON.stringify(product);})();
                - normalize:
                    routine: json2xml
                - to_block
                - find:
                    path: zoom
                    do:
                    - parse:
                        filter: ^(\S+)
                    - if:
                        match: \w+
                        do:
                        - normalize:
                            routine: url
                        - object_field_set:
                            object: product
                            joinby: "|"
                            field: images
        - object_save:
            name: product
- link_add:
    url:
    - https://www.chanel.com/en_US/watches-jewelry/fine-jewelry/collections
    - https://www.chanel.com/en_US/watches-jewelry/watches/collections
- walk:
    to: links
    do:
    - find:
        path: div.product-item-wrapper>a
        do:
        - parse:
            attr: href
        - register_set: <%register%>?show=All
        - walk:
            to: value
            do:
            - find:
                path: div.product-item-wrapper>a
                do:
                - parse:
                    attr: href
                - if:
                    match: \w+
                    do:
                    - normalize:
                        routine: url
                    - link_add:
                        pool: pages
- walk:
    to: links
    pool: pages
    do:
    - sleep: 2
    - find:
        path: 'main#page-content'
        do:
        - variable_clear: pid
        - object_new: product
        - eval:
            routine: js
            body: '(function (){var d = new Date(); return d.toISOString()})();'
        - object_field_set:
            object: product
            field: date
        - static_get: url
        - object_field_set:
            object: product
            field: url
        - find:
            path: dl>dt:contains("Name:")+dd
            do:
            - parse
            - space_dedupe
            - trim
            - if:
                match: \w+
                do:
                - object_field_set:
                    object: product
                    field: name
        - find:
            path: dl>dt:contains("Reference:")+dd
            do:
            - parse
            - space_dedupe
            - trim
            - if:
                match: \w+
                do:
                - variable_set: pid
                - object_field_set:
                    object: product
                    field: sku
        - register_set: Chanel
        - object_field_set:
            object: product
            field: brand
        - find:
            path: product_price
            do:
            - parse
            - object_field_set:
                object: product
                type: float
                field: price
            - register_set: USD
            - object_field_set:
                object: product
                field: currency
        - find:
            in: doc
            path: meta[name="description"]
            do:
            - parse:
                attr: content
            - space_dedupe
            - trim
            - if:
                match: \w+
                do:
                - object_field_set:
                    object: product
                    field: description
        - find:
            path: 'nav#breadcrumb>ul>li:not(.visually-hidden)>a'
            slice: 1:-1
            do:
            - parse
            - space_dedupe
            - trim
            - if:
                match: \w{2,}
                do:
                - object_field_set:
                    object: product
                    joinby: "|"
                    field: categories
        - find:
            path: div.product-images figure>a
            do:
            - parse:
                attr: href
            - space_dedupe
            - trim
            - if:
                match: \w{2,}
                do:
                - normalize:
                    routine: url
                - object_field_set:
                    object: product
                    joinby: "|"
                    field: images
        - object_save:
            name: product
