---
config:
    debug: 2
    agent: Firefox
do:
- walk:
    to: http://www.esteelauder.com
    do:
    - find: 
        path: .page-navigation .content .field-menu > .menu > .expanded 
        do: 
        - find: 
            path: a.level-1 
            do: 
            - parse
            - space_dedupe
            - trim
            - normalize:
                routine: lower
            - variable_set: cat1
        - find: 
            path: .menu > li
            do: 
            - variable_clear: cat2
            - variable_clear: hassub
            - find: 
                path: h3 
                slice: 0
                do: 
                - parse
                - space_dedupe
                - trim
                - normalize:
                    routine: lower
                - variable_set: cat2
            - find: 
                path: a 
                do: 
                - parse
                - space_dedupe
                - trim
                - normalize:
                    routine: lower
                - variable_set: cat3
                - parse:
                    attr: href
                - normalize:
                    routine: url
                - walk:
                    to: value
                    do:
                    - find: 
                        path: .product_brief__image-container 
                        do: 
                        - parse:
                            attr: href
                        - normalize:
                            routine: url
                        - walk:
                            to: value
                            do:
                            - object_new: product
                            - find: 
                                in: doc
                                path: head 
                                do: 
                                - eval:
                                    routine: js
                                    body: '(function (){var d = new Date(); return d.toISOString()})();'
                                - object_field_set:
                                    object: product
                                    field: date
                                - register_set: Estee Lauder
                                - object_field_set:
                                    object: product
                                    field: brand
                                - static_get: url
                                - object_field_set:
                                    object: product
                                    field: url
                                - variable_get: cat1
                                - if:
                                    match: (\S)
                                    do:
                                    - object_field_set:
                                        object: product
                                        field: categories
                                        joinby: "|"
                                - variable_get: cat2
                                - if:
                                    match: (\S)
                                    do:
                                    - object_field_set:
                                        object: product
                                        field: categories
                                        joinby: "|"
                                - variable_get: cat3
                                - if:
                                    match: (\S)
                                    do:
                                    - object_field_set:
                                        object: product
                                        field: categories
                                        joinby: "|"
                            - find: 
                                path: .product-full__image > img
                                do: 
                                - parse:
                                    attr: src
                                - normalize:
                                    routine: url
                                - object_field_set:
                                    object: product
                                    field: images
                                    joinby: "|"
                            - find: 
                                path: script:matches(var\s*page_data) 
                                do: 
                                - parse:
                                    filter:
                                        - page_data\s*\=\s*(.+)
                                - normalize:
                                    routine: json2xml
                                - normalize:
                                    routine: replace_substring
                                    args:
                                        attribute_desc_\d: attribute_desc
                                - to_block
                                - find: 
                                    path: catalog-spp > products 
                                    do: 
                                    - find: 
                                        path: prod_rgn_name
                                        slice: 0
                                        do: 
                                        - parse
                                        - space_dedupe
                                        - trim
                                        - if:
                                            match: (\S)
                                            do:
                                            - object_field_set:
                                                object: product
                                                field: name
                                    - find: 
                                        path: product_details_long 
                                        do: 
                                        - parse
                                        - space_dedupe
                                        - trim
                                        - if:
                                            match: (\S)
                                            do:
                                            - if:
                                                match: (<[Pp]+>)
                                                do:
                                                - to_block
                                                - parse
                                                - space_dedupe
                                                - trim
                                                - object_field_set:
                                                    object: product
                                                    field: description
                                                else:
                                                - object_field_set:
                                                    object: product
                                                    field: description
                                    - find: 
                                        path: product_id
                                        slice: 0
                                        do: 
                                        - parse
                                        - space_dedupe
                                        - trim
                                        - if:
                                            match: (\S)
                                            do:
                                            - object_field_set:
                                                object: product
                                                field: sku
                                    - find: 
                                        path: skus > shadename
                                        do: 
                                        - parse
                                        - if:
                                            match: (\S)
                                            do:
                                            - object_field_set:
                                                object: product
                                                field: variations
                                                joinby: "|"
                                    - find: 
                                        path: skus > xl_image, skus > xl_smoosh
                                        do: 
                                        - parse
                                        - normalize:
                                            routine: url
                                        - object_field_set:
                                            object: product
                                            field: images
                                            joinby: "|"
                                    - find: 
                                        path: pricerange
                                        slice: 0
                                        do: 
                                        - parse:
                                            filter: 
                                                - ^\s*\$\s*(\d+\.?\d*)\s*-
                                                - (\d+\.?\d*)
                                        - if:
                                            match: (\d)
                                            do:
                                            - object_field_set:
                                                object: product
                                                field: price
                                                type: float
                                            - register_set: USD
                                            - object_field_set:
                                                object: product
                                                field: currency
                            - object_save:
                                name: product
