---
config:
    debug: 2
    agent: Firefox
do:
- walk:
    to: http://www.hugoboss.com/us/
    do:
    - find: 
        path: .main-nav__level3__link 
        do: 
        - pool_clear: main
        
        - parse:
            attr: href
        - link_add:
            pool: main
        - walk:
            to: links
            pool: main
            do:
            - find: 
                path: .load-more__btn 
                do: 
                - parse:
                    attr: href
                - normalize:
                    routine: replace_substring
                    args:
                        \&sz\=\d+\&start\=\d+: '&sz=1000&start=0'
                - link_add:
                    pool: main
            - find: 
                path: .product-tile 
                do: 
                - parse:
                    attr: data-url
                - link_add:
                    pool: sub
- walk:
    to: links
    pool: sub
    do:
    - variable_clear: descr
    - object_new: product
    - find: 
        in: doc
        path: head 
        do: 
        - eval:
            routine: js
            body: '(function (){var d = new Date(); return d.toISOString()})();'
        - object_field_set:
            object: product
            field: date
        - static_get: url
        - object_field_set:
            object: product
            field: url
    - find: 
        path: .breadcrumb__list a 
        do: 
        - parse
        - space_dedupe
        - trim
        - if:
            match: (\S)
            do:
            - object_field_set:
                object: product
                field: categories
                joinby: "|"
    - find: 
        path: '#pdpMain' 
        do: 
        - parse:
            attr: data-pid
            filter:
                - (\d+)
        - if:
            match: (\d)
            do:
            - object_field_set:
                object: product
                field: sku
    - find: 
        path: .product-price--price 
        do: 
        - parse:
            attr: data-pricing
        - normalize:
            routine: json2xml
        - to_block
        - find: 
            path: price 
            do: 
            - parse
            - if:
                match: (\d)
                do:
                - object_field_set:
                    object: product
                    field: price
                    type: float
                - register_set: USD
                - object_field_set:
                    object: product
                    field: currency
    - find: 
        path: .page-width-wrapper__inner[data-brand] 
        do: 
        - parse:
            attr: data-brand
        - space_dedupe
        - trim
        - if:
            match: (\S)
            do:
            - object_field_set:
                object: product
                field: brand
    - find: 
        path: .product-stage__headline 
        do: 
        - parse
        - space_dedupe
        - trim
        - if:
            match: (\S)
            do:
            - object_field_set:
                object: product
                field: name
    - find: 
        path: .swatch-list__button--is-large 
        do: 
        - parse:
            attr: aria-label
        - space_dedupe
        - trim
        - if:
            match: (\S)
            do:
            - object_field_set:
                object: product
                field: variations
                joinby: "|"
    - find: 
        path: .product-container__text__description 
        do: 
        - parse
        - space_dedupe
        - trim
        - if:
            match: (\S)
            do:
            - object_field_set:
                object: product
                field: description
    - find:
        path: '#slider-item__image' 
        do:
        - parse:
            attr: src
            filter:
                - (.+)\?
        - if:
            match: (\S)
            do:
            - normalize:
                routine: replace_substring
                args:
                    \s*$: '?scl=1'
            - object_field_set:
                object: product
                field: images
                joinby: "|"
        - parse:
            attr: data-lazy
            filter:
                - (.+)\?
        - if:
            match: (\S)
            do:
            
            - normalize:
                routine: replace_substring
                args:
                    \s*$: '?scl=1'
            - object_field_set:
                object: product
                field: images
                joinby: "|"
    - find: 
        path: .swatch-list__button--is-empty > a
        do: 
        - parse:
            attr: href
        - normalize:
            routine: url
        - normalize:
            routine: replace_substring
            args:
                \s*$: '?Quantity=1&origin=&format=ajax'
        - walk:
            to: value
            do:
            - find:
                path: '#slider-item__image' 
                do:
                - parse:
                    attr: src
                    filter:
                        - (.+)\?
                - if:
                    match: (\S)
                    do:
                    - normalize:
                        routine: replace_substring
                        args:
                            \s*$: '?scl=1'
                    - object_field_set:
                        object: product
                        field: images
                        joinby: "|"
                - parse:
                    attr: data-lazy
                    filter:
                        - (.+)\?
                - if:
                    match: (\S)
                    do:
                    
                    - normalize:
                        routine: replace_substring
                        args:
                            \s*$: '?scl=1'
                    - object_field_set:
                        object: product
                        field: images
                        joinby: "|"
    - object_save:
        name: product
