---
config:
    debug: 2
    agent: Firefox
do:
- walk:
    to: http://www.joesjeans.com
    do:
    - find: 
        path: .widget-sidenavigation  .menu-main-menu a 
        do: 
        - parse:
            attr: href
        - if:
            match: '(\/l\/)'
            do:
            - filter:
                args: 
                    - \/l\/(\d+)
            - variable_set: cat
            - register_set: http://www.joesjeans.com/l/products/<%cat%>?PageSize=8&CountryCode=&Sort=&Colors=&Sizes=&Attributes=&Page=1
            - pool_clear: main
            - link_add:
                pool: main
            - variable_set:
                field: firstcall
                value: 1
            
            - walk:
                to: links
                pool: main
                do:
                - variable_clear: totalcount
                - find: 
                    path: html 
                    do: 
                    - variable_get: firstcall
                    - if:
                        match: (1)
                        do:
                        - find: 
                            path: totalcount 
                            do: 
                            - parse
                            - variable_set: totalcount
                        - eval:
                            routine: js
                            body: '(function () {
                                    var arr = [];
                                    var num = <%totalcount%>;
                                    var b = 0;
                                    for(var i = 2;i < (num/8); i++){
                                            arr.push(i);
                                            b = i;
                                        }
                                    arr.push(b+1);
                                    return "<div>"+arr.join(",")+"</div>";
                                })();'
                        - to_block
                        - split:
                            context: text
                            delimiter: ","
                        - find: 
                            path: .splitted 
                            do: 
                            - parse
                            - register_set: http://www.joesjeans.com/l/products/<%cat%>?PageSize=8&CountryCode=&Sort=&Colors=&Sizes=&Attributes=&Page=<%register%>
                            - link_add:
                                pool: main
                        else:
                        - variable_clear: firstcall
                - find: 
                    path: body_safe 
                    do: 
                    - find: 
                        path: products > detailsurl 
                        do: 
                        - parse
                        - register_set: <%register%>?CategoryId=<%cat%>
                        - normalize:
                            routine: url
                        - walk:
                            to: value
                            do:
                            - object_new: product
                            - find: 
                                in: doc
                                path: head 
                                do: 
                                - eval:
                                    routine: js
                                    body: '(function (){var d = new Date(); return d.toISOString()})();'
                                - object_field_set:
                                    object: product
                                    field: date
                                - register_set: Joes Jeans
                                - object_field_set:
                                    object: product
                                    field: brand
                                - static_get: url
                                - object_field_set:
                                    object: product
                                    field: url
                            - find: 
                                path: '.breadcrumb a' 
                                slice: 0:-2
                                do: 
                                - parse
                                - space_dedupe
                                - trim
                                - normalize:
                                    routine: lower
                                - if:
                                    match: (\S)
                                    do:
                                    - object_field_set:
                                        object: product
                                        field: categories
                                        joinby: "|"
                            - find: 
                                path: .os-product-name
                                do: 
                                - parse
                                - space_dedupe
                                - trim
                                - object_field_set:
                                    object: product
                                    field: name
                            - find: 
                                path: script:matches(var\s*\_\_onestop\_pageData\s*=\s*)  
                                do: 
                                - parse:
                                    filter:
                                        - onestop\_pageData\s*=\s*(.+);
                                - normalize:
                                    routine: json2xml
                                - to_block
                                - find: 
                                    path: body_safe 
                                    do: 
                                    - find: 
                                        path: product 
                                        do: 
                                        - find: 
                                            path: description1 
                                            do: 
                                            - parse
                                            - parse
                                            - space_dedupe
                                            - trim
                                            - object_field_set:
                                                object: product
                                                field: description
                                            - to_block
                                            - find: 
                                                path: table
                                                do: 
                                                - parse
                                                - space_dedupe
                                                - trim
                                                - object_field_set:
                                                    object: product
                                                    field: description
                                        - find: 
                                            path: mfgsku
                                            slice: 0
                                            do: 
                                            - parse
                                            - space_dedupe
                                            - trim
                                            - object_field_set:
                                                object: product
                                                field: sku
                                        - find: 
                                            path: price 
                                            do: 
                                            - parse
                                            - if:
                                                match: (\d)
                                                do:
                                                - object_field_set:
                                                    object: product
                                                    field: price
                                                    type: float
                                                - register_set: USD
                                                - object_field_set:
                                                    object: product
                                                    field: currency
                                        - find: 
                                            path: productimageurl 
                                            do: 
                                            - parse
                                            - space_dedupe
                                            - trim
                                            - if:
                                                match: (\S)
                                                do:
                                                - normalize:
                                                    routine: url
                                                - object_field_set:
                                                    object: product
                                                    field: images
                                                    joinby: "|"
                                        - find: 
                                            path: productcolors > colorname
                                            do: 
                                            - parse
                                            - space_dedupe
                                            - trim
                                            - object_field_set:
                                                object: product
                                                field: variations
                                                joinby: "|"
                                        - find: 
                                            path: media > items > imageurl
                                            do: 
                                            - parse
                                            - space_dedupe
                                            - trim
                                            - if:
                                                match: (\S)
                                                do:
                                                - normalize:
                                                    routine: url
                                                - object_field_set:
                                                    object: product
                                                    field: images
                                                    joinby: "|"
                            - object_save:
                                name: product
