---
config:
    debug: 2
    agent: Firefox
do:
- walk:
    to: https://guessbymarciano.guess.com/en/menu/index?menuTypes=MainMenu,MainMobileMenu,SideMenu&country=US
    headers:
        X-Requested-With: XMLHttpRequest
    do:
    - find: 
        path: items > url
        do: 
        - pool_clear: default
        - parse
        - variable_set: ur
        - register_set: <%register%>?filter=true&f_Price=0-2500000&page=1&sort=relevance
        - link_add
        - walk:
            to: links
            headers:
                X-Requested-With: XMLHttpRequest
            do:
            - find: 
                path: .prodImg > a
                do: 
                - parse:
                    filter: 
                        - (.+)\?
                        - (.+)
                    attr: href
                - if:
                    match: (\S)
                    do:
                    - link_add:
                        pool: sub
            - find: 
                path: script
                slice: 0
                do: 
                - parse
                - filter:
                    args:
                        - gc\.ProductList\.Page\.ScrollTotalPages\s*=\s*(\d+)\s*;\s*if
                        - gc\.ProductList\.Page\.ScrollTotalPages\s*=\s*(\d+)
                - variable_set: register
                
                - if:
                    match: (\d)
                    do:
                    - eval:
                        routine: js
                        body: '(function () {
                            var str = "";
                            for(var i = 2; i <= <%register%>; i++){
                                str += i;
                                if (i != <%register%>){
                                str += ",";
                                }
                            }
                            return "<div>"+str+"</div>";
                            })();'
                    - to_block
                    - find: 
                        path: div 
                        do: 
                        - split:
                            context: text
                            delimiter: ","
                        - find: 
                            path: .splitted 
                            do: 
                            - parse
                            - if:
                                match: (\d)
                                do:
                                - register_set: <%ur%>?filter=true&f_Price=0-2500000&page=<%register%>&sort=relevance
                                - link_add
- walk:
    to: links
    pool: sub
    headers: 
        X-Requested-With: 
    do:
    - object_new: product
    - find: 
        in: doc
        path: head 
        do: 
        - eval:
            routine: js
            body: '(function (){var d = new Date(); return d.toISOString()})();'
        - object_field_set:
            object: product
            field: date
        - static_get: url
        - object_field_set:
            object: product
            field: url
    - find: 
        path: .rightdetails  > h1.header-big
        do: 
        - parse
        - space_dedupe
        - trim
        - object_field_set:
            object: product
            field: name
    - find: 
        path: .prodDescSpacer 
        do: 
        - find: 
            path: p 
            do: 
            - parse
            - space_dedupe
            - trim
            - object_field_set:
                object: product
                field: description
    - find: 
        path: script:matches(dataLayer\.push) 
        do: 
        - parse
        - space_dedupe
        - trim
        - filter:
            args:
                - dataLayer.push\((.+)\)\;\s*dataLayer
        - normalize:
            routine: json2xml
        - to_block
        - find: 
            path: pageBreadcrumb 
            do: 
            - split:
                context: text
                delimiter: \|
            - find: 
                path: .splitted
                slice: 2:-2
                do: 
                - parse
                - space_dedupe
                - trim
                - normalize:
                    routine: lower
                - object_field_set:
                    object: product
                    field: categories
                    joinby: "|"
        - find: 
            path: sitebrand 
            do: 
            - parse
            - space_dedupe
            - trim
            - object_field_set:
                object: product
                field: brand
        - find: 
            path: productcurrentprice 
            do: 
            - parse
            - if:
                match: (\d)
                do:
                - object_field_set:
                    object: product
                    field: price
                    type: float
                - register_set: USD
                - object_field_set:
                    object: product
                    field: currency
        - find: 
            path: productid 
            do: 
            - parse
            - object_field_set:
                object: product
                field: sku
            - variable_set: pid
            - find: 
                path: .colors > li img
                in: doc
                do: 
                - parse:
                    attr: alt
                - object_field_set:
                    object: product
                    field: variations
                    joinby: "|"
                - parse:
                    attr: id
                - walk:
                    to: https://guessbymarciano.guess.com/en/product/jsonretrieveproductdetails?styleId=<%pid%>&color=<%register%>
                    headers:
                        X-Requested-With: XMLHttpRequest
                    do:
                    - find: 
                        path: images 
                        do: 
                        - parse
                        - register_set: https://a248.e.akamai.net/f/248/9086/10h/origin-d5.scene7.com/is/image/Guess/<%register%>?$2014_G_xxlarge$
                        - object_field_set:
                            object: product
                            field: images
                            joinby: "|"
    - object_save:
        name: product
