---
config:
    debug: 2
    agent: Firefox
do:
- walk:
    to: https://www.faithfullthebrand.com/collections/all
    do:
    - find: 
        path: '.main-content .main-menu .font-nav li a' 
        do: 
        - variable_clear: type
        - parse
        - space_dedupe
        - trim
        - normalize:
            routine: lower
        - variable_set: type
        - parse:
            attr: href
        - normalize:
            routine: url
        - pool_clear: main
        - link_add:
            pool: main
        - walk:
            to: links
            pool: main
            do:
            - find:
                path: .pagination .arrow.right:not(.unavailable) a
                do:
                - parse:
                    attr: href
                - normalize:
                    routine: url
                - link_add:
                    pool: main
            - find: 
                path: .image-wrapper
                do: 
                - find: 
                    path: a
                    slice: 0
                    do: 
                    - parse:
                        attr: href
                    - normalize:
                        routine: url
                    - walk:
                        to: value
                        do:
                        - variable_clear: id
                        - find: 
                            path: body 
                            do: 
                            - object_new: product
                            - find: 
                                in: doc
                                path: head 
                                do: 
                                - eval:
                                    routine: js
                                    body: '(function (){var d = new Date(); return d.toISOString()})();'
                                - object_field_set:
                                    object: product
                                    field: date
                                - static_get: url
                                - object_field_set:
                                    object: product
                                    field: url
                                - register_set: faithfull the brand
                                - object_field_set:
                                    object: product
                                    field: brand
                            - find: 
                                path: .page-title 
                                do: 
                                - parse
                                - space_dedupe
                                - trim
                                - object_field_set:
                                    object: product
                                    field: name
                            - find: 
                                path: .accordion:matches(DESCRIPTION)+.container 
                                do: 
                                - parse
                                - space_dedupe
                                - trim
                                - object_field_set:
                                    object: product
                                    field: description
                            - find: 
                                path: .actual-price 
                                do: 
                                - parse:
                                    filter:
                                        - (\d+\.?\d*)
                                - if:
                                    match: (\d)
                                    do:
                                    - object_field_set:
                                        object: product
                                        field: price     
                                        type: float
                                    - register_set: USD
                                    - object_field_set:
                                        object: product
                                        field: currency
                            - find: 
                                path: .p1 
                                do: 
                                - parse
                                - space_dedupe
                                - trim
                                - if:
                                    match: (\S)
                                    do:
                                    - object_field_set:
                                        object: product
                                        field: description
                            - static_get: url
                            - variable_set: url
                            - register_set: https://foursixty.com/api/v2/faithfullthebrand/timeline?page_size=25&format=json&page=1&connector_filter=&for_url=<%url%>
                            - walk:
                                to: value
                                do:
                                - find: 
                                    path: main_image_url 
                                    do: 
                                    - parse
                                    - normalize:
                                        routine: url
                                    - object_field_set:
                                        object: product
                                        field: images
                                        joinby: "|"
                            - register_set: <%url%>.js
                            - set_converter:
                                content_type: text/javascript
                                converter: json
                            - walk:
                                to: value
                                do:
                                - find: 
                                    path: body_safe > variants > sku
                                    do: 
                                    - parse
                                    - object_field_set:
                                        object: product
                                        field: sku
                                - find: 
                                    path: tags 
                                    do: 
                                    - parse
                                    - space_dedupe
                                    - trim
                                    - normalize:
                                        routine: lower
                                    - object_field_set:
                                        object: product
                                        field: categories
                                        joinby: "|"
                            - clear_converter:
                                content_type: text/javascript
                            - find: 
                                path: .thumb > img
                                do: 
                                - parse:
                                    attr: src
                                - normalize:
                                    routine: replace_substring
                                    args:
                                        _large: ''
                                        \?.+: ''
                                        \/\/: http://
                                - object_field_set:
                                    object: product
                                    field: images
                                    joinby: "|"
                            - register_set: <%type%>
                            - object_field_set:
                                object: product
                                field: categories
                                joinby: "|"
                            - object_save:
                                name: product
