#cdekmarket digger
---
config:
    debug: 2
    agent: Firefox
do:
- variable_set:
    field: rep
    value: "yes"
- counter_reset: catalogRetries 
- walk:
    to: links
    repeat_in_pool: <%rep%>
    do:
    - variable_clear: query
    - variable_clear: rep
    - counter_increment:
        name: catalogRetries
    - find: 
        path: body 
        do: 
        - static_get: responseCode
        - if:
            match: 503|423|404
            do:
            - counter_get: catalogRetries
            - if:
                gt: 10
                type: int
                do:
                - error: cannot retrieve a page after 10 retries, skipping
                - proxy_switch
                - cookie_reset
                - counter_reset: catalogRetries
                else:
                - proxy_switch
                - cookie_reset
                - variable_set: 
                    field: rep
                    value: "yes"
    - find: 
        path: .ty-pagination__next 
        do: 
        - parse:
            attr: href
        - if:
            match: \S
            do:
            - normalize:
                routine: url
            - link_add
    - find: 
        path: .grid-list a.product-title
        do: 
        - variable_clear: pLink
        - parse:
            attr: href
        - if:
            match: \S
            do:
            - normalize:
                routine: url
            - variable_set: pLink
            - variable_set: 
                field: pRep
                value: "yes"
            - counter_reset: productReties
            - walk:
                to: <%pLink%>
                repeat: <%pRep%>
                do:
                - variable_clear: pRep
                - counter_increment:
                    name: productReties
                - find: 
                    path: body 
                    do: 
                    - static_get: responseCode
                    - if:
                        match: 503|423|404
                        do:
                        - counter_get: productReties
                        - if:
                            gt: 10
                            type: int
                            do:
                            - error: cannot retrieve a page after 10 retries, skipping
                            - proxy_switch
                            - cookie_reset
                            else:
                            - proxy_switch
                            - cookie_reset
                            - variable_set: 
                                field: pRep
                                value: "yes"
                        else:
                        - find: 
                            path: html
                            in: doc
                            do: 
                            - object_new: item
                            - static_get: url
                            - object_field_set:
                                object: item
                                field: url
                            - find: 
                                path: .ty-product-block-title 
                                do: 
                                - parse
                                - space_dedupe
                                - trim
                                - object_field_set:
                                    object: item
                                    field: title
                            - find: 
                                path: .ty-breadcrumbs__a
                                slice: 1:-2
                                do: 
                                - parse
                                - space_dedupe
                                - trim
                                - if:
                                    match: \S
                                    do:
                                    - object_field_set:
                                        object: item
                                        field: categories
                                        joinby: ","
                            - find: 
                                path: '#content_description' 
                                do: 
                                - node_remove: style,script
                                - parse
                                - space_dedupe
                                - trim
                                - if:
                                    match: \S
                                    do:
                                    - object_field_set:
                                        object: item
                                        field: description
                            - find: 
                                path: 'meta[itemprop="price"]' 
                                do: 
                                - parse:
                                    attr: content
                                - if:
                                    match: \d
                                    do:
                                    - object_field_set:
                                        object: item
                                        field: price
                            - find: 
                                path: 'meta[itemprop="sku"]' 
                                do: 
                                - parse:
                                    attr: content
                                - if:
                                    match: \d
                                    do:
                                    - object_field_set:
                                        object: item
                                        field: sku
                            - find: 
                                path: .ypi-vendor-link a 
                                slice: 0
                                do: 
                                - parse
                                - space_dedupe
                                - trim
                                - if:
                                    match: \S
                                    do:
                                    - object_field_set:
                                        object: item
                                        field: seller
                            - find: 
                                path: link[itemprop="availability"] 
                                do: 
                                - parse:
                                    attr: href
                                - if:
                                    match: InStock
                                    do:
                                    - register_set: "yes"
                                    - object_field_set:
                                        object: item
                                        field: instock
                                    else:
                                    - register_set: "no"
                                    - object_field_set:
                                        object: item
                                        field: instock
                            - find: 
                                path: '#content_features'
                                do: 
                                - find: 
                                    path: .ty-product-feature:hasChild(.ty-product-feature__label:matches([Бб]ренд\:)) > .ty-product-feature__value 
                                    do: 
                                    - parse
                                    - space_dedupe
                                    - trim
                                    - if:
                                        match: \S
                                        do:
                                        - object_field_set:
                                            object: item
                                            field: brand
                                - find: 
                                    path: .ty-product-feature:hasChild(.ty-product-feature__label:matches([Цц]вет\:)) > .ty-product-feature__value,.ty-product-feature:hasChild(.ty-product-feature__label:matches([Цц]вет товара\:)) > .ty-product-feature__value 
                                    do: 
                                    - parse
                                    - space_dedupe
                                    - trim
                                    - if:
                                        match: \S
                                        do:
                                        - object_field_set:
                                            object: item
                                            field: color       
                                - find: 
                                    path: .ty-product-feature:hasChild(.ty-product-feature__label:matches([пП]ол\:)) > .ty-product-feature__value
                                    do: 
                                    - parse
                                    - space_dedupe
                                    - trim
                                    - if:
                                        match: \S
                                        do:
                                        - object_field_set:
                                            object: item
                                            field: gender 
                            - find: 
                                path: meta[property="og:image"]
                                do:
                                - parse:
                                    attr: content
                                - if:
                                    match: \S
                                    do:
                                    - normalize:
                                        routine: url
                                    - object_field_set:
                                        object: item
                                        field: image
                            - object_save:
                                name: item
