---
config:
    debug: 2
    agent: Firefox
do:
- walk:
    to: http://www.cartier.com/en-us/collections.html
    do:
    - find:
        path: ul.c-navigation__ulist a
        do:
        - parse:
            attr: href
            filter: ^([^\?]+)
        - space_dedupe
        - trim
        - normalize:
            routine: replace_matched
            args:
                javascript\:: ''
        - if:
            match: \s*[a-z]+
            do:
            - normalize:
                routine: url
            - link_add:
                pool: catalog
- walk:
    to: links
    pool: catalog
    do:
    - sleep: 2
    - find:
        path: a.c-collection-link
        do:
        - parse:
            attr: href
            filter: ^([^\?]+)
        - space_dedupe
        - trim
        - normalize:
            routine: replace_matched
            args:
                javascript\:: ''
        - if:
            match: \s*[a-z]+
            do:
            - normalize:
                routine: url
            - link_add:
                pool: catalog
    - find:
        path: a.prod-link
        do:
        - parse:
            attr: href
            filter: ^([^\?]+)
        - space_dedupe
        - trim
        - normalize:
            routine: replace_matched
            args:
                javascript\:: ''
        - if:
            match: \s*[a-z]+
            do:
            - normalize:
                routine: url
            - link_add:
                pool: pages
- walk:
    to: links
    pool: pages
    do:
    - sleep: 2
    - find:
        path: div.main-container
        do:
        - variable_clear: desc
        - object_new: product
        - eval:
            routine: js
            body: '(function (){var d = new Date(); return d.toISOString()})();'
        - object_field_set:
            object: product
            field: date
        - static_get: url
        - object_field_set:
            object: product
            field: url
        - find:
            path: span.c-pdp__cta-section--product-title
            do:
            - parse
            - space_dedupe
            - trim
            - object_field_set:
                object: product
                field: name
        - register_set: Cartier
        - object_field_set:
            object: product
            field: brand
        - find:
            path: div.c-pdp__cta-section--product-ref-id>span
            do:
            - parse
            - space_dedupe
            - trim
            - if:
                match: \w+
                do:
                - variable_set: pid
                - object_field_set:
                    object: product
                    field: sku
        - find:
            in: doc
            path: meta[property="description"]
            do:
            - parse:
                attr: content
            - space_dedupe
            - trim
            - variable_set: desc
        - find:
            path: div.c-pdp__desc--content
            do:
            - parse
            - space_dedupe
            - trim
            - variable_set: desc
        - variable_get: desc
        - object_field_set:
            object: product
            field: description
        - find:
            path: div.c-pdp__cta-section--product-price
            do:
            - find:
                path: div.price
                do:
                - parse
                - normalize:
                    routine: replace_matched
                    args:
                        \$: USD
                - object_field_set:
                    object: product
                    field: currency
                - parse:
                    filter:
                    - ([0-9\.\,]+)\s*-
                    - ([0-9\.\,]+)
                - normalize:
                    routine: replace_substring
                    args:
                        \,: ''
                - space_dedupe
                - trim
                - object_field_set:
                    object: product
                    type: float
                    field: price
        - find:
            path: ul.c-breadcrumb__list>li.c-breadcrumb__list-item>a
            do:
            - parse
            - space_dedupe
            - trim
            - normalize:
                routine: replace_matched
                args:
                    Collections: ''
                    Categories: ''
            - if:
                match: \w+
                do:
                - object_field_set:
                    object: product
                    joinby: "|"
                    field: categories
        - find:
            path: div.c-pdp__image--wrapper
            do:
            - parse:
                attr: data-src
            - space_dedupe
            - trim
            - if:
                match: \w+
                do:
                - normalize:
                    routine: url
                - object_field_set:
                    object: product
                    joinby: "|"
                    field: images
        - object_save:
            name: product
