---
config:
    debug: 2
    agent: Opera/9.80 (Windows NT 6.0) Presto/2.12.388 Version/12.14
    proxy: #USE YOUR PROXY HERE LIKE 1.1.1.1:8888
do:
- pool_clear: catalog
- pool_clear: pages
- walk:
    to: https://www.hollisterco.com/shop/wd/
    headers:
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
        Accept-Language: ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4
        Cache-Control: no-cache
        Host: www.hollisterco.com
        Pragma: no-cache
        Proxy-Connection: keep-alive
        Upgrade-Insecure-Requests: 1
        user-agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36'
    do:
    - find:
        path: ul.nav-accordion-container--level1 a.rs-nav-link--minor
        do:
        - parse:
            attr: href
        - space_dedupe
        - trim
        - if:
            match: \w+
            do:
            - if:
                match: \?+
                else:
                - normalize:
                    routine: url
                - link_add:
                    pool: catalog
- walk:
    to: links
    pool: catalog
    do:
    - find:
        path: ul.grid-nav__items-group>li>a.grid-nav__item-link
        do:
        - parse:
            attr: href
        - space_dedupe
        - trim
        - if:
            match: \w+
            do:
            - if:
                match: \?+
                else:
                - normalize:
                    routine: url
                - link_add:
                    pool: catalog
    - find:
        path: div.products
        do:
        - parse:
            attr: data-result-total
        - if:
            match: \d+
            do:
            - variable_set: total
            - eval:
                routine: js
                body: (function(){var t = <%total%>;var offset = [];for(var i = 90; i < t; i+=90){offset.push(i)}; return offset.join(",");})();
            - to_block
            - split:
                context: text
                delimiter: ","
            - find:
                path: div
                do:
                - parse
                - if:
                    match: \d+
                    do:
                    - variable_set: offset
                    - static_get: url
                    - filter:
                        args: ^([^\?]+)
                    - register_set: <%register%>?search-field=&sort=bestmatch&start=<%offset%>&rows=90&filtered=true
                    - link_add:
                        pool: catalog
    - find:
        path: div.products
        do:
        - find:
            path: a.product-card__name
            do:
            - parse:
                attr: href
            - space_dedupe
            - trim
            - if:
                match: \w+
                do:
                - normalize:
                    routine: url
                - link_add:
                    pool: pages
- walk:
    to: links
    headers:
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
        Accept-Language: ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4
        Cache-Control: no-cache
        Host: www.hollisterco.com
        Pragma: no-cache
        Proxy-Connection: keep-alive
        Upgrade-Insecure-Requests: 1
        cookie: uPref=%7B%22cfi%22%3A%221%22%2C%22cur%22%3A%22USD%22%2C%22sf%22%3A%22US%22%7D; geoLocation=US:TX:;
        user-agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36'
    pool: pages
    do:
    - sleep: 3
    - variable_clear: pageurl
    - find:
        path: body
        do:
        - static_get: url
        - variable_set: pageurl
    - find:
        path: 'section.product'
        do:
        - variable_clear: pid
        - variable_clear: prid
        - variable_clear: cid
        - variable_clear: sin
        - variable_clear: desc
        - variable_clear: price
        - object_new: product
        - find:
            path: div.details__web-item-number>span.number
            do:
            - parse
            - object_field_set:
                object: product
                field: sku
        - parse:
            attr: data-collection
        - variable_set: pid
        - parse:
            attr: data-seq
        - variable_set: cid
        - parse:
            attr: data-productid
        - variable_set: prid
        - eval:
            routine: js
            body: '(function (){var d = new Date(); return d.toISOString()})();'
        - object_field_set:
            object: product
            field: date
        - variable_get: pageurl
        - object_field_set:
            object: product
            field: url
        - find:
            path: .product-page-title
            slice: 0
            do:
            - parse
            - space_dedupe
            - trim
            - object_field_set:
                object: product
                field: name
        - register_set: Hollister Co
        - object_field_set:
            object: product
            field: brand
        - find:
            path: p.details__description
            do:
            - parse
            - space_dedupe
            - trim
            - object_field_set:
                object: product
                field: description
        - find:
            path: script:contains('var globalProducts')
            do:
            - parse:
                filter: globalProducts\[\d+\]\s+\=\s+(.+);\s+\}\s+catch\(err\)
            - normalize:
                routine: json2xml
            - to_block
            - find:
                path: offerpricefmt
                slice: 0
                do:
                - parse
                - variable_set: price
        - find:
            in: doc
            path: div.upper-breadcrumb>div.breadcrumbs>a
            do:
            - parse
            - space_dedupe
            - trim
            - if:
                match: \w+
                do:
                - object_field_set:
                    object: product
                    joinby: "|"
                    field: categories
        - find:
            path: ul.product-swatches>li>label>span,ul.product-swatches>li>h2>span
            do:
            - parse
            - space_dedupe
            - trim
            - if:
                match: \w+
                do:
                - object_field_set:
                    object: product
                    joinby: "|"
                    field: variations
        - find:
            path: span.product-price-v2__price
            do:
            - parse:
                filter:
                - (\$[0-9\.]+)\s*-
                - (\$[0-9\.]+)
            - variable_set: price
            - variable_get: price
            - normalize:
                routine: replace_substring
                args:
                    \$: ''
            - object_field_set:
                object: product
                type: float
                field: price
            - variable_get: price
            - normalize:
                routine: replace_matched
                args:
                    \$: USD
            - object_field_set:
                object: product
                field: currency
        - register_set: https://anf.scene7.com/is/image/anf?imageset={anf/hol_<%pid%>_<%cid%>}&req=set,json&id=<%pid%>
        - walk:
            to: value
            do:
            - find:
                path: body
                do:
                - parse:
                    filter: s7jsonResponse\((.+),\&quot;\d+\&quot;\);
                - normalize:
                    routine: unescape_html
                - normalize:
                    routine: json2xml
                - to_block
                - find:
                    path: i>n
                    do:
                    - variable_clear: iurl
                    - parse
                    - variable_set: iurl
                    - register_set: https://anf.scene7.com/is/image/<%iurl%>?$product-zoom-hol-v1$
                    - object_field_set:
                        object: product
                        joinby: "|"
                        field: images
        - find:
            path: ul.product-swatches>li>label>input
            do:
            - variable_clear: cid
            - parse:
                attr: data-seq
            - variable_set: cid
            - register_set: https://anf.scene7.com/is/image/anf?imageset={anf/hol_<%pid%>_<%cid%>}&req=set,json&id=<%pid%>
            - walk:
                to: value
                do:
                - find:
                    path: body
                    do:
                    - parse:
                        filter: s7jsonResponse\((.+),\&quot;\d+\&quot;\);
                    - normalize:
                        routine: unescape_html
                    - normalize:
                        routine: json2xml
                    - to_block
                    - find:
                        path: i>n
                        do:
                        - variable_clear: iurl
                        - parse
                        - variable_set: iurl
                        - register_set: https://anf.scene7.com/is/image/<%iurl%>?$product-zoom-hol-v1$
                        - object_field_set:
                            object: product
                            joinby: "|"
                            field: images
        - object_save:
            name: product
