#zdravcityru digger
---
config:
    debug: 2
    agent: Chrome
do:
- variable_set: 
    field: crep
    value: "yes"
- counter_set: 
    name: catc
    value: 0
- walk:
    to: links
    repeat_in_pool: <%crep%>
    do:
    - variable_clear: pageOk
    - counter_increment:
        name: catc
    - variable_clear: crep
    - find: 
        path: body 
        do: 
        - find: 
            path: 'script#__NEXT_DATA__' 
            do: 
            - variable_set: 
                field: pageOk
                value: 1
            - parse
            - space_dedupe
            - trim
            - if:
                match: \S
                do:
                - normalize:
                    routine: json2xml
                - to_block
                - find: 
                    path: body_safe 
                    do: 
                    - object_new: item
                    - static_get: url
                    - object_field_set:
                        object: item
                        field: url
                    - register_set: "yes"
                    - object_field_set:
                        object: item
                        field: instock
                    - register_set: "no"
                    - object_field_set:
                        object: item
                        field: prescription
                    - find: 
                        path: pageprops > breadcrumbs
                        slice: 1:-2
                        do: 
                        - find: 
                            path: title 
                            do: 
                            - parse
                            - space_dedupe
                            - trim
                            - if:
                                match: \S
                                do:
                                - object_field_set:
                                    object: item
                                    field: categories
                                    joinby: ","
                    - variable_clear: cat
                    - find: 
                        path: pageprops > product 
                        do: 
                        - find: 
                            path: badges:hasChild(type:matches(prescription))
                            in: current
                            do: 
                            - register_set: "yes"
                            - object_field_set:
                                object: item
                                field: prescription
                        - find: 
                            path: categorypath 
                            in: current
                            do: 
                            - parse
                            - if:
                                match: \S
                                do:
                                - variable_set: cat
                                
                        - find: 
                            path: maxquantity 
                            in: current
                            do: 
                            - parse
                            - if:
                                match: ^0$
                                do:
                                - register_set: "no"
                                - object_field_set:
                                    object: item
                                    field: instock
                        - find: 
                            path: producercountry 
                            do: 
                            - parse
                            - space_dedupe
                            - trim
                            - if:
                                match: \S
                                do:
                                - object_field_set:
                                    object: item
                                    field: produced
                        - find: 
                            path: producer 
                            in: current
                            do: 
                            - parse
                            - space_dedupe
                            - trim
                            - if:
                                match: \S
                                do:
                                - object_field_set:
                                    object: item
                                    field: manufactorer
                        - find: 
                            path: safe_image 
                            in: current
                            do: 
                            - parse
                            - space_dedupe
                            - trim
                            - if:
                                match: \S
                                do:
                                - object_field_set:
                                    object: item
                                    field: image
                        - find: 
                            path: name
                            in: current
                            do: 
                            - parse
                            - space_dedupe
                            - trim
                            - if:
                                match: \S
                                do:
                                - object_field_set:
                                    object: item
                                    field: title
                        - find: 
                            path: price
                            in: current
                            do: 
                            - parse
                            - space_dedupe
                            - trim
                            - if:
                                match: \S
                                do:
                                - object_field_set:
                                    object: item
                                    field: price
                        - find: 
                            path: mnn
                            in: current
                            do: 
                            - parse
                            - space_dedupe
                            - trim
                            - if:
                                match: \S
                                do:
                                - object_field_set:
                                    object: item
                                    field: mnn
                        - find: 
                            path: certs 
                            in: current
                            do: 
                            - parse
                            - space_dedupe
                            - trim
                            - if:
                                match: \S
                                do:
                                - object_field_set:
                                    object: item
                                    field: certificates
                                    joinby: ","
                    - variable_get: cat
                    - if:
                        match: \S
                        do:
                        - find: 
                            path: '*:hasChild(path:matches(<%cat%>)) > name'
                            do: 
                            - parse
                            - space_dedupe
                            - trim
                            - if:
                                match: \S
                                do:
                                - object_field_set:
                                    object: item
                                    field: type
                    - object_save: 
                        name: item
    - proxy_switch
    - cookie_reset
    - find: 
        path: body 
        do: 
        - variable_get: pageOk
        - if:
            match: \S
            do:
            - counter_reset: catc
            else:
            - variable_set: 
                field: crep
                value: "yes"
            - counter_get: catc
            - if:
                gt: 4
                type: int
                do:
                - variable_clear: crep
                - counter_reset: catc
                - info: cannot fetch url after 5 retries, skipping