---
config:
    debug: 2
    agent: 'Mozilla/5.0 (BlackBerry; U; BlackBerry 9810; en) AppleWebKit/534.11+ (KHTML, like Gecko) Version/7.1.0.267 Mobile Safari/534.11+'
do:
- variable_set:
    field: rep
    value: "yes"
- counter_set: 
    name: start
    value: 0

- walk:
    to: https://www.patagonia.com/shop/clothing-gear/?cgid=root&sz=48&start=<%start%>&format=page-element
    repeat: <%rep%>
    headers:
        X-Requested-With: XMLHttpRequest
        Accept: text/html, */*; q=0.01
        Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7
        Cache-Control: no-cache
        Connection: keep-alive
    do:
    - find: 
        path: body 
        do:
        - variable_clear: exists
        - find: 
            path: .product-image a 
            do: 
            - variable_set: 
                field: exists
                value: 1
            - parse:
                attr: href
                filter:
                    - ^\s*([^\?]+)
            - if:
                match: \S
                do:
                - normalize:
                    routine: url
                - link_add:
                    pool: products
        - variable_get: exists
        - if:
            match: \d
            do:
            - counter_increment:
                name: start
                by: 48
            else:
            - variable_clear: rep
- walk:
    to: links
    pool: products
    headers:
        Accept: text/html, */*; q=0.01
        Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7
        Cache-Control: no-cache
        Pragma: no-cache
        Connection: keep-alive

        # Accept-Encoding: gzip
        
    do:
    - find: 
        path: body 
        do: 
        - cookie_reset
        - object_new: product
        - register_set: Patagonia
        - object_field_set:
            object: product
            field: brand
        - eval:
            routine: js
            body: '(function (){var d = new Date(); return d.toISOString()})();'
        - object_field_set:
            object: product
            field: date
        - static_get: url
        - object_field_set:
            object: product
            field: url
        - find: 
            path: a.breadcrumb-element 
            do: 
            - parse
            - space_dedupe
            - trim
            - if:
                match: \S
                do:
                - object_field_set:
                    object: product
                    field: categories
                    joinby: " | "
        - find: 
            path: 'span[itemprop="productID"]' 
            do: 
            - parse
            - space_dedupe
            - trim
            - object_field_set:
                object: product
                field: sku
        - find: 
            path: .color-name 
            do: 
            - parse
            - space_dedupe
            - trim
            - if:
                match: \S
                do:
                - object_field_set:
                    object: product
                    field: variations
                    joinby: " | "
        - find: 
            path: h1.product-name 
            do: 
            - parse
            - space_dedupe
            - trim
            - if:
                match: \S
                do:
                - object_field_set:
                    object: product
                    field: name
        - find: 
            path: 'span[itemprop="price"]'
            do: 
            - parse:
                attr: content
            - if:
                match: \d
                do:
                - object_field_set:
                    object: product
                    field: prcie
                    type: float
        - find: 
            path: .loading > li > img 
            do: 
            - parse:
                attr: data-zoom-image
            - if:
                match: \S
                do:
                - object_field_set:
                    object: product
                    field: images
                    joinby: " | "
        - find: 
            path: .product-short-desc, .product-learn-more-column:not(.ch-left-column)
            do: 
            - parse
            - space_dedupe
            - trim
            - if:
                match: \S
                do:
                - object_field_set:
                    object: product
                    field: description
                    joinby: "\n"
        - object_save:
            name: product
