---
config:
    debug: 2
    agent: Firefox
    proxy: #USE YOUR PROXY HERE LIKE 1.1.1.1:8888
do:
- walk:
    to: https://www.gilt.com/
    do:
    - find:
        path: div.nav-category
        slice: 2:7
        do:
        - variable_clear: cat
        - variable_clear: subcat
        - parse:
            attr: data-store-name
        - variable_set: cat
        - find:
            path: article.subnav-column>a
            do:
            - pool_clear: catalog
            - parse
            - space_dedupe
            - trim
            - variable_set: subcat
            - parse:
                attr: href
            - trim
            - if:
                match: \w+
                do:
                - normalize:
                    routine: url
                - link_add:
                    pool: catalog
                - walk:
                    to: links
                    pool: catalog
                    do:
                    - find:
                        path: a.next
                        slice: 0
                        do:
                        - parse:
                            attr: href
                        - trim
                        - if:
                            match: \w+
                            do:
                            - normalize:
                                routine: url
                            - link_add:
                                pool: catalog
                    - find:
                        path: a.product-link
                        do:
                        - parse:
                            attr: href
                        - trim
                        - if:
                            match: \w+
                            do:
                            - normalize:
                                routine: url
                            - normalize:
                                routine: replace_substring
                                args:
                                    ^http\:: 'https:'
                            - walk:
                                to: value
                                do:
                                - variable_set:
                                    field: valid
                                    value: "no"
                                - find:
                                    path: article.product-details
                                    do:
                                    - variable_set:
                                        field: valid
                                        value: "yes"
                                    - object_new: product
                                    - eval:
                                        routine: js
                                        body: '(function (){var d = new Date(); return d.toISOString()})();'
                                    - object_field_set:
                                        object: product
                                        field: date
                                    - static_get: url
                                    - object_field_set:
                                        object: product
                                        field: url
                                    - find:
                                        in: doc
                                        path: script:contains('config.product_details')
                                        do:
                                        - parse
                                        - normalize:
                                            routine: replace_substring
                                            args:
                                                \/\/\s+app\s+specific\s+configs: ''
                                                \n+: ' '
                                        - filter:
                                            args: config\.product_details",\s+(.+)\);
                                        - variable_set: pd
                                        - eval:
                                            routine: js
                                            body: (function () {var e = <%pd%>; return JSON.stringify(e);})();
                                        - normalize:
                                            routine: json2xml
                                        - to_block
                                        - find:
                                            path: body_safe>productname
                                            do:
                                            - parse
                                            - space_dedupe
                                            - trim
                                            - if:
                                                match: \w+
                                                do:
                                                - object_field_set:
                                                    object: product
                                                    field: name
                                        - find:
                                            path: body_safe>productdetails>brand>name
                                            do:
                                            - parse
                                            - space_dedupe
                                            - trim
                                            - if:
                                                match: \w+
                                                do:
                                                - object_field_set:
                                                    object: product
                                                    field: brand
                                        - find:
                                            path: body_safe>productdetails skus>skuid
                                            slice: 0
                                            do:
                                            - parse
                                            - space_dedupe
                                            - trim
                                            - variable_set: pid
                                            - object_field_set:
                                                object: product
                                                field: sku
                                        - find:
                                            path: body_safe>pricemin
                                            do:
                                            - parse
                                            - object_field_set:
                                                object: product
                                                type: float
                                                field: price
                                            - register_set: USD
                                            - object_field_set:
                                                object: product
                                                field: currency
                                        - find:
                                            path: body_safe>productdetails>product>description
                                            do:
                                            - parse
                                            - to_block
                                            - find:
                                                path: p
                                                slice: 0
                                                do:
                                                - node_remove: strong
                                                - parse
                                                - space_dedupe
                                                - trim
                                                - if:
                                                    match: \w+
                                                    do:
                                                    - object_field_set:
                                                        object: product
                                                        field: description
                                        - find:
                                            path: body_safe>productdetails>product>colorattribute>sortedvalues>value
                                            do:
                                            - parse
                                            - space_dedupe
                                            - trim
                                            - if:
                                                match: \w{2,}
                                                do:
                                                - object_field_set:
                                                    object: product
                                                    joinby: "|"
                                                    field: variations
                                        - variable_get: cat
                                        - if:
                                            match: \w{2,}
                                            do:
                                            - object_field_set:
                                                object: product
                                                joinby: "|"
                                                field: categories
                                        - variable_get: subcat
                                        - if:
                                            match: \w{2,}
                                            do:
                                            - object_field_set:
                                                object: product
                                                joinby: "|"
                                                field: categories
                                        - find:
                                            path: body_safe>productdetails>product>alllooks>images>origlookurl
                                            do:
                                            - parse
                                            - space_dedupe
                                            - trim
                                            - if:
                                                match: \w{2,}
                                                do:
                                                - normalize:
                                                    routine: url
                                                - object_field_set:
                                                    object: product
                                                    joinby: "|"
                                                    field: images
                                    - object_save:
                                        name: product
                                - find:
                                    path: html
                                    do:
                                    - variable_get: valid
                                    - if:
                                        match: "no"
                                        do:
                                        - banned
                                        - exit
