---
config:
    debug: 2
    agent: Firefox
do:
- walk:
    to: https://www.vans.com/
    do:
    - find:
        path: ul.topnav-main>li.has-dropdown
        slice: 0:2
        do:
        - find:
            path: ul.dropdown>li.sub-category
            do:
            - find:
                path: ul.content>li:not(:contains("SHOP NEW ARRIVALS")):not(:contains("SHOP THE LOOK")):not(:contains("STYLE")):not(:contains("LOOKS WE LOVE")):not(:contains("Shop All"))>a
                do:
                - parse:
                    attr: href
                - space_dedupe
                - trim
                - if:
                    match: \w+
                    do:
                    - normalize:
                        routine: url
                    - link_add:
                        pool: catalog
- walk:
    to: links
    pool: catalog
    do:
    - sleep: 2
    - variable_clear: totalcount
    - variable_clear: categoryid
    - variable_clear: storeid
    - variable_clear: catalogid
    - variable_clear: langid
    - variable_clear: perpage
    - find:
        path: input.total-count-js
        do:
        - parse:
            attr: value
        - variable_set: totalcount
    - find:
        path: span.ajax-product-search-js
        do:
        - parse:
            attr: data-value
            filter: categoryId\=(\d+)
        - variable_set: categoryid
        - parse:
            attr: data-value
            filter: storeId\=(\d+)
        - variable_set: storeid
        - parse:
            attr: data-value
            filter: catalogId\=(\d+)
        - variable_set: catalogid
        - parse:
            attr: data-value
            filter: langId\=([0-9\-]+)
        - variable_set: langid
    - find:
        path: input.products-per-page-js
        do:
        - parse:
            attr: value
        - variable_set: perpage
    - find:
        path: body
        do:
        - variable_get: totalcount
        - if:
            match: \d+
            do:
            - eval:
                routine: js
                body: (function () {
                            var pages = [];
                            for (var i=0; i <= <%totalcount%>; i+=<%perpage%>) {
                                pages.push(i)
                            };
                            return pages.join(",");
                        })();
            - to_block
            - split:
                context: text
                delimiter: ","
            - find:
                path: .splitted
                do:
                - parse
                - register_set: https://www.vans.com/shop/VFAjaxGetFilteredSearchResultsView?categoryId=<%categoryid%>&searchSource=N&storeId=<%storeid%>&catalogId=<%catalogid%>&langId=<%langid%>&beginIndex=<%register%>&returnProductsOnly=true&requesttype=ajax
                - walk:
                    to: value
                    do:
                    - find:
                        path: products
                        do:
                        - parse
                        - to_block
                        - find:
                            path: a.product-block-pdp-url
                            do:
                            - parse:
                                attr: href
                            - link_add:
                                pool: pages
- walk:
    to: links
    pool: pages
    do:
    - sleep: 2
    - find:
        path: article.page-contents
        do:
        - variable_clear: pid
        - object_new: product
        - eval:
            routine: js
            body: '(function () {
                        var d = new Date();
                        return d.toISOString();
                    })();'
        - object_field_set:
            object: product
            field: date
        - static_get: url
        - object_field_set:
            object: product
            field: url
        - find:
            path: script:contains("dataLayer")
            in: doc
            slice: 0
            do:
            - parse
            - space_dedupe
            - trim
            - filter:
                args: 'var\s+dataLayer\s+\=\s+(.+)\s*;'
            - normalize:
                routine: json2xml
            - to_block
            - find:
                path: body_safe > element > pdpproduct > sku
                do:
                - parse
                - variable_set: iid
                - object_field_set:
                    object: product
                    field: sku
            - find:
                path: body_safe > element > pdpproduct > category
                do:
                - parse
                - normalize:
                    routine: replace_matched
                    args:
                        Mens Classics: Mens Classics
                        Mens Skate: Mens Skate
                        Mens Surf: Mens Surf
                        Mens Sandals: Mens Sandals
                        H MW Snowboard Boots: Snowboard Boots
                        M Tees: Mens Tees
                        M Shirts: Mens Shirts
                        M Fleece and Hoodies: Mens Fleece and Hoodies
                        M Pants: Mens Pants
                        M Shorts: Mens Shorts
                        M Backpacks_Bags: Mens Backpacks_Bags
                        M Hats: Mens Hats
                        M Socks: Mens Socks
                        M Shoe Care: Mens Shoe Care
                        M Sunglasses: Mens Sunglasses
                        M Wallets: Mens Wallets
                        M Belts: Mens Belts
                        M Laces: Mens Laces
                        Womens Classics: Womens Classics
                        Womens Pro Skate: Womens Pro Skate
                        Womens Surf: Womens Surf
                        Womens Sandals: Womens Sandals
                        Womens Snowboard Boots: Womens Snowboard Boots
                        W Tees: Womens Tees
                        W Tops: Womens Tops
                        W Fleece and Hoodies: Womens Fleece and Hoodies
                        W Dresses: Womens Dresses
                        W Pants: Womens Pants
                        W Backpacks: Womens Backpacks
                        W Hats: Womens Hats
                        W Socks: Womens Socks
                        W Sunglasses: Womens Sunglasses
                        W Handbags: Womens Handbags
                        W Wallets: Womens Wallets
                        W Keychains: Womens Keychains
                        Little Boys: Little Boys
                        Little Girls: Little Girls
                        Toddlers_Infants: Toddlers Infants
                        H K Infant: Infant
                        B Tees and Tanks: Boys Tees and Tanks
                        B Fleece and Hoodies: Boys Fleece and Hoodies
                        B Bottoms: Boys Bottoms
                        B Shorts: Boys Shorts
                        Boys Hats: Boys Hats
                        Kids Socks: Kids Socks
                        SC_CA_M_SHOES_NEW_ARRIVALS: Mens Shoes
                - variable_set: cat
            - find:
                path: body_safe > element > pdpproduct > seoCategory
                do:
                - parse
                - variable_set: seocat

            - register_set: <%cat%>|<%seocat%>
            - variable_set: category
            - object_field_set:
                object: product
                field: category
        - find:
            path: 'span[itemprop="brand"] > meta[itemprop="name"]'
            do:
            - parse:
                attr: content
            - space_dedupe
            - trim
            - object_field_set:
                object: product
                field: brand
        - find:
            path: h1.product-info-js
            do:
            - parse
            - space_dedupe
            - trim
            - object_field_set:
                object: product
                field: name
        - find:
            path: 'div.product-details-desc-container'
            do:
            - parse
            - space_dedupe
            - trim
            - object_field_set:
                object: product
                field: description
        - find:
            in: doc
            path: head
            do:
            - find:
                path: meta[property="og:price:amount"]
                do:
                - parse:
                    attr: content
                - object_field_set:
                    object: product
                    type: float
                    field: amount
            - find:
                path: meta[property="og:price:currency"]
                do:
                - parse:
                    attr: content
                - object_field_set:
                    object: product
                    field: currency
        - find:
            in: doc
            path: 'form#product-attr-form > section > div > div[class*="color-swatches"] > button[data-form-button*="color-bnt"]'
            do:
            - parse:
                attr: data-attribute-value
            - space_dedupe
            - trim
            - if:
                match: (\S)
                do:
                - object_field_set:
                    object: product
                    field: variations
                    joinby: "|"
        - walk:
            to: https://images.vans.com/is/image/Vans/<%iid%>_is?req=set,json,UTF-8
            do:
            - find:
                path: script
                do:
                - parse:
                    filter: s7jsonResponse\((.+)\,\&quot;\&quot;\)\;
                - normalize:
                    routine: unescape_html
                - normalize:
                    routine: json2xml
                - to_block
                - find:
                    path: item > i > n
                    do:
                    - parse
                    - if:
                        match: \d+
                        do:
                        - variable_set: iurl
                        - register_set: https://images.vans.com/is/image/<%iurl%>?scl=02
                        - object_field_set:
                            object: product
                            field: images
                            joinby: "|"
        - object_save:
            name: product
