---
config:
    debug: 2
    agent: Firefox
do:
- walk:
    to: https://www.romwe.com
    do:
    - find: 
        path: .j-category-title  
        do: 
        - parse:
            attr: href
        - link_add:
            pool: main
- walk:
    to: links
    pool: main
    do:
    - find: 
        path: a:hasChild(.icon-right) 
        do: 
        - parse:
            attr: href
        - normalize:
            routine: replace_matched
            args:
                javascript: ''
        - if:
            match: \S
            do:
            - normalize:
                routine: url
            - link_add:
                pool: main
    - find: 
        path: .j-item-msg
        do: 
        - parse:
            attr: href
        - normalize:
            routine: url
        - link_add:
            pool: products
- walk:
    to: links
    pool: products
    do:
    - find: 
        path: body
        do: 
        - object_new: product
        - static_get: url
        - filter:
            args:
                - ^\s*([^?]+)
        - object_field_set:
            object: product
            field: url
        - eval:
            routine: js
            body: '(function (){var d = new Date(); return d.toISOString()})();'
        - object_field_set:
            object: product
            field: date
        - register_set: Romwe
        - object_field_set:
            object: product
            field: brand
        - find: 
            path: .c-breadcrumb > li
            slice: 1:-2
            do: 
            - parse
            - space_dedupe
            - trim
            - if:
                match: \S
                do:
                - object_field_set:
                    object: product
                    field: categories
                    joinby: " | "
        - find: 
            path: 'meta[itemprop="priceCurrency"]'
            do: 
            - parse:
                attr: content
            - space_dedupe
            - trim
            - if:
                match: \S
                do:
                - object_field_set:
                    object: product
                    field: currency
        - find: 
            path: .desc-con:has(.kv) 
            do: 
            - parse
            - space_dedupe
            - trim
            - if:
                match: \S
                do:
                - object_field_set:
                    object: product
                    field: description
        - find: 
            path: .img-thumbs .thumbs-wrapper img 
            do: 
            - parse:
                attr: data-src-1200
            - if:
                match: \S
                do:
                - normalize:
                    routine: url
                - object_field_set:
                    object: product
                    field: images
                    joinby: " | "
        - find: 
            path: 'meta[itemprop="name"]' 
            do: 
            - parse:
                attr: content
            - space_dedupe
            - trim
            - if:
                match: \S
                do:
                - object_field_set:
                    object: product
                    field: name
        - find: 
            path: 'meta[itemprop="price"]' 
            do: 
            - parse:
                attr: content
            - if:
                match: \d
                do:
                - object_field_set:
                    object: product
                    field: price
                    type: float
        - find: 
            path: .sku 
            do: 
            - parse:
                attr: data-sku
            - space_dedupe
            - trim
            - if:
                match: \S
                do:
                - object_field_set:
                    object: product
                    field: sku
        - find: 
            path: .opt-color > a 
            do: 
            - parse:
                attr: href
            - filter:
                args:
                    - ^\s*([^?]+)
            - if:
                match: \S
                do:
                - normalize:
                    routine: url
                - link_add:
                    pool: products
        - object_save:
            name: product
