# olxpl digger
---
config:
    agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
    debug: 2
    js_enabled: "yes"
do:
- variable_clear: token
- set_engine: surf
- variable_set:
    field: repeat
    value: "yes"
- walk:
    to: links
    repeat_in_pool: <%repeat%>
    do:
    - variable_clear: ok
    - find:
        path: script:contains("window.__PRERENDERED_STATE__")
        do:
        - parse
        - space_dedupe
        - trim
        - eval:
            routine: js
            body: (function () {var window = {}; <%register%>; return JSON.stringify(window.__PRERENDERED_STATE__);})();
        - normalize:
            routine: json2xml
        - to_block
        - find:
            path: body_safe
            do:
            - parse
            - normalize:
                routine: json2xml
            - to_block
            - find:
                path: body_safe > ad > ad
                do:
                - variable_clear: id
                - variable_set:
                    field: ok
                    value: 1
                - object_new: item
                - static_get: url
                - variable_set: url
                - object_field_set:
                    object: item
                    field: url
                - find:
                    in: current
                    path: title
                    do:
                    - parse
                    - space_dedupe
                    - trim
                    - object_field_set:
                        object: item
                        field: title
                - find:
                    in: current
                    path: id
                    do:
                    - parse:
                        filter: (\d+)
                    - if:
                        match: \d+
                        do:
                        - object_field_set:
                            object: item
                            field: ad_id
                        - variable_set: id
                - find:
                    in: current
                    path: lastrefreshtime
                    do:
                    - parse
                    - space_dedupe
                    - trim
                    - object_field_set:
                        object: item
                        field: date
                - find:
                    path: contact > name
                    do:
                    - parse
                    - space_dedupe
                    - trim
                    - object_field_set:
                        object: item
                        field: seller
                - find:
                    path: location > pathname
                    do:
                    - parse
                    - space_dedupe
                    - trim
                    - object_field_set:
                        object: item
                        field: address
                - find:
                    path: price > regularprice > value
                    do:
                    - parse
                    - space_dedupe
                    - trim
                    - object_field_set:
                        object: item
                        field: price
                - find:
                    path: price > regularprice > currencycode
                    do:
                    - parse
                    - space_dedupe
                    - trim
                    - object_field_set:
                        object: item
                        field: currency
                - find:
                    path: isbusiness
                    do:
                    - parse
                    - space_dedupe
                    - trim
                    - normalize:
                        routine: replace_matched
                        args:
                        - 'true': Company
                        - 'false': Private person
                    - object_field_set:
                        object: item
                        field: seller_type
                - find:
                    in: current
                    path: params
                    do:
                    - find:
                        path: name
                        do:
                        - parse
                        - space_dedupe
                        - trim
                        - variable_set: fieldname
                    - find:
                        path: value
                        do:
                        - parse
                        - space_dedupe
                        - trim
                        - object_field_set:
                            object: item
                            field: <%fieldname%>
                - find:
                    in: current
                    path: description
                    do:
                    - parse
                    - space_dedupe
                    - trim
                    - normalize:
                        routine: replace_substring
                        args:
                        - \&lt;br\s*\/\&gt;: ''
                        - <br\s*\/>: ''
                    - object_field_set:
                        object: item
                        field: description
                - find:
                    path: photos
                    slice: 0
                    do:
                    - parse:
                        filter: ^([^;]+)
                    - object_field_set:
                        object: item
                        field: image
                - register_set: ''
                - variable_get: token
                - if:
                    match: \w+
                    else:
                    - set_engine: selenium
                    - static_get: url
                    - walk:
                        to: value
                        do:
                        - find:
                            path: body
                            do:
                            - sleep: 5:10
                            - cookie_get: a_access_token
                            - variable_set: token
                    - set_engine: surf
                - sleep: 5:10
                - variable_set:
                    field: pr
                    value: "yes"
                - counter_set:
                    name: ptries
                    value: 0
                - walk:
                    to: https://www.olx.pl/api/v1/offers/<%id%>/phones/
                    repeat: <%pr%>
                    headers:
                        authorization: Bearer <%token%>
                        cache-control: 'no-cache'
                        pragma: 'no-cache'
                        sec-ch-ua: '" Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"'
                        sec-ch-ua-mobile: '?0'
                        sec-fetch-dest: empty
                        sec-fetch-mode: cors
                        sec-fetch-site: same-origin
                        version: 'v1.19'
                        x-client: DESKTOP
                        x-platform-type: mobile-html5
                    do:
                    - variable_clear: pr
                    - variable_clear: pf
                    - find:
                        path: data > phones
                        do:
                        - parse
                        - space_dedupe
                        - trim
                        - if:
                            match: \d+
                            do:
                            - object_field_set:
                                object: item
                                field: phone
                                joinby: ","
                            - variable_set:
                                field: pf
                                value: 1
                    - find:
                        path: error > detail
                        do:
                        - parse
                        - variable_set: err
                        - info: <%err%>
                        - variable_set:
                            field: pf
                            value: 1
                    - find:
                        path: data > phones
                        do:
                        - variable_get: pf
                        - if:
                            match: 1
                            else:
                            - info: empty phone
                            - counter_get: tries
                            - if:
                                gt: 5
                                type: int
                                do:
                                - error: cannot get phone number after 5 tries, aborting
                                - variable_set:
                                    field: pf
                                    value: 1
                                else:                                        
                                - counter_increment:
                                    name: ptries
                                    by: 1
                                - info: switching proxy and retrying
                                - info: current token <%token%>
                                - set_engine: selenium
                                - proxy_switch
                                - variable_get: url
                                - walk:
                                    to: value
                                    do:
                                    - find:
                                        path: body
                                        do:
                                        - sleep: 5:10
                                        - cookie_get: a_access_token
                                        - variable_set: token
                                - info: new token <%token%>
                                - variable_set:
                                    field: pr
                                    value: "yes"
                                - set_engine: surf
                                - variable_set:
                                    field: pf
                                    value: 1
                    - find:
                        path: html
                        do:
                        - variable_get: pf
                        - if:
                            match: 1
                            else:
                            - parse:
                                format: html
                            - variable_set: ht
                            - info: <%ht%>
                - object_save:
                    name: item
                - cookie_reset
    - find:
        path: body
        do:
        - variable_get: ok
        - if:
            match: 1
            do:
            - variable_clear: repeat
            else:
            - parse
            - if:
                match: To ogłoszenie nie jest już dostępne
                do:
                - info: item is not exist anymore, skipping
                - variable_clear: repeat
                else:
                - static_get: url
                - if:
                    match: '#from404'
                    do:
                    - info: item is not exist anymore, skipping
                    - variable_clear: repeat
                    else:
                    - error: Proxy is banned or page layout has been changed
                    - cookie_reset
                    - proxy_switch
