# olxpl digger
---
config:
    agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
    debug: 2
    js_enabled: "yes"
do:
- set_engine: surf
- variable_set:
    field: repeat
    value: "yes"
- walk:
    to: links
    repeat_in_pool: <%repeat%>
    do:
    - variable_clear: ok
    - find:
        path: script:contains("window.__PRERENDERED_STATE__")
        do:
        - parse
        - space_dedupe
        - trim
        - eval:
            routine: js
            body: (function () {var window = {}; <%register%>; return JSON.stringify(window.__PRERENDERED_STATE__);})();
        - normalize:
            routine: json2xml
        - to_block
        - find:
            path: body_safe
            do:
            - parse
            - normalize:
                routine: json2xml
            - to_block
            - find:
                path: body_safe > ad > ad
                do:
                - variable_clear: skipphone
                - variable_clear: id
                - variable_set:
                    field: ok
                    value: 1
                - object_new: item
                - static_get: url
                - variable_set: url
                - object_field_set:
                    object: item
                    field: url
                - find:
                    in: current
                    path: title
                    do:
                    - parse
                    - space_dedupe
                    - trim
                    - object_field_set:
                        object: item
                        field: title
                - find:
                    in: current
                    path: id
                    do:
                    - parse:
                        filter: (\d+)
                    - if:
                        match: \d+
                        do:
                        - object_field_set:
                            object: item
                            field: ad_id
                        - variable_set: id
                - find:
                    in: current
                    path: lastrefreshtime
                    do:
                    - parse
                    - space_dedupe
                    - trim
                    - object_field_set:
                        object: item
                        field: date
                - find:
                    path: contact > name
                    do:
                    - parse
                    - space_dedupe
                    - trim
                    - object_field_set:
                        object: item
                        field: seller
                - find:
                    path: contact > phone
                    do:
                    - parse
                    - space_dedupe
                    - trim
                    - if:
                        match: "false"
                        do:
                        - info: No phone available
                        - variable_set:
                            field: skipphone
                            value: 1
                - find:
                    path: protectphone
                    do:
                    - parse
                    - space_dedupe
                    - trim
                    - if:
                        match: "true"
                        do:
                        - info: Phone number is protected
                        - variable_set:
                            field: skipphone
                            value: 1
                - find:
                    path: location > pathname
                    do:
                    - parse
                    - space_dedupe
                    - trim
                    - object_field_set:
                        object: item
                        field: address
                - find:
                    path: price > regularprice > value
                    do:
                    - parse
                    - space_dedupe
                    - trim
                    - object_field_set:
                        object: item
                        field: price
                - find:
                    path: price > regularprice > currencycode
                    do:
                    - parse
                    - space_dedupe
                    - trim
                    - object_field_set:
                        object: item
                        field: currency
                - find:
                    path: isbusiness
                    do:
                    - parse
                    - space_dedupe
                    - trim
                    - normalize:
                        routine: replace_matched
                        args:
                        - 'true': Company
                        - 'false': Private person
                    - object_field_set:
                        object: item
                        field: seller_type
                - find:
                    in: current
                    path: params
                    do:
                    - find:
                        path: name
                        do:
                        - parse
                        - space_dedupe
                        - trim
                        - variable_set: fieldname
                    - find:
                        path: value
                        do:
                        - parse
                        - space_dedupe
                        - trim
                        - object_field_set:
                            object: item
                            field: <%fieldname%>
                - find:
                    in: current
                    path: description
                    do:
                    - parse
                    - space_dedupe
                    - trim
                    - normalize:
                        routine: replace_substring
                        args:
                        - \&lt;br\s*\/\&gt;: ''
                        - <br\s*\/>: ''
                    - object_field_set:
                        object: item
                        field: description
                - find:
                    path: photos
                    slice: 0
                    do:
                    - parse:
                        filter: ^([^;]+)
                    - object_field_set:
                        object: item
                        field: image
                - register_set: ''
                - variable_get: skipphone
                - if:
                    match: 1
                    do:
                    - info: Skipping phone extraction
                    else:
                    - set_engine: selenium
                    - variable_set:
                        field: rp
                        value: "yes"
                    - walk:
                        to: <%url%>
                        repeat: <%rp%>
                        do:
                        - find:
                            path: body
                            do:
                            - parse
                            - if:
                                match: 403 ERROR
                                do:
                                - info: Access denied, retrying
                                - proxy_switch
                                else:
                                - variable_set:
                                    field: rp
                                    value: "no"
                                - find:
                                    path: div.js-gtm-survey-close
                                    do:
                                    - click
                                - find:
                                    path: 'button[data-cy="dismiss-cookies-overlay"]'
                                    do:
                                    - click
                                - find:
                                    path: 'button#onetrust-accept-btn-handler'
                                    do:
                                    - click
                                - find:
                                    path: div[data-cy="ad-footer-bar-section"]
                                    do:
                                    - scrollto
                                - find:
                                    path: button[data-testid="show-phone"]
                                    do:
                                    - click
                                - sleep: 5:10
                                - find:
                                    path: a[data-testid="contact-phone"]
                                    do:
                                    - parse
                                    - space_dedupe
                                    - trim
                                    - object_field_set:
                                        object: item
                                        field: phone
                    - set_engine: surf
                - object_save:
                    name: item
                - cookie_reset
    - find:
        path: body
        do:
        - variable_get: ok
        - if:
            match: 1
            do:
            - variable_clear: repeat
            else:
            - parse
            - if:
                match: (To ogłoszenie nie jest już dostępne)|(Wygląda na to, że strona nie istnieje)
                do:
                - info: item is not exist anymore, skipping
                - variable_clear: repeat
                else:
                - static_get: url
                - if:
                    match: '#from404'
                    do:
                    - info: item is not exist anymore, skipping
                    - variable_clear: repeat
                    else:
                    - error: Proxy is banned or page layout has been changed
                    - cookie_reset
                    - proxy_switch
                    - variable_set:
                        field: repeat
                        value: "yes"
