#monastirevru digger
---
config:
    debug: 2
    agent: Firefox
do:
- variable_set: 
    field: crep
    value: "yes"
- counter_set: 
    name: catc
    value: 0
- walk:
    to: links
    repeat_in_pool: <%crep%>
    do:
    - cookie_reset
    - variable_clear: pageOk
    - variable_clear: crep
    - counter_increment:
        name: catc
    - find: 
        path: .pagination .pagination__link
        do: 
        - parse:
            attr: href
        - if:
            match: \S
            do:
            - normalize:
                routine: url
            - link_add
    - find: 
        path: .listing .offer__info > a
        do: 
        - variable_set: 
            field: pageOk
            value: 1
        - parse:
            attr: href
        - if:
            match: \S
            do:
            - normalize:
                routine: url
            - link_add:
                pool: catalog
    - find: 
        path: body 
        do: 
        - variable_get: pageOk
        - if:
            match: \S
            else:
            - counter_get: catc
            - if:
                gt: 4
                type: int
                do:
                - variable_clear: crep
                - counter_reset: catc
                - proxy_switch
                - info: cannot fetch url after 5 retries, skipping
                else:
                - variable_set: 
                    field: crep
                    value: "yes"
- variable_set: 
    field: crep
    value: "yes"
- counter_set: 
    name: catc
    value: 0
- walk:
    to: links
    repeat_in_pool: <%crep%>
    headers:
        x-requested-with: ''
    pool: catalog
    do:
    - cookie_reset
    - variable_clear: pageOk
    - variable_clear: crep
    - counter_increment:
        name: catc
    - find: 
        path: body 
        do:
        - find: 
            path: h1.product-page__name 
            do: 
            - variable_set:
                field: pageOk
                value: 1
            - find: 
                path: body
                in: doc
                do: 
                - object_new: item
                - static_get: url
                - object_field_set:
                    object: item
                    field: url
                - register_set: "yes"
                - object_field_set:
                    object: item
                    field: instock
                - find: 
                    path: h1.product-page__name 
                    do: 
                    - parse
                    - space_dedupe
                    - trim
                    - if:
                        match: \S
                        do:
                        - object_field_set:
                            object: item
                            field: title
                - find: 
                    path: 'div[id^=offer]' 
                    do: 
                    - parse:
                        attr: data-brand
                    - if:
                        match: \S
                        do:
                        - space_dedupe
                        - trim
                        - object_field_set:
                            object: item
                            field: brand
                    - register_set: ''
                    - parse:
                        attr: data-manufacturer
                    - if:
                        match: \S
                        do:
                        - space_dedupe
                        - trim
                        - object_field_set:
                            object: item
                            field: manufactorer
                    - register_set: ''
                    - parse:
                        attr: data-product-id
                    - if:
                        match: \S
                        do:
                        - space_dedupe
                        - trim
                        - object_field_set:
                            object: item
                            field: sku
                    - register_set: ''
                    - parse:
                        attr: data-available-quantity
                    - if:
                        match: \d
                        do:
                        - if:
                            gt: 0
                            type: int
                            else:
                            - register_set: 'no'
                            - object_field_set:
                                object: item
                                field: instock
                        else:
                        - register_set: 'no'
                        - object_field_set:
                            object: item
                            field: instock
                    - register_set: ''
                    - parse:
                        attr: data-price
                    - if:
                        match: \d
                        do:
                        - space_dedupe
                        - trim
                        - object_field_set:
                            object: item
                            field: price
                    - register_set: ''
                    - parse:
                        attr: data-image-url
                    - if:
                        match: \S
                        do:
                        - normalize:
                            routine: url
                        - object_field_set:
                            object: item
                            field: image
                    - register_set: ''
                    - parse:
                        attr: data-categories
                    - if:
                        match: \S
                        do:
                        - normalize:
                            routine: replace_substring
                            args:
                                - \/: ','
                        - object_field_set:
                            object: item
                            field: categories
                - find: 
                    path: .product-page__description .product-page__description-content 
                    slice: 0
                    do: 
                    - parse
                    - trim
                    - if:
                        match: \S
                        do:
                        - object_field_set:
                            object: item
                            field: description
                - variable_clear: commentsFound
                - find: 
                    path: 'input[id="comment_objectId"]' 
                    do: 
                    - parse:
                        attr: value
                    - if:
                        match: \d
                        do:
                        - walk:
                            to:
                                post: https://monastirev.ru/comment/list
                                headers:
                                    x-requested-with: XMLHttpRequest
                                data:
                                    objectId: <%register%>
                                    objectType: Товар
                            do:
                            - find: 
                                path: countHtml 
                                do: 
                                - parse
                                - to_block
                                - find: 
                                    path: span 
                                    do: 
                                    - parse:
                                        filter:
                                            - ^(\d+)
                                    - if:
                                        match: \d
                                        do:
                                        - variable_set: commentsFound
                                        - object_field_set:
                                            object: item
                                            field: total_reviews
                - variable_get: commentsFound
                - if:
                    match: \S
                    else:
                    - find: 
                        path: 'div[id^=offer]' 
                        do: 
                        - parse:
                            attr: data-product-id
                        - if:
                            match: \d
                            do:
                            - walk:
                                to:
                                    post: https://monastirev.ru/comment/list
                                    headers:
                                        x-requested-with: XMLHttpRequest
                                    data:
                                        objectId: <%register%>
                                        objectType: Товар
                                do:
                                - find: 
                                    path: countHtml 
                                    do: 
                                    - parse
                                    - to_block
                                    - find: 
                                        path: span 
                                        do: 
                                        - parse:
                                            filter:
                                                - ^(\d+)
                                        - if:
                                            match: \d
                                            do:
                                            - variable_set: commentsFound
                                            - object_field_set:
                                                object: item
                                                field: total_reviews
                - object_save:
                    name: item
                        
    - find: 
        path: body 
        do: 
        - variable_get: pageOk
        - if:
            match: \S
            else:
            - counter_get: catc
            - if:
                gt: 4
                type: int
                do:
                - variable_clear: crep
                - counter_reset: catc
                - proxy_switch
                - info: cannot fetch url after 5 retries, skipping
                else:
                - variable_set: 
                    field: crep
                    value: "yes"