---
config:
    debug: 2
    agent: Firefox
do:
- walk:
    to: https://www.farfetch.com/
    do:
    - find:
        path: ul.ff-primary-nav>li.ff-has-children>ul.ff-secondary-nav>li>ul.ff-nav-ul>li>a.ff-nav-a
        do:
        - parse:
            attr: href
            filter: ^([^\?]+)
        - space_dedupe
        - trim
        - if:
            match: \w+
            do:
            - normalize:
                routine: url
            - link_add:
                pool: catalog
- walk:
    to: links
    pool: catalog
    do:
    - find:
        path: span[data-tstid="paginationTotal"]
        slice: 0
        do:
        - parse:
            filter: (\d+)
        - if:
            match: \d+
            do:
            - variable_set: total
            - static_get: url
            - if:
                match: \?+
                else:
                - variable_set: url
                - eval:
                    routine: js
                    body: (function(){var t = <%total%>;var offset = [];for(var i = 2; i < t; i++){offset.push(i)}; return offset.join(",");})();
                - to_block
                - split:
                    context: text
                    delimiter: ","
                - find:
                    path: div
                    do:
                    - parse
                    - if:
                        match: \d+
                        do:
                        - variable_set: page
                        - register_set: "<%url%>?page=<%page%>"
                        - link_add:
                            pool: catalog
    - find:
        path: a.listing-item-link[itemprop="url"]
        do:
        - parse:
            attr: href
            filter: ^([^\?]+)
        - space_dedupe
        - trim
        - if:
            match: \w+
            do:
            - normalize:
                routine: url
            - link_add:
                pool: pages
- walk:
    to: links
    pool: pages
    do:
    - sleep: 2
    - find:
        path: 'div#PDPContainer'
        do:
        - variable_clear: desc
        - object_new: product
        - eval:
            routine: js
            body: '(function (){var d = new Date(); return d.toISOString()})();'
        - object_field_set:
            object: product
            field: date
        - static_get: url
        - object_field_set:
            object: product
            field: url
        - find:
            path: span[itemprop="name"]
            do:
            - parse
            - space_dedupe
            - trim
            - object_field_set:
                object: product
                field: name
        - find:
            path: a[itemprop="brand"]
            do:
            - parse
            - space_dedupe
            - trim
            - object_field_set:
                object: product
                field: brand
        - find:
            path: span[itemprop="sku"]
            do:
            - parse
            - space_dedupe
            - trim
            - if:
                match: \w+
                do:
                - object_field_set:
                    object: product
                    field: sku
        - find:
            in: doc
            path: meta[name="description"]
            do:
            - parse:
                attr: content
            - space_dedupe
            - trim
            - variable_set: desc
        - find:
            path: p[itemprop="description"]
            do:
            - parse
            - space_dedupe
            - trim
            - variable_set: desc
        - find:
            path: span[itemprop="color"]
            do:
            - parse
            - space_dedupe
            - trim
            - if:
                match: \s*[A-Za-z]+
                do:
                - object_field_set:
                    object: product
                    joinby: "|"
                    field: variations
        - variable_get: desc
        - object_field_set:
            object: product
            field: description
        - find:
            path: img.responsive[itemprop="image"]
            do:
            - parse:
                attr: data-zoom-image
            - space_dedupe
            - trim
            - if:
                match: \w+
                do:
                - normalize:
                    routine: url
                - object_field_set:
                    object: product
                    joinby: "|"
                    field: images
        - find:
            in: doc
            path: script:contains('window.universal_variable.product')
            do:
            - parse:
                filter: window\.universal_variable\.product\s+\=\s+(.+)\;
            - normalize:
                routine: json2xml
            - to_block
            - find:
                path: body_safe>gender,body_safe>department,body_safe>category,body_safe>subcategory
                do:
                - parse
                - space_dedupe
                - trim
                - if:
                    match: \w+
                    do:
                    - object_field_set:
                        object: product
                        joinby: "|"
                        field: categories
            - find:
                path: body_safe>currencycode
                do:
                - parse
                - space_dedupe
                - trim
                - if:
                    match: \w+
                    do:
                    - object_field_set:
                        object: product
                        field: currency
            - find:
                path: body_safe>unitprice
                do:
                - parse
                - space_dedupe
                - trim
                - if:
                    match: \d+
                    do:
                    - object_field_set:
                        object: product
                        type: float
                        field: price
            - find:
                path: body_safe>unitsaleprice
                do:
                - parse
                - space_dedupe
                - trim
                - if:
                    match: \d+
                    do:
                    - object_field_set:
                        object: product
                        type: float
                        field: price
        - object_save:
            name: product
