#avitoru digger
---
config:
    debug: 2
    agent: "Mozilla/5.0 (Linux; Android 5.0; SM-G900P Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Mobile Safari/537.36"
do:
- variable_set:
    field: rip
    value: "yes"
- walk:
    to: https://m.avito.ru
    repeat: <%rip%>
    do:
    - variable_clear: key
    - variable_clear: sp
    - variable_clear: laststamp
    - find:
        path: script
        do:
        - variable_get: key
        - if:
            match: \S
            else:
            - parse:
                attr: src
            - if:
                match: mstatic\/build
                do:
                - set_converter:
                    content_type: application/javascript
                    converter: image
                - walk:
                    to: value
                    do:
                    - variable_clear: filt
                    - find: 
                        path: imgbase64
                        do: 
                        - parse
                        - normalize:
                            routine: Base64Decode
                        - filter: 
                            args:
                                - params\:\s*\{\s*key\:\s*\"?([A-Za-z0-9\$]+)\"?\s*\}\,data
                        - normalize:
                            routine: replace_substring
                            args:
                                \$: '\$'
                        - variable_set: filt
                        - parse
                        - normalize:
                            routine: Base64Decode
                        - filter:
                            args:
                            - \,\s*<%filt%>\s*\=\s*\"([a-z0-9]+)\"\;
                            - var\s*<%filt%>\s*\=\s*\"([a-z0-9]+)\"
                        - if:
                            match: \S
                            do:
                            - variable_set: key
                - clear_converter:
                    content_type: application/javascript
    - find:
        path: html
        do:
        - variable_get: key
        - if:
            match: \w+
            do:
            - variable_set:
                field: rip
                value: "no"
            - variable_set:
                field: repeat2
                value: "yes"
            - walk:
                to: links
                repeat_in_pool: <%repeat2%>
                do:
                - sleep: 3
                - find:
                    path: 'div#app'
                    do:
                    - variable_set:
                        field: repeat2
                        value: "no"
                    - object_new: item
                    - static_get: url
                    - object_field_set:
                        object: item
                        field: url
                    - find: 
                        path: script:matches(window\.\_\_initialData\_\_\s*\=) 
                        in: doc
                        do: 
                        - parse
                        - eval:
                            routine: js
                            body: (function () {var window = {}; <%register%>;if (typeof window.__initialData__ === 'string' || window.__initialData__ instanceof String) {return JSON.stringify(JSON.parse(window.__initialData__));} else {return JSON.stringify(window.__initialData__);};})();
                        - normalize:
                            routine: json2xml
                        - toblock
                        - find: 
                            path: body_safe 
                            do: 
                            - find: 
                                path: list:hasChild(type:matches(phone)) > value > uri
                                do: 
                                - parse:
                                    filter: 
                                        - number\=(.+)\s*$
                                - if:
                                    match: \d
                                    do:
                                    - normalize:
                                        routine: URLDecode
                                    - object_field_set:
                                        object: item
                                        field: phone

                            - find: 
                                path: 'images > safe_640x480'
                                do: 
                                - parse
                                - if:
                                    match: \S
                                    do:
                                    - object_field_set:
                                        object: item
                                        field: image
                                        joinby: "|"
                            - find: 
                                path: coords 
                                do: 
                                - find: 
                                    path: lat
                                    do: 
                                    - parse
                                    - if:
                                        match: \S
                                        do:
                                        - object_field_set:
                                            object: item
                                            field: lat
                                            type: float
                                - find: 
                                    path: lng 
                                    do: 
                                    - parse
                                    - if:
                                        match: \S
                                        do:
                                        - object_field_set:
                                            object: item
                                            field: lng
                                            type: float
                            - find: 
                                path: item > id
                                do: 
                                - parse:
                                    filter: (\d+)
                                - space_dedupe
                                - trim
                                - object_field_set:
                                    object: item
                                    field: id
                                - walk:
                                    to: https://m.avito.ru/api/1/items/<%register%>/phone?key=<%key%>
                                    do:
                                    - find: 
                                        path: uri 
                                        do: 
                                        - parse:
                                            filter:
                                                - number\=([^?]+)
                                        - if:
                                            match: \d
                                            do:
                                            - normalize:
                                                routine: URLDecode
                                            - object_field_set:
                                                object: item
                                                field: phone
                                            
                            - find: 
                                path: item > time
                                do: 
                                - parse:
                                    filter: (\d+)
                                - if:
                                    match: \d+
                                    do:
                                    - normalize:
                                        routine: date_format
                                        args:
                                            format_in: "%s"
                                            format_out: "%Y-%m-%d %T"
                                    - object_field_set:
                                        object: item
                                        field: actualized
                            - find: 
                                path: item > stats > views > total
                                do: 
                                - parse:
                                    filter: (\d+)
                                - if:
                                    match: \d+
                                    do:
                                    - object_field_set:
                                        object: item
                                        field: views_total
                            - find: 
                                path: item > stats > views > today
                                do: 
                                - parse:
                                    filter: (\d+)
                                - if:
                                    match: \d+
                                    do:
                                    - object_field_set:
                                        object: item
                                        field: views_today
                    - find:
                        path: 'h1[itemprop="name"]'
                        in: doc
                        do:
                        - parse
                        - space_dedupe
                        - trim
                        - object_field_set:
                            object: item
                            field: title
                    - find:
                        path: 'meta[itemprop="priceCurrency"]'
                        do:
                        - parse:
                            attr: content
                        - object_field_set:
                            object: item
                            field: currency
                    - find: 
                        path: 'meta[itemprop="price"]' 
                        do: 
                        - parse:
                            attr: content
                        - object_field_set:
                            object: item
                            field: price
                    - find:
                        path: 'meta[itemprop="description"]'
                        do:
                        - parse:
                            attr: content
                        - space_dedupe
                        - trim
                        - object_field_set:
                            object: item
                            field: description
                    - find:
                        path: 'span[data-marker="delivery/location"]'
                        do:
                        - parse
                        - space_dedupe
                        - trim
                        - object_field_set:
                            object: item
                            field: address

                    - find:
                        path: 'span[data-marker="seller-info/name"]'
                        do:
                        - parse
                        - space_dedupe
                        - trim
                        - object_field_set:
                            object: item
                            field: seller
                    - object_save:
                        name: item
                - find:
                    path: body
                    do:
                    - variable_get: repeat2
                    - if:
                        match: "yes"
                        do:
                        - error: Page changed layout or proxy is banned, retrying
                        - proxy_switch
                        - cookie_reset
            else:
            - error: No key found, probably proxy is banned, retrying
            - variable_set:
                field: rip
                value: "yes"
            - proxy_switch
            - cookie_reset
