#avitoru digger
---
config:
    debug: 2
    agent: "Mozilla/5.0 (Linux; Android 5.0; SM-G900P Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Mobile Safari/537.36"
    ssl:
        version: TLSv1.2
        cipher: ECDHE ECDSA AES 256 GCM SHA384
    proxy:
        type: residential
do:
- variable_set:
    field: collectPhone
    value: "yes"
- variable_set:
    field: rip
    value: "yes"
- walk:
    to: https://m.avito.ru
    repeat: <%rip%>
    do:
    - variable_clear: key
    - variable_clear: sp
    - variable_clear: laststamp
    - find:
        path: script
        do:
        - variable_get: key
        - if:
            match: \S
            else:
            - parse:
                attr: src
            - if:
                match: mstatic\/build
                do:
                - set_converter:
                    content_type: application/javascript
                    converter: image
                - walk:
                    to: value
                    do:
                    - variable_clear: filt
                    - find: 
                        path: imgbase64
                        do: 
                        - parse
                        - normalize:
                            routine: Base64Decode
                        - filter: 
                            args:
                            - params\:\s*\{\s*key\:\s*\"?([A-Za-z0-9\$]+)\"?\s*\}\,data
                        - normalize:
                            routine: replace_substring
                            args:
                                \$: '\$'
                        - variable_set: filt
                        - parse
                        - normalize:
                            routine: Base64Decode
                        - filter:
                            args:
                            - <%filt%>\s*\=\s*\"([a-z0-9]{44})\"
                        - if:
                            match: \S
                            do:
                            - variable_set: key
                - clear_converter:
                    content_type: application/javascript
    - find:
        path: html
        do:
        - variable_get: key
        - if:
            match: \w+
            do:
            - variable_set:
                field: rip
                value: "no"
            - variable_set:
                field: repeat2
                value: "yes"
            - walk:
                to: links
                repeat_in_pool: <%repeat2%>
                do:
                - sleep: 3
                - find:
                    path: a[data-marker="full-version"]
                    do:
                    - parse:
                        attr: href
                        filter: (\d+)\?
                    - if:
                        match: \d+
                        else:
                        - error: Cannot find product id, layout is changed
                        - exit
                        do:
                        - variable_set: pid
                        - variable_set:
                            field: repeat2
                            value: "no"
                        - object_new: item
                        - static_get: url
                        - object_field_set:
                            object: item
                            field: url
                        - walk:
                            to: https://m.avito.ru/api/17/items/<%pid%>?key=<%key%>&action=view
                            do:
                            - find: 
                                path: 'images > safe_640x480'
                                do: 
                                - parse
                                - if:
                                    match: \S
                                    do:
                                    - object_field_set:
                                        object: item
                                        field: image
                                        joinby: "|"
                            - find: 
                                path: coords 
                                do: 
                                - find: 
                                    path: lat
                                    do: 
                                    - parse
                                    - if:
                                        match: \S
                                        do:
                                        - object_field_set:
                                            object: item
                                            field: lat
                                            type: float
                                - find: 
                                    path: lng 
                                    do: 
                                    - parse
                                    - if:
                                        match: \S
                                        do:
                                        - object_field_set:
                                            object: item
                                            field: lng
                                            type: float
                            - find: 
                                path: body_safe > body_safe > id
                                do: 
                                - parse:
                                    filter: (\d+)
                                - space_dedupe
                                - trim
                                - object_field_set:
                                    object: item
                                    field: id
                                - variable_set: itemid
                                - variable_get: collectPhone
                                - variable_set: pr
                                - walk:
                                    to: https://m.avito.ru/api/1/items/<%itemid%>/phone?key=<%key%>
                                    repeat: <%pr%>
                                    do:
                                    - find:
                                        path: html
                                        do:
                                        - parse:
                                            format: html
                                        - if:
                                            match: HTTP 502
                                            do:
                                            - info: Proxy is banned (502), switching
                                            - proxy_switch
                                            - cookie_reset
                                            - variable_set:
                                                field: pr
                                                value: "yes"
                                            else:
                                            - if:
                                                match: '\&\#34\;\:'
                                                do:
                                                - parse
                                                - normalize:
                                                    routine: json2xml
                                                - to_block
                                                - variable_clear: code
                                                - find:
                                                    path: code
                                                    do:
                                                    - parse
                                                    - variable_set: code
                                                - variable_get: code
                                                - if:
                                                    match: 403
                                                    do:
                                                    - info: Proxy is banned, switching
                                                    - proxy_switch
                                                    - cookie_reset
                                                    - variable_set:
                                                        field: pr
                                                        value: "yes"
                                                    else:
                                                    - find: 
                                                        path: message
                                                        do: 
                                                        - parse
                                                        - info: <%register%>
                                                        - variable_set:
                                                            field: pr
                                                            value: "no"
                                                    - find: 
                                                        path: uri 
                                                        do: 
                                                        - variable_set:
                                                            field: pr
                                                            value: "no"
                                                        - parse:
                                                            filter:
                                                                - number\=([^?]+)
                                                        - if:
                                                            match: \d
                                                            do:
                                                            - normalize:
                                                                routine: URLDecode
                                                            - object_field_set:
                                                                object: item
                                                                field: phone
                                                            else:
                                                            - parse
                                                            - if:
                                                                match: authenticate
                                                                do:
                                                                - info: You need to login to see this phone number
                                                else:
                                                - variable_clear: code
                                                - find:
                                                    path: code
                                                    do:
                                                    - parse
                                                    - variable_set: code
                                                - variable_get: code
                                                - if:
                                                    match: 403
                                                    do:
                                                    - info: Proxy is banned, switching
                                                    - proxy_switch
                                                    - cookie_reset
                                                    - variable_set:
                                                        field: pr
                                                        value: "yes"
                                                    else:
                                                    - find: 
                                                        path: message
                                                        do: 
                                                        - parse
                                                        - info: <%register%>
                                                        - variable_set:
                                                            field: pr
                                                            value: "no"
                                                    - find: 
                                                        path: uri 
                                                        do: 
                                                        - variable_set:
                                                            field: pr
                                                            value: "no"
                                                        - parse:
                                                            filter:
                                                                - number\=([^?]+)
                                                        - if:
                                                            match: \d
                                                            do:
                                                            - normalize:
                                                                routine: URLDecode
                                                            - object_field_set:
                                                                object: item
                                                                field: phone
                                                            else:
                                                            - parse
                                                            - if:
                                                                match: authenticate
                                                                do:
                                                                - info: You need to login to see this phone number
                            - find: 
                                path: body_safe > body_safe > time
                                do: 
                                - parse:
                                    filter: (\d+)
                                - if:
                                    match: \d+
                                    do:
                                    - normalize:
                                        routine: date_format
                                        args:
                                            format_in: "%s"
                                            format_out: "%Y-%m-%d %T"
                                    - object_field_set:
                                        object: item
                                        field: actualized
                            - find: 
                                path: body_safe > body_safe > stats > views > total
                                do: 
                                - parse:
                                    filter: (\d+)
                                - if:
                                    match: \d+
                                    do:
                                    - object_field_set:
                                        object: item
                                        field: views_total
                            - find: 
                                path: body_safe > body_safe > stats > views > today
                                do: 
                                - parse:
                                    filter: (\d+)
                                - if:
                                    match: \d+
                                    do:
                                    - object_field_set:
                                        object: item
                                        field: views_today
                            - find:
                                path: body_safe > body_safe > description
                                do:
                                - parse
                                - space_dedupe
                                - trim
                                - object_field_set:
                                    object: item
                                    field: description
                            - find:
                                path: body_safe > body_safe > title
                                do:
                                - parse
                                - space_dedupe
                                - trim
                                - object_field_set:
                                    object: item
                                    field: title
                            - find:
                                path: body_safe > body_safe > price > metric
                                do:
                                - parse
                                - space_dedupe
                                - trim
                                - object_field_set:
                                    object: item
                                    field: currency
                            - find:
                                path: body_safe > body_safe > price > value
                                do:
                                - parse
                                - space_dedupe
                                - trim
                                - object_field_set:
                                    object: item
                                    field: price
                            - find:
                                path: body_safe > body_safe > address
                                do:
                                - parse
                                - space_dedupe
                                - trim
                                - object_field_set:
                                    object: item
                                    field: address
                            - find:
                                path: body_safe > body_safe > seller > name
                                do:
                                - parse
                                - space_dedupe
                                - trim
                                - object_field_set:
                                    object: item
                                    field: seller
                        - object_save:
                            name: item
                - find:
                    path: body
                    do:
                    - variable_get: repeat2
                    - if:
                        match: "yes"
                        do:
                        - error: Page changed layout or proxy is banned, retrying
                        - proxy_switch
                        - cookie_reset
            else:
            - error: No key found, probably proxy is banned, retrying
            - variable_set:
                field: rip
                value: "yes"
            - proxy_switch
            - cookie_reset
