---
config:
    debug: 2
    agent: Firefox
do:
- walk:
    to: http://shop.diesel.com/
    do:
    - find:
        path: ul.level-1>li,ul.level-2>li,ul.level-3>li,ul.level-4>li
        do:
        - find:
            path: a:not(.actual-stories-link)
            slice: 0
            do:
            - parse:
                attr: href
            - space_dedupe
            - trim
            - normalize:
                routine: replace_matched
                args:
                    javascript\:: ''
                    ^\#$: ''
            - if:
                match: \s*[a-z]+
                do:
                - normalize:
                    routine: url
                - link_add:
                    pool: catalog
- walk:
    to: links
    pool: catalog
    do:
    - find:
        path: 'input#TotalProductCountOnLoad'
        do:
        - parse:
            attr: value
        - space_dedupe
        - trim
        - if:
            match: ^\d+$
            do:
            - variable_set: records
            - static_get: url
            - variable_set: url
            - eval:
                routine: js
                body: (function () {var pages = []; var i = 0; for (i=0; i <= <%records%>; i+=55) {pages.push(i)}; pages.push(i+55);  return pages.join(",");})();
            - to_block
            - split:
                context: text
                delimiter: ","
            - find: 
                path: .splitted 
                do: 
                - parse
                - variable_set: start
                - register_set: <%url%>&?sz=55&start=<%start%>&format=page-element
                - walk:
                    to: value
                    do:
                    - find:
                        path: a.name-link
                        do:
                        - parse:
                            attr: href
                            filter: ^([^\?]+)
                        - space_dedupe
                        - trim
                        - normalize:
                            routine: replace_matched
                            args:
                                javascript\:: ''
                                ^\#$: ''
                        - if:
                            match: \s*[a-z]+
                            do:
                            - normalize:
                                routine: url
                            - link_add:
                                pool: pages
- walk:
    to: links
    pool: pages
    do:
    - sleep: 2
    - find:
        path: 'div#pdpMain'
        do:
        - variable_clear: desc
        - variable_clear: pid
        - variable_clear: cid
        - variable_clear: key
        - object_new: product
        - eval:
            routine: js
            body: '(function (){var d = new Date(); return d.toISOString()})();'
        - object_field_set:
            object: product
            field: date
        - static_get: url
        - object_field_set:
            object: product
            field: url
        - find:
            path: h2.product-name
            do:
            - parse
            - space_dedupe
            - trim
            - object_field_set:
                object: product
                field: name
        - register_set: Diesel
        - object_field_set:
            object: product
            field: brand
        - find:
            path: div.product-content-header>h6
            do:
            - parse:
                filter: ^ID\:(.+)
            - space_dedupe
            - trim
            - if:
                match: \w+
                do:
                - variable_set: pid
                - object_field_set:
                    object: product
                    field: sku
        - find:
            in: doc
            path: meta[name="description"]
            do:
            - parse:
                attr: content
            - space_dedupe
            - trim
            - variable_set: desc
        - find:
            path: ul.discription-list-inner
            slice: 0
            do:
            - find:
                path: li.bullet-list-none
                do:
                - parse
                - space_dedupe
                - trim
                - variable_set: desc
        - variable_get: desc
        - object_field_set:
            object: product
            field: description
        - find:
            path: ul.Color>li>a
            do:
            - parse:
                attr: title
            - space_dedupe
            - trim
            - if:
                match: \w+
                do:
                - object_field_set:
                    object: product
                    joinby: "|"
                    field: variations
            - parse:
                attr: href
            - space_dedupe
            - trim
            - if:
                match: \w+
                do:
                - walk:
                    to: value
                    do:
                    - find:
                        path: ul.product-slides-list1>li>a
                        do:
                        - parse:
                            attr: data-href
                        - space_dedupe
                        - trim
                        - if:
                            match: \w+
                            do:
                            - object_field_set:
                                object: product
                                joinby: "|"
                                field: images
        - find:
            path: div.product-content-header>div.product-price>span.price-sales:contains('$'),div.product-content-header>div.product-price>span.price-final-value:contains('$')
            do:
            - parse:
                filter:
                - \$([0-9\.\,]+)\s*-
                - \$([0-9\.\,]+)
            - normalize:
                routine: replace_substring
                args:
                    \,: ''
            - space_dedupe
            - trim
            - object_field_set:
                object: product
                type: float
                field: price
            - parse
            - normalize:
                routine: replace_matched
                args:
                    \$: USD
            - object_field_set:
                object: product
                field: currency
        - find:
            path: ol.breadcrumb>li>h4>a
            slice: 1:-1
            do:
            - parse
            - space_dedupe
            - trim
            - if:
                match: \w+
                do:
                - object_field_set:
                    object: product
                    joinby: "|"
                    field: categories
        - find:
            path: div.product-content-header>h5
            do:
            - parse
            - space_dedupe
            - trim
            - if:
                match: \w+
                do:
                - object_field_set:
                    object: product
                    joinby: "|"
                    field: categories
        - find:
            path: ul.product-slides-list1>li>a
            do:
            - parse:
                attr: data-href
            - space_dedupe
            - trim
            - if:
                match: \w+
                do:
                - object_field_set:
                    object: product
                    unique: yes
                    field: images
        - object_save:
            name: product
