---
config:
    debug: 2
    agent: Firefox
do:
- walk:
    to: https://www.jaanuu.com/
    do:
    - find: 
        path: .categories a 
        do: 
        - parse:
            attr: href
        - normalize:
            routine: url
        - walk:
            to: value
            do:
            - find: 
                path: script:matches(jaanuu\.product_data)
                do: 
                - parse
                - eval:
                    routine: js
                    body: (function () {
                            var jaanuu = {};
                            <%register%>;
                            return JSON.stringify(jaanuu.product_data);
                        })();
                - normalize:
                    routine: json2xml
                - to_block
                - find:
                    path: body_safe
                    do:
                    - find: 
                        path: product_colors path 
                        do: 
                        - parse
                        - register_set: 'https://www.jaanuu.com<%register%>'
                        - link_add
- walk:
    to: links
    do:
    - object_new: product
    - variable_clear: descr
    - variable_clear: sku
    - find: 
        in: doc
        path: head 
        do: 
        - eval:
            routine: js
            body: '(function (){var d = new Date(); return d.toISOString()})();'
        - object_field_set:
            object: product
            field: date
        - static_get: url
        - object_field_set:
            object: product
            field: url
    - find: 
        path: script[type="application/ld+json"] 
        do: 
        - parse
        - space_dedupe
        - trim
        - normalize:
            routine: json2xml
        - to_block
        - find: 
            path: brand name 
            do: 
            - parse
            - space_dedupe
            - trim
            - object_field_set:
                object: product
                field: brand
    - find: 
        path: script:matches(pdData) 
        do: 
        - parse
        - eval:
            routine: js
            body: (function () {
                    function loadProductDetail(){};
                    <%register%>
                    return JSON.stringify(pdData)
                })();
        - normalize:
            routine: json2xml
        - to_block
        - find: 
            path: body_safe 
            do: 
            - find: 
                path: product_colors > color > name 
                do: 
                - parse
                - space_dedupe
                - trim
                - if:
                    match: \S
                    do:
                    - object_field_set:
                        object: product
                        field: variations
                        joinby: "|"
            - find: 
                path: product_colors > images > url
                do: 
                - parse
                - space_dedupe
                - trim
                - if:
                    match: \S
                    do:
                    - object_field_set:
                        object: product
                        field: images
                        joinby: "|"

            - find: 
                path: selected_sku 
                do: 
                - parse
                - space_dedupe
                - trim
                - variable_set: sku
                - if:
                    match: \S
                    do:
                    - object_field_set:
                        object: product
                        field: sku
            - find: 
                path: product > product_colors:has(product_details:has(sku:matches(<%sku%>)))
                do: 
                - find: 
                    path: display_name
                    do: 
                    - parse
                    - space_dedupe
                    - trim
                    - object_field_set:
                        object: product
                        field: name
                - find: 
                    path: current_price
                    slice: 0
                    do: 
                    - parse
                    - space_dedupe
                    - trim
                    - if:
                        match: \d
                        do:
                        - eval:
                            routine: js
                            body: (function () {return <%register%>/100;})();
                        - object_field_set:
                            object: product
                            field: price
                            type: float
                        - register_set: USD
                        - object_field_set:
                            object: product
                            field: currency
            - find: 
                path: product > description 
                do: 
                - parse
                - space_dedupe
                - trim
                - object_field_set:
                    object: product
                    field: description
            - find: 
                path: product > category > name
                do: 
                - parse
                - space_dedupe
                - trim
                - object_field_set:
                    object: product
                    field: categories
                    joinby: "|"
    - object_save:
        name: product
