---
config:
    debug: 2
    agent: Firefox
do:
- walk:
    to: http://www.debshops.com
    do:
    - find:
        path: a.topmenulink
        do:
        - parse:
            attr: href
        - space_dedupe
        - trim
        - if:
            match: \/category\/
            do:
            - normalize:
                routine: url
        - register_set: <%register%>/1/
        - link_add:
            pool: catalog
- walk:
    to: links
    pool: catalog
    do:
    - find:
        path: div.pull-right>table
        slice: 0
        do:
        - find:
            path: td>a
            do:
            - parse:
                attr: href
            - if:
                match: \d+
                do:
                - link_add:
                    pool: catalog
    - find:
        path: div.prdImg>a.imgList
        do:
        - parse:
            attr: href
        - normalize:
            routine: replace_substring
            args:
                _\d+$: ''
        - link_add:
            pool: pages
- walk:
    to: links
    headers:
        referer: ''
    pool: pages
    do:
    - sleep: 3
    - find:
        path: 'div#center'
        do:
        - variable_clear: pid
        - object_new: product
        - eval:
            routine: js
            body: '(function (){var d = new Date(); return d.toISOString()})();'
        - object_field_set:
            object: product
            field: date
        - static_get: url
        - object_field_set:
            object: product
            field: url
        - find:
            path: span.price
            do:
            - parse:
                filter: ([0-9\.]+)
            - object_field_set:
                object: product
                type: float
                field: price
            - parse
            - normalize:
                routine: replace_matched
                args:
                    \$: USD
            - object_field_set:
                object: product
                field: currency
        - find:
            path: div.productstyleNew.visible-xs
            do:
            - parse:
                filter: (\d+)
            - variable_set: pid
            - object_field_set:
                object: product
                field: sku
        - find:
            path: div.productnameNew.visible-xs
            do:
            - parse
            - normalize:
                routine: replace_substring
                args:
                - \s*[[:space:]]+: ' '
                - ^\s+|\s+$: ''
            - object_field_set:
                object: product
                field: name
        - find:
            path: 'div#tab-description'
            do:
            - split:
                context: html
                delimiter: <br/>
            - find:
                path: div.splitted
                slice: 0
                do:
                - parse
                - normalize:
                    routine: replace_substring
                    args:
                    - \s*[[:space:]]+: ' '
                    - ^\s+|\s+$: ''
                - object_field_set:
                    object: product
                    field: description
        - find:
            path: ol.breadcrumb>li.active>a
            do:
            - parse
            - normalize:
                routine: replace_substring
                args:
                - \s*[[:space:]]+: ' '
                - ^\s+|\s+$: ''
            - object_field_set:
                object: product
                joinby: "|"
                field: categories
        - walk:
            to:
                json: http://www.debshops.com/Products/ProductDetail.aspx/GetColors
                data:
                    StyleId: <%pid%>
            do:
            - find:
                path: d
                do:
                - parse
                - to_block
                - find:
                    path: img.colorthumb
                    do:
                    - parse:
                        attr: alt
                    - normalize:
                        routine: replace_substring
                        args:
                        - \s*[[:space:]]+: ' '
                        - ^\s+|\s+$: ''
                    - if:
                        match: \w+
                        do:
                        - object_field_set:
                            object: product
                            joinby: "|"
                            field: variations
                    - parse:
                        attr: id
                    - variable_set: cid
                    - walk:
                        to:
                            json: http://www.debshops.com/Products/ProductDetail.aspx/GetImages
                            data:
                                Color_Id: <%cid%>
                        do:
                        - find:
                            path: d
                            do:
                            - parse
                            - to_block
                            - find:
                                path: img.productdetail_image_display
                                do:
                                - parse:
                                    attr: data-zoom-image
                                - object_field_set:
                                    object: product
                                    joinby: "|"
                                    field: images
        - register_set: Debshops
        - object_field_set:
            object: product
            field: brand
        - object_save:
            name: product
