---
config:
    debug: 2
    agent: Firefox
do:
- walk:
    to: http://www.ikea.com/us/en/
    do:
    - find: 
        path: .departmentLinkBlock a 
        do: 
        - parse:
            attr: href
        - normalize:
            routine: url
        - link_add:
            pool: main
- walk:
    to: links
    pool: main
    do:
    - find: 
        path: .visualNavContainer > a 
        do: 
        - parse:
            attr: href
        - link_add:
            pool: main
        
    - find: 
        path: .product > .image > a 
        do: 
        - parse:
            attr: href
        - link_add:
            pool: products
- walk:
    to: links
    pool: products
    do:
    - variable_clear: reg
    - object_new: product
    - find:
        path: head
        do:
        - eval:
            routine: js
            body: '(function (){var d = new Date(); return d.toISOString()})();'
        - object_field_set:
            object: product
            field: date
        - static_get: url
        - object_field_set:
            object: product
            field: url
        - find:
            path: meta[name="description"]
            do:
            - parse:
                attr: content
            - object_field_set:
                object: product
                field: description
        - register_set: Ikea
        - object_field_set:
            object: product
            field: brand
    - find: 
        path: '#breadCrumbs > li a' 
        slice: 1:-1
        do: 
        - parse
        - space_dedupe
        - trim
        - normalize:
            routine: lower
        - if:
            match: \S
            do:
            - object_field_set:
                object: product
                field: categories
                joinby: '|'
    - find: 
        path: .productName 
        do: 
        - parse
        - space_dedupe
        - trim
        - if:
            match: \S
            do:
            - object_field_set:
                object: product
                field: name
            
    - find: 
        path: '#price1' 
        do: 
        - parse:
            filter:
                - (\d+\.\d+)
        - if:
            match: \d
            do:
            - object_field_set:
                object: product
                field: price
                type: float
            - register_set: USD
            - object_field_set:
                object: product
                field: currency
    - find: 
        path: '#salesArg t' 
        do: 
        - node_remove: a
        - parse
        - space_dedupe
        - trim
        - if:
            match: \S
            do:
            - object_field_set:
                object: product
                field: description
    - find: 
        path: .prodDropdown > select > option 
        do: 
        - parse
        - space_dedupe
        - trim
        - if:
            match: \S
            do:
            - object_field_set:
                object: product
                field: variations
                joinby: '|'
    - find: 
        path: '#itemNumber' 
        do: 
        - parse
        - space_dedupe
        - trim
        - if:
            match: \S
            do:
            - object_field_set:
                object: product
                field: sku
    - find: 
        path: script:matches(jProductData) 
        do: 
        - parse
        - normalize:
            routine: replace_substring
            args:
                - uniqueUrl\.updateProductMetaTag\(\)\;: ''
                - var\s*itemRelationValue\s*=\s*irwstatGetTrailingTagValue\(\'IRWStats\.productFindingMethod\'\)\;: ''
        - variable_set: reg
        - eval:
            routine: js
            body: (function () {<%reg%> return JSON.stringify(jProductData)})();
        - normalize:
            routine: json2xml
        - to_block
        - find: 
            path: body_safe 
            do: 
            - find: 
                path: images > large 
                do: 
                - parse
                - normalize:
                    routine: url
                - object_field_set:
                    object: product
                    field: images
                    joinby: '|'           
    - object_save:
        name: product
