#wildberriesru digger
---
config:
    debug: 2
    agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
    keepalive: disable
do:
- counter_reset: pool
- variable_set: 
    field: repc
    value: "yes"
- walk:
    to: links
    repeat_in_pool: <%repc%>
    do:
    - variable_clear: repc
    - counter_increment:
        name: pool
    - find: 
        path: body 
        do: 
        - static_get: responseCode
        - if:
            match: 503|423|404
            do:
            - proxy_switch
            - cookie_reset
            - variable_set: 
                field: repc
                value: "yes"
            - counter_get: pool
            - if:
                gt: 5
                type: int
                do:
                - error: Server return 503 error code after 5 retries, exiting
                - exit
            - info: Server return 503 error code, retrying
            else:
            - counter_reset: pool
    - variable_clear: sku
    - find: 
        path: '#productNmId'
        slice: 0
        do: 
        - parse
        - if:
            match: \S
            do:
            - variable_set: sku
            - object_new: item
            - static_get: url
            - object_field_set:
                object: item
                field: url
            - find: 
                path: body
                in: doc
                do: 
                - find: 
                    path: meta[itemprop="brand"] 
                    do: 
                    - parse:
                        attr: content
                    - if:
                        match: \S
                        do:
                        - object_field_set:
                            object: item
                            field: brand
                - find: 
                    path: .product-params__cell:has(span:matches(Пол)) > td 
                    do: 
                    - parse
                    - space_dedupe
                    - trim
                    - if:
                        match: \S
                        do:
                        - object_field_set:
                            object: item
                            field: gender
                        
                - find: 
                    path: .j-description 
                    do: 
                    - parse
                    - space_dedupe
                    - trim
                    - if:
                        match: \S
                        do:
                        - object_field_set:
                            object: item
                            field: description
                - find: 
                    path: .same-part-kt__color > span 
                    do: 
                    - parse
                    - space_dedupe
                    - trim
                    - if:
                        match: \S
                        do:
                        - object_field_set:
                            object: item
                            field: color
                - find: 
                    path: .breadcrumbs__item
                    slice: 1:-2
                    do: 
                    - parse
                    - space_dedupe
                    - trim
                    - object_field_set:
                        object: item
                        field: categories
                        joinby: ","
                - find: 
                    path: '#imageContainer .j-zoom-photo'
                    do: 
                    - parse:
                        attr: src
                    - if:
                        match: \S
                        do:
                        - normalize:
                            routine: url
                        - object_field_set:
                            object: item
                            field: image
                - variable_get: sku
                - object_field_set:
                    object: item
                    field: sku
                - variable_set: 
                    field: rep
                    value: "yes"
                - counter_reset: sellerReq
                - walk:
                    to: https://wbx-content-v2.wbstatic.net/sellers/<%sku%>.json
                    repeat: <%rep%>
                    do:
                    - variable_clear: rep
                    - counter_increment:
                        name: sellerReq
                    - find: 
                        path: body 
                        do: 
                        - static_get: responseCode
                        - if:
                            match: 503|423|404
                            do:
                            - proxy_switch
                            - cookie_reset
                            - variable_set: 
                                field: rep
                                value: "yes"
                            - counter_get: sellerReq
                            - if:
                                gt: 5
                                type: int
                                do:
                                - error: Server return 503 error code after 5 retries, skipping
                            - info: Server return 503 error code, retrying
                            else:
                            - counter_reset: sellerReq
                    - find: 
                        path: supplierName 
                        do: 
                        - parse
                        - space_dedupe
                        - trim
                        - if:
                            match: \S
                            do:
                            - object_field_set:
                                object: item
                                field: seller
                - find: 
                    path: meta[itemprop="ratingValue"]
                    do: 
                    - parse:
                        attr: content
                    - space_dedupe
                    - trim
                    - if:
                        match: \d
                        do:
                        - object_field_set:
                            object: item
                            field: rating        
                - find: 
                    path: meta[itemprop="reviewCount"]
                    do: 
                    - parse:
                        attr: content
                    - space_dedupe
                    - trim
                    - if:
                        match: \d
                        do:
                        - object_field_set:
                            object: item
                            field: total_reviews
                - register_set: "yes"
                - object_field_set:
                    object: item
                    field: instock
                - find: 
                    path: meta[itemprop="price"]
                    do: 
                    - parse:
                        attr: content
                    - space_dedupe
                    - trim
                    - if:
                        match: \d
                        do:
                        - object_field_set:
                            object: item
                            field: price
                - object_save:
                    name: item
    