#wildberriesru digger
---
config:
    debug: 2
    agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
    keepalive: disable
do:
- variable_set:
    field: destination
    value: -1257786 # Moscow (https://static-basket-01.wbbasket.ru/vol0/j/spa/index.min.dd902511ef166807.js)
- counter_reset: pool
- variable_set: 
    field: repc
    value: "yes"
- walk:
    to: links
    repeat_in_pool: <%repc%>
    headers:
        Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9'
        Accept-Language: 'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7'
        Cache-Control: 'no-cache'
        Connection: 'keep-alive'
        Pragma: 'no-cache'
        Upgrade-Insecure-Requests: 1
        x-requested-with: ''
    do:
    - variable_clear: repc
    - counter_increment:
        name: pool
    - find: 
        path: body 
        do: 
        - static_get: responseCode
        - if:
            match: 503|423|404
            do:
            - proxy_switch
            - cookie_reset
            - variable_set: 
                field: repc
                value: "yes"
            - counter_get: pool
            - if:
                gt: 5
                type: int
                do:
                - error: Server return 503 error code after 5 retries, exiting
                - exit
            - info: Server return 503 error code, retrying
            else:
            - counter_reset: pool
    - variable_clear: query
    - variable_clear: shard
    - variable_clear: cat_name
    - variable_clear: pcat_name
    - variable_clear: filters
    - variable_clear: cats
    - find: 
        path: body 
        do: 
        - static_get: url
        - filter:
            args:
                - catalog\/(\d+)\/detail
        - variable_set: sku
        - register_set: 'https://card.wb.ru/cards/v2/detail?appType=1&curr=rub&dest=<%destination%>&spp=30&ab_testing=false&nm=<%sku%>'
        - counter_reset: item
        - variable_set: 
            field: repi
            value: "yes"
        - set_converter:
            converter: json
            content_type: text/plain
        - walk:
            to: <%register%>
            repeat: <%repi%>
            do:
            - variable_clear: repi
            - counter_increment:
                name: item
            - find: 
                path: body 
                do: 
                - static_get: responseCode
                - if:
                    match: 503|423|404
                    do:
                    - proxy_switch
                    - cookie_reset
                    - variable_set: 
                        field: repi
                        value: "yes"
                    - counter_get: item
                    - if:
                        gt: 5
                        type: int
                        do:
                        - error: Server return 503 error code after 5 retries, exiting
                        - exit
                    - info: Server return 503 error code, retrying
                    else:
                    - counter_reset: item
            - find: 
                path: products 
                do: 
                - object_new: item
                - find: 
                    path: id 
                    do: 
                    - parse
                    - space_dedupe
                    - trim
                    - object_field_set:
                        object: item
                        field: sku
                    - register_set: https://www.wildberries.ru/catalog/<%sku%>/detail.aspx
                    - object_field_set:
                        object: item
                        field: url
                    - register_set: "yes"
                    - object_field_set:
                        object: item
                        field: instock
                - find: 
                    path: pics 
                    do: 
                    - parse
                    - if:
                        gt: 0 
                        type: int
                        do:
                        - eval:
                            routine: js
                            body: '(function () {
                                 function getHost(e){
                                     return e >= 0 && e <= 143 ? "//basket-01.wbbasket.ru/" : e >= 144 && e <= 287 ? "//basket-02.wbbasket.ru/" : e >= 288 && e <= 431 ? "//basket-03.wbbasket.ru/" : e >= 432 && e <= 719 ? "//basket-04.wbbasket.ru/" : e >= 720 && e <= 1007 ? "//basket-05.wbbasket.ru/" : e >= 1008 && e <= 1061 ? "//basket-06.wbbasket.ru/" : e >= 1062 && e <= 1115 ? "//basket-07.wbbasket.ru/" : e >= 1116 && e <= 1169 ? "//basket-08.wbbasket.ru/" : e >= 1170 && e <= 1313 ? "//basket-09.wbbasket.ru/" : e >= 1314 && e <= 1601 ? "//basket-10.wbbasket.ru/" : e >= 1602 && e <= 1655 ? "//basket-11.wbbasket.ru/" : e >= 1656 && e <= 1919 ? "//basket-12.wbbasket.ru/" : e >= 1920 && e <= 2045 ? "//basket-13.wbbasket.ru/" : e >= 2046 && e <= 2189 ? "//basket-14.wbbasket.ru/" : e >= 2190 && e <= 2405 ? "//basket-15.wbbasket.ru/" : e >= 2406 && e <= 2621 ? "//basket-16.wbbasket.ru/" : e >= 2622 && e <= 2837 ? "//basket-17.wbbasket.ru/" : "//basket-18.wbbasket.ru/"
                                 }
                                 var n = <%sku%>;
                                 var first = ~~(n / 1e5);
                                 var second = ~~(n / 1e3);
                                 var host = getHost(first);
                                 return host+"vol"+first+"/part"+second+"/"+n+"/images/big/1.jpg"
                                })();'
                        - if:
                            match: \S
                            do:
                            - normalize:
                                routine: url
                            - object_field_set:
                                object: item
                                field: image
                - find: 
                    path: feedbacks
                    do: 
                    - parse
                    - space_dedupe
                    - trim
                    - if:
                        match: \d
                        do:
                        - object_field_set:
                            object: item
                            field: total_reviews
                - find: 
                    path: rating
                    do: 
                    - parse
                    - space_dedupe
                    - trim
                    - if:
                        match: \d
                        do:
                        - object_field_set:
                            object: item
                            field: rating
                - variable_clear: price
                - find: 
                    path: price > product
                    do: 
                    - parse
                    - if:
                        match: \d
                        do:
                        - eval:
                            routine: js
                            body: (function () {return <%register%>/100;})();
                        - if:
                            match: \d
                            do:
                            - object_field_set:
                                object: item
                                field: price
                            - variable_set: price
                - find: 
                    path: price > basic
                    do: 
                    - variable_get: price
                    - if:
                        match: \d
                        do:
                        - parse
                        - if:
                            match: \d
                            do:
                            - eval:
                                routine: js
                                body: (function () {return <%register%>/100;})();
                            - if:
                                match: \d
                                do:
                                - object_field_set:
                                    object: item
                                    field: price_old
                        else:
                        - parse
                        - if:
                            match: \d
                            do:
                            - eval:
                                routine: js
                                body: (function () {return <%register%>/100;})();
                            - if:
                                match: \d
                                do:
                                - object_field_set:
                                    object: item
                                    field: price
                                - object_field_set:
                                    object: item
                                    field: price_old
                                - variable_set: price
                - find: 
                    path: supplier
                    do: 
                    - parse
                    - space_dedupe
                    - trim
                    - object_field_set:
                        object: item
                        field: seller
                - find: 
                    path: brand
                    do: 
                    - parse
                    - space_dedupe
                    - trim
                    - if:
                        match: \S
                        do:
                        - object_field_set:
                            object: item
                            field: brand
                - variable_set: 
                    field: rep
                    value: "yes"
                - counter_reset: infoReq 
                - eval:
                    routine: js
                    body: '(function () {
                         function getHost(e){
                             return e >= 0 && e <= 143 ? "//basket-01.wbbasket.ru/" : e >= 144 && e <= 287 ? "//basket-02.wbbasket.ru/" : e >= 288 && e <= 431 ? "//basket-03.wbbasket.ru/" : e >= 432 && e <= 719 ? "//basket-04.wbbasket.ru/" : e >= 720 && e <= 1007 ? "//basket-05.wbbasket.ru/" : e >= 1008 && e <= 1061 ? "//basket-06.wbbasket.ru/" : e >= 1062 && e <= 1115 ? "//basket-07.wbbasket.ru/" : e >= 1116 && e <= 1169 ? "//basket-08.wbbasket.ru/" : e >= 1170 && e <= 1313 ? "//basket-09.wbbasket.ru/" : e >= 1314 && e <= 1601 ? "//basket-10.wbbasket.ru/" : e >= 1602 && e <= 1655 ? "//basket-11.wbbasket.ru/" : e >= 1656 && e <= 1919 ? "//basket-12.wbbasket.ru/" : e >= 1920 && e <= 2045 ? "//basket-13.wbbasket.ru/" : e >= 2046 && e <= 2189 ? "//basket-14.wbbasket.ru/" : e >= 2190 && e <= 2405 ? "//basket-15.wbbasket.ru/" : e >= 2406 && e <= 2621 ? "//basket-16.wbbasket.ru/" : e >= 2622 && e <= 2837 ? "//basket-17.wbbasket.ru/" : "//basket-18.wbbasket.ru/"
                         }
                         var n = <%sku%>;
                         var first = ~~(n / 1e5);
                         var second = ~~(n / 1e3);
                         var host = getHost(first);
                         return host+"vol"+first+"/part"+second+"/"+n+"/info/ru/card.json"
                        })();'
                - walk:
                    to: value
                    repeat: <%rep%>
                    do:
                    - variable_clear: rep
                    - counter_increment:
                        name: infoReq
                    - find: 
                        path: body 
                        do: 
                        - static_get: responseCode
                        - if:
                            match: 503|423|404
                            do:
                            - proxy_switch
                            - cookie_reset
                            - variable_set: 
                                field: repc
                                value: "yes"
                            - counter_get: infoReq
                            - if:
                                gt: 5
                                type: int
                                do:
                                - error: Server return 503 error code after 5 retries, skipping
                            - info: Server return 503 error code, retrying
                            else:
                            - counter_reset: infoReq
                    - find: 
                        path: nm_colors_names 
                        do: 
                        - parse
                        - space_dedupe
                        - trim
                        - if:
                            match: \S
                            do:
                            - object_field_set:
                                object: item
                                field: color
                    - find: 
                        path: description 
                        do: 
                        - parse
                        - space_dedupe
                        - trim
                        - if:
                            match: \S
                            do:
                            - object_field_set:
                                object: item
                                field: description
                    - find: 
                        path: subj_name, subj_root_name 
                        do: 
                        - parse
                        - space_dedupe
                        - trim
                        - object_field_set:
                            object: item
                            field: categories
                            joinby: ","
                    - find: 
                        path: imt_name
                        do: 
                        - parse
                        - space_dedupe
                        - trim
                        - object_field_set:
                            object: item
                            field: title
                - object_save:
                    name: item
        - clear_converter:
            content_type: text/plain
