#wildberriesru digger
---
config:
    debug: 2
    agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
    keepalive: disable
do:
- counter_reset: pool
- variable_set: 
    field: repc
    value: "yes"
- walk:
    to: links
    repeat_in_pool: <%repc%>
    headers:
        Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9'
        Accept-Language: 'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7'
        Cache-Control: 'no-cache'
        Connection: 'keep-alive'
        Pragma: 'no-cache'
        Upgrade-Insecure-Requests: 1
        x-requested-with: ''
    do:
    - variable_clear: repc
    - counter_increment:
        name: pool
    - find: 
        path: body 
        do: 
        - static_get: responseCode
        - if:
            match: 503|423|404
            do:
            - proxy_switch
            - cookie_reset
            - variable_set: 
                field: repc
                value: "yes"
            - counter_get: pool
            - if:
                gt: 5
                type: int
                do:
                - error: Server return 503 error code after 5 retries, exiting
                - exit
            - info: Server return 503 error code, retrying
            else:
            - counter_reset: pool
    - variable_clear: query
    - variable_clear: shard
    - variable_clear: cat_name
    - variable_clear: pcat_name
    - variable_clear: filters
    - variable_clear: cats
    - variable_clear: destination
    - counter_reset: loc
    - variable_set: 
        field: reploc
        value: "yes"
    - walk:
        repeat: <%reploc%>
        to:
            post: https://www.wildberries.ru/webapi/geo/getuserlocationinfo
            headers:
                x-requested-with: XMLHttpRequest
        do:
        - variable_clear: reploc
        - counter_increment:
            name: loc
        - find: 
            path: body 
            do: 
            - static_get: responseCode
            - if:
                match: 503|423|404
                do:
                - proxy_switch
                - cookie_reset
                - variable_set: 
                    field: reploc
                    value: "yes"
                - counter_get: loc
                - if:
                    gt: 5
                    type: int
                    do:
                    - error: Server return 503 error code after 5 retries, exiting
                    - exit
                - info: Server return 503 error code, retrying
                else:
                - counter_reset: loc
    - find: 
        path: body 
        do: 
        - static_get: url
        - filter:
            args:
                - catalog\/(\d+)\/detail
        - variable_set: sku
        - register_set: ''
        - cookie_get: __dst
        - variable_set: dst_cookie
        - eval:
            routine: js
            body: '(function () {return "<%dst_cookie%>".split("_").join(",");})();'
        - variable_set: destination
        - register_set: ''
        - cookie_get: __region
        - variable_set: region_cookie
        - eval:
            routine: js
            body: '(function () {return "<%region_cookie%>".split("_").join(",");})();'
        - variable_set: region
        - register_set: ''
        - cookie_get: __store
        - variable_set: store_cookie
        - eval:
            routine: js
            body: '(function () {return "<%store_cookie%>".split("_").join(",");})();'
        - variable_set: store
        - register_set: 'https://card.wb.ru/cards/detail?appType=1&locale=ru&lang=ru&curr=rub&dest=<%destination%>&reg=0&emp=0&regions=<%region%>&stores=<%store%>&nm=<%sku%>' 
        - counter_reset: item
        - variable_set: 
            field: repi
            value: "yes"
        - set_converter:
            converter: json
            content_type: text/plain
        - walk:
            to: <%register%>
            repeat: <%repi%>
            do:
            - variable_clear: repi
            - counter_increment:
                name: item
            - find: 
                path: body 
                do: 
                - static_get: responseCode
                - if:
                    match: 503|423|404
                    do:
                    - proxy_switch
                    - cookie_reset
                    - variable_set: 
                        field: repi
                        value: "yes"
                    - counter_get: item
                    - if:
                        gt: 5
                        type: int
                        do:
                        - error: Server return 503 error code after 5 retries, exiting
                        - exit
                    - info: Server return 503 error code, retrying
                    else:
                    - counter_reset: item
            - find: 
                path: products 
                do: 
                - object_new: item
                - find: 
                    path: id 
                    do: 
                    - parse
                    - space_dedupe
                    - trim
                    - object_field_set:
                        object: item
                        field: sku
                    - register_set: https://www.wildberries.ru/catalog/<%sku%>/detail.aspx
                    - object_field_set:
                        object: item
                        field: url
                    - register_set: "yes"
                    - object_field_set:
                        object: item
                        field: instock
                - find: 
                    path: pics 
                    do: 
                    - parse
                    - if:
                        gt: 0 
                        type: int
                        do:
                        - eval:
                            routine: js
                            body: '(function () {
                                 function getHost(e){
                                     return e >= 0 && e <= 143 ? "//basket-01.wb.ru/" : e >= 144 && e <= 287 ? "//basket-02.wb.ru/" : e >= 288 && e <= 431 ? "//basket-03.wb.ru/" : e >= 432 && e <= 719 ? "//basket-04.wb.ru/" : e >= 720 && e <= 1007 ? "//basket-05.wb.ru/" : e >= 1008 && e <= 1061 ? "//basket-06.wb.ru/" : e >= 1062 && e <= 1115 ? "//basket-07.wb.ru/" : e >= 1116 && e <= 1169 ? "//basket-08.wb.ru/" : e >= 1170 && e <= 1313 ? "//basket-09.wb.ru/" : e >= 1314 && e <= 1601 ? "//basket-10.wb.ru/" : e >= 1602 && e <= 1655 ? "//basket-11.wb.ru/" : "//basket-12.wb.ru/"
                                 }
                                 var n = <%sku%>;
                                 var first = ~~(n / 1e5);
                                 var second = ~~(n / 1e3);
                                 var host = getHost(first);
                                 return host+"vol"+first+"/part"+second+"/"+n+"/images/big/1.jpg"
                                })();'
                        - if:
                            match: \S
                            do:
                            - normalize:
                                routine: url
                            - object_field_set:
                                object: item
                                field: image
                - find: 
                    path: feedbacks
                    do: 
                    - parse
                    - space_dedupe
                    - trim
                    - if:
                        match: \d
                        do:
                        - object_field_set:
                            object: item
                            field: total_reviews
                - find: 
                    path: rating
                    do: 
                    - parse
                    - space_dedupe
                    - trim
                    - if:
                        match: \d
                        do:
                        - object_field_set:
                            object: item
                            field: rating
                - variable_clear: price
                - find: 
                    path: salePriceU 
                    do: 
                    - parse
                    - if:
                        match: \d
                        do:
                        - eval:
                            routine: js
                            body: (function () {return <%register%>/100;})();
                        - if:
                            match: \d
                            do:
                            - object_field_set:
                                object: item
                                field: price
                            - variable_set: price
                - find: 
                    path: priceU 
                    do: 
                    - variable_get: price
                    - if:
                        match: \d
                        else:
                        - parse
                        - if:
                            match: \d
                            do:
                            - eval:
                                routine: js
                                body: (function () {return <%register%>/100;})();
                            - if:
                                match: \d
                                do:
                                - object_field_set:
                                    object: item
                                    field: price
                                - variable_set: price
                - variable_set: 
                    field: rep
                    value: "yes"
                - counter_reset: sellerReq 
                - walk:
                    to: https://wbx-content-v2.wbstatic.net/sellers/<%sku%>.json
                    repeat: <%rep%>
                    do:
                    - variable_clear: rep
                    - counter_increment:
                        name: sellerReq
                    - find: 
                        path: body 
                        do: 
                        - static_get: responseCode
                        - if:
                            match: 503|423|404
                            do:
                            - proxy_switch
                            - cookie_reset
                            - variable_set: 
                                field: repc
                                value: "yes"
                            - counter_get: sellerReq
                            - if:
                                gt: 5
                                type: int
                                do:
                                - error: Server return 503 error code after 5 retries, skipping
                            - info: Server return 503 error code, retrying
                            else:
                            - counter_reset: sellerReq
                    - find: 
                        path: supplierName 
                        do: 
                        - parse
                        - space_dedupe
                        - trim
                        - if:
                            match: \S
                            do:
                            - object_field_set:
                                object: item
                                field: seller
                - variable_set: 
                    field: rep
                    value: "yes"
                - counter_reset: infoReq 
                - walk:
                    to: https://wbx-content-v2.wbstatic.net/ru/<%sku%>.json
                    repeat: <%rep%>
                    do:
                    - variable_clear: rep
                    - counter_increment:
                        name: infoReq
                    - find: 
                        path: body 
                        do: 
                        - static_get: responseCode
                        - if:
                            match: 503|423|404
                            do:
                            - proxy_switch
                            - cookie_reset
                            - variable_set: 
                                field: repc
                                value: "yes"
                            - counter_get: infoReq
                            - if:
                                gt: 5
                                type: int
                                do:
                                - error: Server return 503 error code after 5 retries, skipping
                            - info: Server return 503 error code, retrying
                            else:
                            - counter_reset: infoReq
                    - find: 
                        path: selling > brand_name 
                        do: 
                        - parse
                        - space_dedupe
                        - trim
                        - if:
                            match: \S
                            do:
                            - object_field_set:
                                object: item
                                field: brand
                    - find: 
                        path: kinds 
                        do: 
                        - parse
                        - space_dedupe
                        - trim
                        - if:
                            match: \S
                            do:
                            - object_field_set:
                                object: item
                                field: gender
                    - find: 
                        path: nm_colors_names 
                        do: 
                        - parse
                        - space_dedupe
                        - trim
                        - if:
                            match: \S
                            do:
                            - object_field_set:
                                object: item
                                field: color
                    - find: 
                        path: description 
                        do: 
                        - parse
                        - space_dedupe
                        - trim
                        - if:
                            match: \S
                            do:
                            - object_field_set:
                                object: item
                                field: description
                    - find: 
                        path: subj_name, subj_root_name 
                        do: 
                        - parse
                        - space_dedupe
                        - trim
                        - object_field_set:
                            object: item
                            field: categories
                            joinby: ","
                    - find: 
                        path: imt_name
                        do: 
                        - parse
                        - space_dedupe
                        - trim
                        - object_field_set:
                            object: item
                            field: title
                - object_save:
                    name: item
        - clear_converter:
            content_type: text/plain
