---
config:
    debug: 2
    agent: Firefox
do:
- walk:
    to: http://www.eloquii.com
    do:
    - find: 
        path: '#main-menu  > div > li > a' 
        do: 
        - pool_clear: main
        - parse:
            attr: href
        - normalize:
            routine: url
        - link_add:
            pool: main
        - walk:
            to: links
            pool: main
            do:
            - find: 
                path: .pagination a
                do: 
                - parse:
                    attr: href
                - normalize:
                    routine: url
                - link_add:
                    pool: main
            - find:
                path: .jscontainer
                do:
                - parse:
                    attr: href
                - normalize:
                    routine: replace_substring
                    args:
                        - \.html?.+: .html
                - link_add:
                    pool: sub
- walk:
    to: links
    pool: sub
    do:
    - sleep: 1
    - find:
        path: body.pdp
        do:
        - variable_clear: stop
        - variable_clear: sdecr
        - variable_clear: id
        - object_new: product
        - eval:
            routine: js
            body: '(function (){var d = new Date(); return d.toISOString()})();'
        - object_field_set:
            object: product
            field: date
        - static_get: url
        - object_field_set:
            object: product
            field: url
        - find: 
            in: doc
            path: head 
            do: 
            - find:
                path: link[rel="canonical"]
                do:
                - parse:
                    attr: href
                - parse:
                    attr: href
                    filter:
                    - .\/(\d+)\.html
                - variable_set: id
                - walk:
                    to: http://www.eloquii.com/on/demandware.store/Sites-eloquii-Site/default/Rii-XoqJson?productId=<%id%>
                    do:
                    - find:
                        path: post
                        do:
                        - find:
                            path: full
                            do:
                            - parse
                            - object_field_set:
                                joinby: "|"
                                object: product
                                field: images
            - find:
                path: meta[property="og:description"]
                do: 
                - parse:
                    attr: content
                - normalize:
                    routine: replace_matched
                    args:
                        null: ''
                - variable_set: sdecr
            - find:
                path: meta[property="og:description"]
                do:
                - parse:
                    attr: content
                - space_dedupe
                - trim
                - normalize:
                    routine: replace_matched
                    args:
                    - ^\s*null: ''
                - variable_set: sdecr
        - find:
            path: 'script:matches(app.execUjs\(\)\;)'
            do:
            - parse:
                filter: 
                    - .ProductController\(\s*{\s*data\s*\:\s*([.\w\W\d]+})\s*}\)\;
                    - .ProductController\(\s*{\s*\'OOS\'\:\s*true\,\s*\'data\'\s*:\s*([.\w\W\d]+})\s*}\)\;
                    - .ProductController\(\s*{\s*\'COMINGSOON\'\s*\:\s*true\s*\,\s*\'OOS\'\s*\:\s*true\,\s*\'data\'\s*:\s*([.\w\W\d]+})\s*}\)\;
            - normalize:
                routine: json2xml
            - to_block
            - find:
                path: 'images > xlarge > url'
                do:
                - parse
                - if:
                    match: (\S)
                    do:
                    - variable_set: stop
                    - object_field_set:
                        joinby: "|"
                        object: product
                        field: images
            - find:
                path: images > large > url
                do:
                - variable_get: stop
                - if:
                    match: (\S)
                    else:
                    - parse
                    - if:
                        match: (\S)
                        do:
                        - variable_set: stop
                        - object_field_set:
                            joinby: "|"
                            object: product
                            field: images
            - find:
                path: images > medium > url
                do:
                - variable_get: stop
                - if:
                    match: (\S)
                    else:
                    - parse
                    - if:
                        match: (\S)
                        do:
                        - object_field_set:
                            joinby: "|"
                            object: product
                            field: images
        - find:
            path: .item-number > span
            slice: 0
            do:
            - parse:
                attr: content
            - normalize:
                routine: replace_substring
                args:
                - 'sku:\s*': ''
            - object_field_set:
                object: product
                field: sku
        - find:
            in: doc
            path: head
            do:
            - find:
                path: meta[property="og:price:amount"]
                do:
                - parse:
                    attr: content
                    filter:
                        - (\d+\.?\d*)
                - if:
                    match: (\d+)
                    do:
                    - object_field_set:
                        object: product
                        type: float
                        field: price
                    - find:
                        in: doc
                        path: meta[property="og:price:currency"]
                        do:
                        - parse:
                            attr: content
                        - space_dedupe
                        - trim
                        - object_field_set:
                            object: product
                            field: currency
        - find:
            path: .swatch-hover > .color-title
            do:
            - parse
            - space_dedupe
            - trim
            - object_field_set:
                joinby: "|"
                object: product
                field: variations
        - variable_clear: list
        - find:
            path: 'div#breadcrumb a[itemprop="url"]'
            slice: 0:-2
            do:
            - parse
            - if:
                match: \w+
                do:
                - variable_set: list_item
                - object_field_set:
                    joinby: "|"
                    object: product
                    field: categories
        - find:
            path: .description 
            do: 
            - find: 
                path: p
                slice: 0
                do: 
                - variable_get: sdecr
                - if:
                    match: \S
                    else:
                    - parse
                    - space_dedupe
                    - trim
                    - variable_set: sdecr
        - variable_get: sdecr
        - object_field_set:
            object: product
            field: description
        - find:
            path: .productname
            do:
            - parse
            - space_dedupe
            - trim
            - object_field_set:
                object: product
                field: name
        - register_set: Eloquii
        - object_field_set:
            object: product
            field: brand
        - object_save:
            name: product
