---
config:
    debug: 2
    agent: Firefox
do:
- walk:
    to: https://www.farfetch.com/
    do:
    - find:
        path: li.tabs-gender > a.tabs-gender-a
        do:
        - parse:
            attr: data-async-link
        - space_dedupe
        - trim
        - if:
            match: \w+
            do:
            - walk:
                to: value
                do:
                - find:
                    path: ul.ff-secondary-nav>li>ul.ff-nav-ul>li>a.ff-nav-a
                    do:
                    - parse:
                        attr: href
                        filter: ^([^\?]+)
                    - space_dedupe
                    - trim
                    - if:
                        match: \w+
                        do:
                        - normalize:
                            routine: url
                        - link_add:
                            pool: catalog
    - find:
        path: ul.ff-primary-nav>li.ff-has-children>ul.ff-secondary-nav>li>ul.ff-nav-ul>li>a.ff-nav-a
        do:
        - parse:
            attr: href
            filter: ^([^\?]+)
        - space_dedupe
        - trim
        - if:
            match: \w+
            do:
            - normalize:
                routine: url
            - link_add:
                pool: catalog
- walk:
    to: links
    pool: catalog
    do:
    - variable_clear: pagetype
    - variable_clear: pricetype
    - variable_clear: gender
    - variable_clear: category
    - variable_clear: setid
    - variable_clear: scale
    - variable_clear: total
    - variable_clear: designer
    - find:
        path: script:contains("window['__initialState_slice-listing__']")
        do:
        - parse
        - normalize:
            routine: replace_substring
            args:
                window\[\'__initialState_slice-listing__\'\]: "var data"
        - eval:
            routine: js
            body: (function(){<%register%>; return JSON.stringify(data);})();
        - normalize:
            routine: json2xml
        - to_block
        - find:
            path: body_safe > pagetype
            do:
            - parse
            - variable_set: pagetype
        - find:
            path: body_safe > pricetype
            do:
            - parse
            - variable_set: pricetype
        - find:
            path: body_safe > gender
            do:
            - parse
            - variable_set: gender
        - find:
            path: body_safe > listing > category > id
            do:
            - parse:
                filter: (\d+)
            - if:
                match: \d+
                do:
                - register_set: "&c-category=<%register%>"
                - variable_set: category
        - find:
            path: body_safe > listing > designer > id
            do:
            - parse:
                filter: (\d+)
            - if:
                match: \d+
                do:
                - register_set: "&c-designer=<%register%>"
                - variable_set: designer
        - find:
            path: body_safe > listing > setid
            do:
            - parse:
                filter: (\d+)
            - if:
                match: \d+
                do:
                - register_set: "&setId=<%register%>"
                - variable_set: setid
        - find:
            path: body_safe > listing > selectedscale
            do:
            - parse
            - variable_set: scale
        - find:
            path: body_safe > listing > totalitems
            do:
            - parse
            - variable_set: total
        - variable_get: total
        - if:
            match: \d+
            do:
            - pool_clear: paginator
            - eval:
                routine: js
                body: (function(){var t = Math.ceil(<%total%>/180);var offset = [];for(var i = 1; i <= t; i++){offset.push(i)}; return offset.join(",");})();
            - to_block
            - split:
                context: text
                delimiter: ","
            - find:
                path: div
                do:
                - parse
                - if:
                    match: \d+
                    do:
                    - variable_set: page
                    - register_set: "https://www.farfetch.com/plpslice/listing-api/products-facets?page=<%page%>&view=180&pagetype=<%pagetype%>&gender=<%gender%>&pricetype=<%pricetype%>&scale=<%scale%><%category%><%setid%><%designer%>"
                    - link_add:
                        pool: paginator
            - walk:
                to: links
                pool: paginator
                do:
                - find:
                    path: products > id
                    do:
                    - parse
                    - space_dedupe
                    - trim
                    - if:
                        match: \d+
                        do:
                        - register_set: https://www.farfetch.com/item-<%register%>.aspx
                        - link_add:
                            pool: pages
                - sleep: 2
- walk:
    to: links
    pool: pages
    do:
    - sleep: 2
    - find:
        path: 'div#slice-pdp'
        do:
        - variable_clear: desc
        - object_new: product
        - eval:
            routine: js
            body: '(function (){var d = new Date(); return d.toISOString()})();'
        - object_field_set:
            object: product
            field: date
        - static_get: url
        - object_field_set:
            object: product
            field: url
        - find:
            path: meta[itemprop="name"]
            do:
            - parse:
                attr: content
            - space_dedupe
            - trim
            - object_field_set:
                object: product
                field: name
        - find:
            path: h1[itemprop="brand"] > a > span[itemprop="name"]
            do:
            - parse
            - space_dedupe
            - trim
            - object_field_set:
                object: product
                field: brand
        - find:
            path: meta[itemprop="productID"]
            do:
            - parse:
                attr: content
            - space_dedupe
            - trim
            - if:
                match: \w+
                do:
                - object_field_set:
                    object: product
                    field: sku
        - find:
            in: doc
            path: meta[itemprop="description"]
            do:
            - parse:
                attr: content
            - space_dedupe
            - trim
            - variable_set: desc
        - find:
            path: p[data-tstid="fullDescription"]
            do:
            - parse
            - space_dedupe
            - trim
            - variable_set: desc
        - find:
            path: meta[itemprop="color"]
            do:
            - parse:
                attr: content
            - space_dedupe
            - trim
            - if:
                match: \s*[A-Za-z]+
                do:
                - object_field_set:
                    object: product
                    joinby: "|"
                    field: variations
        - variable_get: desc
        - object_field_set:
            object: product
            field: description
        - find:
            in: doc
            path: script:contains("window['__initialState_slice-pdp__']")
            do:
            - parse
            - normalize:
                routine: replace_substring
                args:
                    window\[\'__initialState_slice-pdp__\'\]: "var data"
            - eval:
                routine: js
                body: (function(){<%register%>; return JSON.stringify(data);})();
            - normalize:
                routine: json2xml
            - to_block
            - find:
                path: images zoom
                do:
                - parse
                - space_dedupe
                - trim
                - if:
                    match: \w+
                    do:
                    - normalize:
                        routine: url
                    - object_field_set:
                        object: product
                        joinby: "|"
                        field: images
            - find:
                path: priceinfo > default > currencycode
                do:
                - parse
                - space_dedupe
                - trim
                - if:
                    match: \w+
                    do:
                    - object_field_set:
                        object: product
                        field: currency
            - find:
                path: priceinfo > default > initialprice
                do:
                - parse
                - space_dedupe
                - trim
                - if:
                    match: \d+
                    do:
                    - object_field_set:
                        object: product
                        type: float
                        field: price
            - find:
                path: priceinfo > default > finalprice
                do:
                - parse
                - space_dedupe
                - trim
                - if:
                    match: \d+
                    do:
                    - object_field_set:
                        object: product
                        type: float
                        field: price
        - find:
            path: ol[data-tstid="breadcrumb"]>li>a>span[itemprop="name"]
            slice: 1:-1
            do:
            - parse
            - space_dedupe
            - trim
            - if:
                match: \w+
                do:
                - object_field_set:
                    object: product
                    joinby: "|"
                    field: categories
        - object_save:
            name: product
