# olxcombr digger
---
config:
    agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
    debug: 2
do:
- variable_set:
    field: rip
    value: "yes"
- walk:
    to: links
    repeat_in_pool: <%rip%>
    do:
    - variable_clear: okp
    - find:
        path: 'div#content'
        do:
        - variable_set:
            field: okp
            value: 1
    - find:
        path: a[data-lurker-detail="next_page"]
        do:
        - parse:
            attr: href
        - link_add
    - find:
        path: 'ul#ad-list > li > a'
        do:
        - parse:
            attr: href
        - variable_set:
            field: repeat
            value: "yes"
        - walk:
            to: value
            repeat: <%repeat%>
            do:
            - variable_clear: ok
            - find:
                path: 'script#initial-data'
                do:
                - parse:
                    attr: data-json
                - normalize:
                    routine: json2xml
                - to_block
                - find:
                    path: body_safe > ad
                    do:
                    - variable_set:
                        field: ok
                        value: 1
                    - object_new: item
                    - find:
                        path: subject
                        do:
                        - parse
                        - space_dedupe
                        - trim
                        - object_field_set:
                            object: item
                            field: title
                    - find:
                        path: description
                        do:
                        - parse
                        - space_dedupe
                        - trim
                        - object_field_set:
                            object: item
                            field: description
                    - find:
                        path: listid
                        do:
                        - parse
                        - if:
                            match: \d+
                            do:
                            - object_field_set:
                                object: item
                                field: ad_id
                    - find:
                        path: listtime
                        do:
                        - parse
                        - space_dedupe
                        - trim
                        - object_field_set:
                            object: item
                            field: date
                    - find:
                        path: pricevalue
                        do:
                        - parse:
                            filter: (\d+)
                        - space_dedupe
                        - trim
                        - if:
                            match: \d+
                            do:
                            - object_field_set:
                                object: item
                                field: price
                    - find:
                        path: user > name
                        do:
                        - parse
                        - space_dedupe
                        - trim
                        - object_field_set:
                            object: item
                            field: seller
                    - find:
                        path: locationproperties > value
                        do:
                        - parse
                        - space_dedupe
                        - trim
                        - object_field_set:
                            object: item
                            field: address
                            joinby: ", "
                    - find:
                        path: images > original
                        slice: 0
                        do:
                        - parse:
                            filter: ^([^;]+)
                        - object_field_set:
                            object: item
                            field: image
                    - static_get: url
                    - object_field_set:
                        object: item
                        field: url
                    - find:
                        path: properties
                        do:
                        - find:
                            path: name
                            do:
                            - parse
                            - space_dedupe
                            - trim
                            - variable_set: fieldname
                        - find:
                            path: value
                            do:
                            - parse
                            - space_dedupe
                            - trim
                            - object_field_set:
                                object: item
                                field: <%fieldname%>
                    - find:
                        path: phone > phone
                        do:
                        - parse
                        - space_dedupe
                        - trim
                        - object_field_set:
                            object: item
                            field: phone
                    - object_save:
                        name: item
                    - cookie_reset
            - find:
                path: body
                do:
                - variable_get: ok
                - if:
                    match: 1
                    do:
                    - variable_clear: repeat
                    else:
                    - error: Proxy is banned or page layout has been changed
                    - cookie_reset
                    - proxy_switch
    - find:
        path: html
        do:
        - variable_get: okp
        - if:
            match: 1
            do:
            - cookie_reset
            - variable_set:
                field: rip
                value: "no"
            else:
            - error: Proxy is banned or page layout has been changed
            - cookie_reset
            - proxy_switch
            - variable_set:
                field: rip
                value: "yes"
