---
config:
    debug: 2
    agent: Chrome
do:
- walk:
    to: https://www.hermes.com/us/en/
    do:
    - find:
        path: ul.nav-list
        slice: 0
        do:
        - find:
            path: li:not(:haschild(ul))>a
            do:
            - parse:
                attr: href
            - if:
                match: \w+
                do:
                - normalize:
                    routine: url
                - link_add:
                    pool: catalog
- walk:
    to: links
    pool: catalog
    do:
    - find:
        path: script:contains('jQuery.extend(Drupal.settings')
        do:
        - parse
        - normalize:
            routine: replace_substring
            args:
                jQuery\.extend\(Drupal\.settings\,: 'var jsdata='
                \)\;$: ';'
        - eval:
            routine: js
            body: '(function (){<%register%> return JSON.stringify(jsdata)})();'
        - normalize:
            routine: json2xml
        - to_block
        - find:
            path: hermes_category>data
            do:
            - parse
            - variable_set: catid
            - variable_set:
                field: repeat
                value: 'yes'
            - counter_reset: offset
            - walk:
                repeat: <%repeat%>
                to:
                    json: https://www.hermes.com/apps/cde/personalize/grid/<%catid%>
                    payload: '{"offset":<%offset%>,"limit":100,"sort":"relevance","locale":"us_en","url_locale":"us/en"}'
                do:
                - find:
                    path: products>items>url
                    do:
                    - parse
                    - if:
                        match: \w+
                        do:
                        - if:
                            match: \/product\/look
                            else:
                            - register_set: https://www.hermes.com/us/en<%register%>
                            - link_add:
                                pool: pages
                - counter_increment:
                    name: offset
                    by: 100
                - find:
                    path: body_safe>total
                    do:
                    - parse
                    - if:
                        type: int
                        lt: <%offset%>
                        do:
                        - variable_set:
                            field: repeat
                            value: 'no'
- walk:
    to: links
    pool: pages
    do:
    - sleep: 2
    - find:
        path: 'section#product-detail'
        do:
        - hashmap_clear: cats
        - variable_clear: desc
        - object_new: product
        - eval:
            routine: js
            body: '(function (){var d = new Date(); return d.toISOString()})();'
        - object_field_set:
            object: product
            field: date
        - static_get: url
        - object_field_set:
            object: product
            field: url
        - find:
            path: 'div#variant-info>h1'
            do:
            - parse
            - space_dedupe
            - trim
            - if:
                match: \w+
                do:
                - object_field_set:
                    object: product
                    field: name
        - find:
            path: 'div#variant-info>div.field-type-commerce-price'
            do:
            - parse:
                filter: ([0-9\.\,]+)
            - normalize:
                routine: replace_substring
                args:
                    \,: ''
            - object_field_set:
                object: product
                type: float
                field: price
            - parse
            - normalize:
                routine: replace_matched
                args:
                - \$: USD
            - object_field_set:
                object: product
                field: currency
        - find:
            path: 'div#product-info>div.commerce-product-sku>p:contains("Product reference")>span'
            do:
            - parse
            - space_dedupe
            - trim
            - if:
                match: \w+
                do:
                - variable_set: pid
                - object_field_set:
                    object: product
                    field: sku
        - find:
            in: doc
            path: li.product-configurator-form-option:has(input[name="field_color_hermes"])>label>span.name
            do:
            - parse
            - space_dedupe
            - trim
            - if:
                match: \w+
                do:
                - object_field_set:
                    object: product
                    joinby: "|"
                    field: variations
        - find:
            path: div.product-image-wrap>a
            do:
            - parse:
                attr: href
            - space_dedupe
            - trim
            - if:
                match: \w+
                do:
                - normalize:
                    routine: url
                - object_field_set:
                    object: product
                    joinby: "|"
                    field: images
        - find:
            path: h2.field-name-field-description
            do:
            - node_remove: span.commerce-product-details
            - parse
            - space_dedupe
            - trim
            - object_field_set:
                object: product
                field: description
        - register_set: "Hermes"
        - object_field_set:
            object: product
            field: brand
        - find:
            in: doc
            path: script:contains('jQuery.extend(Drupal.settings')
            do:
            - parse
            - normalize:
                routine: replace_substring
                args:
                    jQuery\.extend\(Drupal\.settings\,: 'var jsdata='
                    \)\;$: ';'
            - eval:
                routine: js
                body: '(function (){<%register%> return JSON.stringify(jsdata)})();'
            - normalize:
                routine: json2xml
            - to_block
            - find:
                path: visitor_actions>pagecontext>taxonomy>productcategory
                do:
                - parse
                - space_dedupe
                - trim
                - if:
                    match: \w{2,}
                    do:
                    - variable_set: cat
                    - hashmap_get:
                        name: cats
                        field: <%cat%>
                    - if:
                        eq: 'yes'
                        else:
                        - hashmap_set:
                            name: cats
                            field: <%cat%>
                            value: 'yes'
                        - variable_get: cat
                        - object_field_set:
                            object: product
                            joinby: "|"
                            field: categories
        - object_save:
            name: product
