---
config:
    debug: 2
    agent: Firefox
do:
- walk:
    to: http://www.calypsostbarth.com/new-arrivals/clothing
    do:
    - find: 
        path: .col-side > ul > li 
        do: 
        - variable_clear: cat1
        - variable_clear: cat2
        - variable_clear: cat3
        - find: 
            path: a
            slice: 0
            do: 
            - parse
            - space_dedupe
            - trim
            - normalize:
                routine: lower
            - variable_set: cat1
        - parse:
            format: html
        - register_set: <div><ul><li><%register%></li></ul></div>
        - to_block
        - find: 
            path: div > ul > li > ul > li 
            do: 
            - variable_clear: cat2
            - variable_clear: cat3
            - find: 
                path: a
                slice: 0
                do: 
                - parse
                - space_dedupe
                - trim
                - normalize:
                    routine: lower
                - variable_set: cat2
                - parse:
                    attr: href
                - normalize:
                    routine: url
                - pool_clear: default
                - parse:
                    attr: href
                - link_add
                - walk:
                    to: links
                    do:
                    - find: 
                        path: .paging  li > a:matches([Nn]ext) 
                        do: 
                        - parse:
                            attr: href
                        - link_add
                    - find: 
                        path: .item > a 
                        do: 
                        - parse:
                            attr: href
                        - walk:
                            to: value
                            do:
                            - object_new: product
                            - find: 
                                in: doc
                                path: head 
                                do: 
                                - eval:
                                    routine: js
                                    body: '(function (){var d = new Date(); return d.toISOString()})();'
                                - object_field_set:
                                    object: product
                                    field: date
                                - static_get: url
                                - object_field_set:
                                    object: product
                                    field: url
                            - find: 
                                path: .tabbed li:nth-of-type(1) 
                                do: 
                                - parse
                                - space_dedupe
                                - trim
                                - if:
                                    match: (\S)
                                    do:
                                    - object_field_set:
                                        object: product
                                        field: description
                            - find: 
                                path: body 
                                do: 
                                - register_set: Calypso St. Barth
                                - object_field_set:
                                    object: product
                                    field: brand
                                - variable_get: cat1
                                - if:
                                    match: (\S)
                                    do:
                                    - object_field_set:
                                        object: product
                                        field: categories
                                        joinby: "|"
                                - variable_get: cat2
                                - if:
                                    match: (\S)
                                    do:
                                    - object_field_set:
                                        object: product
                                        field: categories
                                        joinby: "|"
                                - variable_get: cat3
                                - if:
                                    match: (\S)
                                    do:
                                    - object_field_set:
                                        object: product
                                        field: categories
                                        joinby: "|"
                            - find: 
                                path: .product-name > h1 
                                do: 
                                - parse
                                - space_dedupe
                                - trim
                                - object_field_set:
                                    object: product
                                    field: name
                            - find: 
                                path: img.cloudzoom-gallery, .image > img
                                do: 
                                - parse:
                                    attr: data-cloudzoom
                                - eval:
                                    routine: js
                                    body: (function () {var e = {<%register%>}; return JSON.stringify(e);})();
                                - normalize:
                                    routine: json2xml
                                - to_block
                                - find: 
                                    path: zoomImage 
                                    do: 
                                    - parse
                                    - normalize:
                                        routine: url
                                    - object_field_set:
                                        object: product
                                        field: images
                                        joinby: "|"
                            - find: 
                                path: script:matches(var\s*spConfig) 
                                do: 
                                - parse:
                                    filter:
                                        - Product\.Config\((.+)\);
                                - normalize:
                                    routine: json2xml
                                - to_block
                                - find: 
                                    path: 'attributes > *:hasChild(code:matches(color)) > options > label'
                                    do: 
                                    - parse
                                    - space_dedupe
                                    - trim
                                    - object_field_set:
                                        object: product
                                        field: variations
                                        joinby: "|"
                                - find: 
                                    path: body_safe > productid 
                                    do: 
                                    - parse
                                    - space_dedupe
                                    - trim
                                    - object_field_set:
                                        object: product
                                        field: sku
                                - find: 
                                    path: body_safe > baseprice
                                    do: 
                                    - parse
                                    - if:
                                        match: (\d)
                                        do:
                                        - object_field_set:
                                            object: product
                                            field: price
                                            type: float
                                        - register_set: USD
                                        - object_field_set:
                                            object: product
                                            field: currency
                            - object_save:
                                name: product
            - find: 
                path: ul > li > a 
                do: 
                - parse
                - space_dedupe
                - trim
                - normalize:
                    routine: lower
                - variable_set: cat3
                - parse:
                    attr: href
                - normalize:
                    routine: url
                - pool_clear: default
                - parse:
                    attr: href
                - link_add
                - walk:
                    to: links
                    do:
                    - find: 
                        path: .paging  li > a:matches([Nn]ext) 
                        do: 
                        - parse:
                            attr: href
                        - link_add
                    - find: 
                        path: .item > a 
                        do: 
                        - parse:
                            attr: href
                        - walk:
                            to: value
                            do:
                            - object_new: product
                            - find: 
                                in: doc
                                path: head 
                                do: 
                                - eval:
                                    routine: js
                                    body: '(function (){var d = new Date(); return d.toISOString()})();'
                                - object_field_set:
                                    object: product
                                    field: date
                                - static_get: url
                                - object_field_set:
                                    object: product
                                    field: url
                            - find: 
                                path: .tabbed li:nth-of-type(1) 
                                do: 
                                - parse
                                - space_dedupe
                                - trim
                                - if:
                                    match: (\S)
                                    do:
                                    - object_field_set:
                                        object: product
                                        field: description
                            - find: 
                                path: body 
                                do: 
                                - register_set: Calypso St. Barth
                                - object_field_set:
                                    object: product
                                    field: brand
                                - variable_get: cat1
                                - if:
                                    match: (\S)
                                    do:
                                    - object_field_set:
                                        object: product
                                        field: categories
                                        joinby: "|"
                                - variable_get: cat2
                                - if:
                                    match: (\S)
                                    do:
                                    - object_field_set:
                                        object: product
                                        field: categories
                                        joinby: "|"
                                - variable_get: cat3
                                - if:
                                    match: (\S)
                                    do:
                                    - object_field_set:
                                        object: product
                                        field: categories
                                        joinby: "|"
                            - find: 
                                path: .product-name > h1 
                                do: 
                                - parse
                                - space_dedupe
                                - trim
                                - object_field_set:
                                    object: product
                                    field: name
                                
                            - find: 
                                path: img.cloudzoom-gallery, .image > img
                                do: 
                                - parse:
                                    attr: data-cloudzoom
                                - eval:
                                    routine: js
                                    body: (function () {var e = {<%register%>}; return JSON.stringify(e);})();
                                - normalize:
                                    routine: json2xml
                                - to_block
                                - find: 
                                    path: zoomImage 
                                    do: 
                                    - parse
                                    - normalize:
                                        routine: url
                                    - object_field_set:
                                        object: product
                                        field: images
                                        joinby: "|"
                            - find: 
                                path: script:matches(var\s*spConfig) 
                                do: 
                                - parse:
                                    filter:
                                        - Product\.Config\((.+)\);
                                - normalize:
                                    routine: json2xml
                                - to_block
                                - find: 
                                    path: 'attributes > *:hasChild(code:matches(color)) > options > label'
                                    do: 
                                    - parse
                                    - space_dedupe
                                    - trim
                                    - object_field_set:
                                        object: product
                                        field: variations
                                        joinby: "|"
                                - find: 
                                    path: body_safe > productid 
                                    do: 
                                    - parse
                                    - space_dedupe
                                    - trim
                                    - object_field_set:
                                        object: product
                                        field: sku
                                - find: 
                                    path: body_safe > baseprice 
                                    do: 
                                    - parse
                                    - if:
                                        match: (\d)
                                        do:
                                        - object_field_set:
                                            object: product
                                            field: price
                                            type: float
                                        - register_set: USD
                                        - object_field_set:
                                            object: product
                                            field: currency
                            - object_save:
                                name: product
